Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2019-10, with the labels that each got.

#278 [v1alpha2] machines: Re-enable support for availability zones
  api/v1alpha2/azuremachine_types.go
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/scope/machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  controllers/azuremachine_reconciler.go
  examples/controlplane/controlplane.yaml
  examples/generate.sh
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#279 [v1alpha2] Update Calico and temporarily move CNI deployment
  Makefile
  examples/addons.yaml
  examples/controlplane/controlplane.yaml
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, release-note, size/M

#282 Fix manifest generation failures
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  examples/generate.sh
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#286 Align Makefile (release) and hack/tools with other repos
  Makefile
  cloudbuild.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, release-note-none, size/L

#285 OWNERS: Add CAPI maintainers and update labels for SIG Cluster Lifecycle
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, size/S

#287 [v1alpha1] Update/rename scripts to pass CI
  Makefile
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
  hack/verify-boilerplate.sh
  scripts/ci-build.sh
  scripts/ci-e2e.sh
  scripts/ci-integration.sh
  scripts/ci-test.sh
  test/e2e/util/kind/setup.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/important-longterm, release-note-none, size/L

#288 Update default Kubernetes version to v1.16.1
  .gitignore
  README.md
  examples/generate.sh
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, priority/important-soon, release-note, sig/cluster-lifecycle, size/XS

#289 Update containerd to v1.3.0 and allow configurable versions
  config/default/kustomization.yaml
  config/default/manager_pull_policy.yaml
  examples/controlplane/controlplane.yaml
  examples/generate.sh
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, area/provider/azure, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/cluster-lifecycle, size/M

#290 🐛 Delete cluster retries forever if group does not exist
  cloud/services/groups/groups.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, ok-to-test, release-note, sig/cluster-lifecycle, size/XS

#291 :sparkles: Support specifying VM images by ID or from Shared Image Gallery
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/defaults.go
  cloud/services/virtualmachines/virtualmachines.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  examples/controlplane/controlplane.yaml
  examples/generate.sh
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, priority/important-soon, release-note, sig/cluster-lifecycle, size/L

#295 :bug: Validate a location supports Availability Zones before VM creation
  cloud/defaults.go
  controllers/azuremachine_reconciler.go
Labels: approved, area/provider/azure, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note, sig/cluster-lifecycle, size/M

#297 🐛 Support running alongside other Cluster API pods in the same namespace with leader election enabled
  main.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, ok-to-test, release-note-action-required, sig/cluster-lifecycle, size/XS

#296 Add rule to verify generated codes and manifests
  Makefile
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/XS

#304 update release binary golang version
  Makefile
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/XS

#303 test: add some unit tests
  controllers/azuremachine_reconciler.go
  controllers/azuremachine_reconciler_test.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/L

#305 update golang version in Dockerfile
  Dockerfile
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/XS

#306 Update golang to 1.12.11
  Dockerfile
  Makefile
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/XS

#308 🏃 Corrected 'control-plane' labels prefix
  config/manager/manager.yaml
  config/rbac/auth_proxy_service.yaml
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, ok-to-test, release-note, sig/cluster-lifecycle, size/S

#302 Add default 1.16 image and remove prekubeadm commands
  Makefile
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/services/virtualmachines/virtualmachines.go
  docs/getting-started.md
  examples/controlplane/controlplane.yaml
  examples/generate.sh
  examples/machinedeployment/machinedeployment.yaml
  go.mod
  go.sum
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/XL
