Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2019-11, with the labels that each got.

#317 ✨ support exisiting resource group
  cloud/services/groups/groups.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/M

#320 🏃 update image reference to use first party image
  cloud/services/virtualmachines/virtualmachines.go
  docs/getting-started.md
  examples/controlplane/controlplane.yaml
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/M

#321 🐛 fix auth in cloud provider
  examples/controlplane/controlplane.yaml
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, ok-to-test, release-note, sig/cluster-lifecycle, size/M

#322 Add CecileRobertMichon as approver
  OWNERS_ALIASES
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/XS

#323 🏃 Update capi to 0.2.7
  go.mod
  go.sum
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/XS

#328 🏃 Add default Marketplace image logic
  api/v1alpha2/azuremachine_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/defaults.go
  cloud/services/virtualmachines/virtualmachines.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  controllers/azuremachine_reconciler.go
  examples/controlplane/controlplane.yaml
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/L

#329 🏃 Populate address status fields on azuremachines
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/services/virtualmachines/virtualmachines.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  controllers/azuremachine_controller.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, ok-to-test, release-note-none, sig/cluster-lifecycle, size/L

#327 ✨ support the ability for public IPs on azuremachines
  api/v1alpha2/azuremachine_types.go
  cloud/services/networkinterfaces/networkinterfaces.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  controllers/azuremachine_reconciler.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, ok-to-test, release-note-none, sig/cluster-lifecycle, size/M

#331 fix: developer getting started docs with working example
  Makefile
  docs/development.md
  examples/controlplane/controlplane.yaml
  examples/generate.sh
  examples/wait-for-ready.sh
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/L

#332 fix: make test should work without having to run ./script/ci-test first
  Makefile
  scripts/ci-test.sh
  scripts/fetch_ext_bins.sh
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/M

#333 :runner: placeholder e2e shell script
  scripts/ci-e2e.sh
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, ok-to-test, release-note-none, sig/cluster-lifecycle, size/S
