Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2019-01, with the labels that each got.

#47 Update import path for kubernetes-sig
  cmd/clusterctl/main.go
  cmd/manager/main.go
  pkg/apis/addtoscheme_azureprovider_v1alpha1.go
  pkg/apis/azureprovider/v1alpha1/doc.go
  pkg/apis/azureprovider/v1alpha1/register.go
  pkg/cloud/azure/actuators/cluster/clusteractuator.go
  pkg/cloud/azure/actuators/cluster/clusteractuator_test.go
  pkg/cloud/azure/actuators/machine/machine_status.go
  pkg/cloud/azure/actuators/machine/machineactuator.go
  pkg/cloud/azure/actuators/machine/machineactuator_test.go
  pkg/cloud/azure/services/interfaces.go
  pkg/cloud/azure/services/mock_interfaces.go
  pkg/cloud/azure/services/mock_interfaces_helper.go
  pkg/cloud/azure/services/resourcemanagement/deployments.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#46 Improve readme for better usability
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#50 Improve generate-yaml.sh
  cmd/clusterctl/examples/azure/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#54 fix goreportcard links and ineffassign issues
  README.md
  pkg/cloud/azure/actuators/machine/machineactuator_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#60 Adds pull request, feature request and bug report templates.
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/pull_request_template.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#61 updated the golang version in dockerfile
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#62 check command, to be used in test-infra
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#64 docs: Minor improvements in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#65 Rename crds
  config/crds/azureprovider_v1alpha1_azureclusterproviderspec.yaml
  config/crds/azureprovider_v1alpha1_azuremachineproviderspec.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#66 ran gofmt on machine_status.go, machineactuator.go and virtualnetwork…
  pkg/cloud/azure/actuators/machine/machine_status.go
  pkg/cloud/azure/actuators/machine/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#69 Misc cleanup to unused packages and adding copyright header
  pkg/cloud/azure/actuators/machine/machinesetup/types.go
  pkg/cloud/azure/actuators/machine/status.go
  pkg/cloud/azure/actuators/machine/testconfigs/cluster-ci-create-rg.yaml
  pkg/cloud/azure/actuators/machine/testconfigs/cluster-ci-create-update-existing.yaml
  pkg/cloud/azure/actuators/machine/testconfigs/cluster-ci-create-update.yaml
  pkg/cloud/azure/actuators/machine/testconfigs/cluster-ci-create.yaml
  pkg/cloud/azure/actuators/machine/testconfigs/cluster-ci-delete-single.yaml
  pkg/cloud/azure/actuators/machine/testconfigs/cluster-ci-delete.yaml
  pkg/cloud/azure/actuators/machine/testconfigs/cluster-ci-get-ip.yaml
  pkg/cloud/azure/actuators/machine/testconfigs/cluster-ci-parse-providers.yaml
  pkg/cloud/azure/actuators/machine/testconfigs/cluster-ci-rg-exists.yaml
  pkg/cloud/azure/actuators/machine/testconfigs/cluster-ci-vm-exists.yaml
  pkg/cloud/azure/actuators/machine/testconfigs/machines.yaml
  test/e2e/azure.go
  test/e2e/e2e_test.go
  test/e2e/kube.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#70 Update Golang image to the latest patch release
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#71 Fix all linting issues and improve the make check workflow
  .golangci.yml
  Makefile
  cmd/clusterctl/main.go
  cmd/manager/main.go
  pkg/cloud/azure/actuators/cluster/actuator.go
  pkg/cloud/azure/actuators/cluster/actuator_test.go
  pkg/cloud/azure/actuators/machine/actuator.go
  pkg/cloud/azure/actuators/machine/actuator_test.go
  pkg/cloud/azure/actuators/machine/status.go
  pkg/cloud/azure/services/network/virtualnetworks.go
  test/e2e/e2e_test.go
  test/e2e/kube.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#72 Added GOBIN path in Makefile if not present
  .gitignore
  Gopkg.lock
  Makefile
  test/e2e/kube.go
  vendor/github.com/gobuffalo/envy/.env
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, ok-to-test, size/L

#73 Added kube.go back, and its imports in gopkg.lock
  Gopkg.lock
  test/e2e/kube.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#77 Fix issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cncf-cla: yes, lgtm, sig/azure, size/S

#79 Removed files related with az pipelines
  README.md
  azure-pipelines.yml
  ci/azure-pipelines-build-test.yml
  ci/azure-pipelines-e2e.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/azure, size/L

#78 Register all default controllers, which includes machineset and machi…
  Gopkg.lock
  cmd/manager/main.go
  vendor/k8s.io/apimachinery/pkg/api/equality/semantic.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/azure, size/L

#84 Add Azure manager template
  cmd/clusterctl/examples/azure/azure_manager_image_patch.yaml.template
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/azure, size/S
