Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2020-01, with the labels that each got.

#340 ✨Add support for BYO vnet
  api/v1alpha2/types.go
  cloud/errors.go
  cloud/scope/cluster.go
  cloud/services/disks/disks.go
  cloud/services/groups/groups.go
  cloud/services/internalloadbalancers/internalloadbalancers.go
  cloud/services/internalloadbalancers/service.go
  cloud/services/networkinterfaces/networkinterfaces.go
  cloud/services/publicips/publicips.go
  cloud/services/publicloadbalancers/publicloadbalancers.go
  cloud/services/routetables/routetables.go
  cloud/services/securitygroups/securitygroups.go
  cloud/services/subnets/subnets.go
  cloud/services/virtualmachineextensions/virtualmachineextensions.go
  cloud/services/virtualmachines/virtualmachines.go
  cloud/services/virtualmachines/virtualmachines_test.go
  cloud/services/virtualnetworks/client.go
  cloud/services/virtualnetworks/mock_virtualnetworks/virtualnetworks_mock.go
  cloud/services/virtualnetworks/virtualnetworks.go
  cloud/services/virtualnetworks/virtualnetworks_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  controllers/azurecluster_reconciler.go
  controllers/azuremachine_reconciler.go
  controllers/azuremachine_tags.go
  docs/topics/custom-vnet.md
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/XL

#358 Change kind min version to 0.6.1
  Makefile
  docs/development.md
  docs/getting-started.md
  examples/wait-for-ready.sh
  hack/ensure-kind.sh
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/M

#357 Updating getting started doc
  docs/getting-started.md
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, ok-to-test, release-note-none, sig/cluster-lifecycle, size/M

#361 add unit tests for azure security groups
  cloud/services/securitygroups/securitygroups_test.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/L

#362 Update capi to 0.2.9
  examples/generate.sh
  go.mod
  go.sum
  test/e2e/azure_suite_test.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/S

#363 add unit tests for subnets in the cloud services package
  cloud/services/subnets/subnets_test.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/L

#367 increase e2e timeout for delete cluster to 20 min
  test/e2e/framework/clean_up.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/XS

#365 Add unit tests for internalloadbalancers
  cloud/services/internalloadbalancers/internalloadbalancers_test.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, ok-to-test, release-note-none, sig/cluster-lifecycle, size/L

#366 Add unit tests for availabilityzones
  cloud/services/availabilityzones/availabilityzones_test.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, ok-to-test, release-note-none, sig/cluster-lifecycle, size/L

#368 Add nader-ziada as reviewer
  OWNERS_ALIASES
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/XS

#364 Add 3 control plane cluster E2E test
  .gitignore
  Makefile
  test/e2e/azure_suite_test.go
  test/e2e/azure_test.go
  test/e2e/control_plane_cluster_test.go
  test/e2e/framework/framework_flags.go
  test/e2e/framework/types.go
  test/e2e/one_node_cluster_test.go
  test/e2e/resource_generators.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/XXL

#369 reorder OWNERS aliases alphabetically
  OWNERS_ALIASES
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/XS

#370 Update default k8s version to 1.16.6
  examples/generate.sh
  test/e2e/framework/framework_flags.go
Labels: approved, area/dependency, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/XS

#372 Add tags to e2e resource groups
  test/e2e/resource_generators.go
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/XS

#373 docs: update the readme to point to capi book and cleanup docs
  README.md
  docs/development.md
  docs/getting-started.md
Labels: approved, area/provider/azure, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/L
