Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2022-12, with the labels that each got.

#2888 [release-1.5] update latest-1.21 to latest-1.25
  docs/book/src/developers/development.md
  docs/book/src/topics/custom-images.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2889 replace xargs with for loop in gen-flavors.sh
  hack/common-vars.sh
  hack/gen-flavors.sh
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#2861 add e2e AKS upgrade test
  test/e2e/aks.go
  test/e2e/azure_test.go
  test/e2e/common.go
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2894 Convert resourceGroup name in ID for VMSS vms to lower case to keep it compatible with the rest of capz
  azure/converters/vmss.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, ok-to-test, lgtm

#2846 Add cluster's name to MachinePool and AzureManagedMachinePool in AKS templates
  exp/controllers/azuremanagedmachinepool_reconciler.go
  templates/cluster-template-aks.yaml
  templates/flavors/aks/cluster-template.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
  templates/test/ci/prow-aks/patches/aks-pool0.yaml
  templates/test/ci/prow-aks/patches/aks-pool1.yaml
  templates/test/ci/prow-aks/patches/aks-pool2.yaml
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#2773 Uplift CAPI to v1.3.0 minor release
  .golangci.yml
  Makefile
  Tiltfile
  api/v1alpha3/azurecluster_types.go
  api/v1alpha4/azurecluster_types.go
  api/v1beta1/azurecluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  controllers/azurecluster_controller_test.go
  controllers/azuremachine_controller_test.go
  controllers/suite_test.go
  docs/book/src/developers/development.md
  docs/book/src/topics/gpu.md
  exp/controllers/azuremachinepool_controller_test.go
  exp/controllers/suite_test.go
  go.mod
  go.sum
  hack/create-dev-cluster.sh
  hack/install-cert-manager.sh
  hack/tools/go.mod
  hack/tools/go.sum
  internal/test/env/env.go
  test/e2e/aks.go
  test/e2e/azure_clusterproxy.go
  test/e2e/azure_csidriver.go
  test/e2e/azure_failuredomains.go
  test/e2e/azure_gpu.go
  test/e2e/azure_lb.go
  test/e2e/azure_machinepool_drain.go
  test/e2e/azure_net_pol.go
  test/e2e/azure_privatecluster.go
  test/e2e/azure_selfhosted.go
  test/e2e/azure_test.go
  test/e2e/azure_vmextensions.go
  test/e2e/capi_test.go
  test/e2e/cloud-provider-azure.go
  test/e2e/cni.go
  test/e2e/common.go
  test/e2e/config/azure-dev.yaml
  test/e2e/conformance_test.go
  test/e2e/csi_migration_test.go
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/helpers.go
  test/e2e/kubescape.go
  test/e2e/log.go
Labels: kind/feature, cncf-cla: yes, release-note-none, approved, size/XXL, lgtm

#2807 Default Ubuntu to 22.04 for new k8s versions
  azure/services/virtualmachineimages/images.go
  azure/services/virtualmachineimages/images_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#2781 feat: AKS node pool KubeletConfig
  azure/converters/managedagentpool.go
  azure/scope/managedmachinepool.go
  azure/services/agentpools/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  docs/book/src/topics/managedcluster.md
  exp/api/v1alpha3/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremanagedmachinepool_types.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  exp/controllers/helpers_test.go
  templates/cluster-template-aks.yaml
  templates/flavors/aks/cluster-template.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, lgtm, area/managedclusters

#2913 Move AKS config from reference to test template
  templates/cluster-template-aks.yaml
  templates/flavors/aks/cluster-template.yaml
  templates/test/ci/prow-aks/patches/aks-pool0.yaml
  templates/test/ci/prow-aks/patches/aks-pool1.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#2646 Enable race detector for unit tests
  Makefile
  api/v1beta1/azuremachinetemplate_webhook_test.go
  azure/services/inboundnatrules/inboundnatrules_test.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, lifecycle/active, lgtm, kind/failing-test

#2893 Add clusterCIDR to cloud provider e2e install
  docs/book/src/topics/addons.md
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2916 fix deleting all tags on AKS resources
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#2910 Add logging for empty RoleAssignmentName
  azure/services/roleassignments/roleassignments.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note, approved, ok-to-test, lgtm

#2909 split out AKS E2E source files
  test/e2e/aks.go
  test/e2e/aks_autoscaler.go
  test/e2e/aks_machinepools.go
  test/e2e/aks_public_ip_prefix.go
  test/e2e/aks_upgrade.go
  test/e2e/aks_versions.go
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm

#2752 feat : dependabot workflow automation for updating dependency
  .github/dependabot.yml
  .github/workflows/dependabot-code-gen.yml
Labels: kind/feature, cncf-cla: yes, tide/merge-method-squash, size/M, release-note, approved, ok-to-test, lgtm

#2928 [release-1.6] fix deleting all tags on AzureManagedControlPlane
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, lgtm

#2926 fix: workflow run schedule interval
  .github/dependabot.yml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#2930 [release-1.6] fix machine pool wait in AKS e2e test
  test/e2e/azure_test.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2895 Use function 'ConvertResourceGroupNameToLower' from 'cloud-provider-azure' provider pkg
  azure/converters/vmss.go
  azure/services/scalesets/scalesets.go
  azure/services/virtualmachines/virtualmachines.go
  exp/controllers/azuremanagedmachinepool_reconciler.go
  go.mod
  go.sum
  util/azure/azure.go
  util/azure/azure_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, ok-to-test, lgtm

#2920 remove --listen-client-urls injection from ipv6 template
  templates/cluster-template-ipv6.yaml
  templates/flavors/ipv6/patches/kubeadm-controlplane.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2528 Add support for configurable VM Diagnostics
  api/v1alpha3/azuremachine_conversion.go
  api/v1alpha3/azuremachinetemplate_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/azuremachine_conversion.go
  api/v1alpha4/azuremachinetemplate_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/azuremachine_default.go
  api/v1beta1/azuremachine_types.go
  api/v1beta1/azuremachine_validation.go
  api/v1beta1/azuremachine_webhook.go
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/converters/diagnostics.go
  azure/converters/diagnostics_test.go
  azure/scope/machine.go
  azure/scope/machinepool.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
  azure/services/virtualmachines/spec.go
  azure/services/virtualmachines/spec_test.go
  azure/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  docs/book/src/topics/troubleshooting.md
  docs/book/src/topics/vm-diagnostics.md
  exp/api/v1alpha3/azuremachinepool_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremachinepool_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremachinepool_default.go
  exp/api/v1beta1/azuremachinepool_default_test.go
  exp/api/v1beta1/azuremachinepool_test.go
  exp/api/v1beta1/azuremachinepool_types.go
  exp/api/v1beta1/azuremachinepool_webhook.go
  exp/api/v1beta1/azuremachinepool_webhook_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, lifecycle/active, size/XXL, ok-to-test, lgtm

#2931 Update windows kube-proxy to deploy to kube-system
  templates/addons/windows/calico/kube-proxy-windows.yaml
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/cni.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#2917 add e2e test for AKS resource tag operations
  test/e2e/aks_tags.go
  test/e2e/azure_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2829 log ManagedCluster spec changes at higher verbosity
  azure/interfaces.go
  azure/mock_azure/azure_mock.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/async/async.go
  azure/services/async/async_test.go
  azure/services/availabilitysets/spec.go
  azure/services/availabilitysets/spec_test.go
  azure/services/bastionhosts/spec.go
  azure/services/disks/spec.go
  azure/services/groups/spec.go
  azure/services/inboundnatrules/spec.go
  azure/services/loadbalancers/spec.go
  azure/services/loadbalancers/spec_test.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  azure/services/natgateways/spec.go
  azure/services/networkinterfaces/spec.go
  azure/services/networkinterfaces/spec_test.go
  azure/services/privatedns/link_spec.go
  azure/services/privatedns/link_spec_test.go
  azure/services/privatedns/record_spec.go
  azure/services/privatedns/record_spec_test.go
  azure/services/privatedns/zone_spec.go
  azure/services/privatedns/zone_spec_test.go
  azure/services/publicips/spec.go
  azure/services/publicips/spec_test.go
  azure/services/roleassignments/spec.go
  azure/services/routetables/spec.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/vmssextension_spec.go
  azure/services/scalesets/vmssextension_spec_test.go
  azure/services/securitygroups/spec.go
  azure/services/securitygroups/spec_test.go
  azure/services/subnets/spec.go
  azure/services/subnets/spec_test.go
  azure/services/virtualmachines/spec.go
  azure/services/virtualmachines/spec_test.go
  azure/services/virtualnetworks/spec.go
  azure/services/vmextensions/spec.go
  azure/services/vmextensions/spec_test.go
  azure/services/vnetpeerings/spec.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2748 Use azidentity instead of ADAL
  azure/scope/clients.go
  azure/scope/identity.go
  go.mod
  go.sum
  test/e2e/aks_autoscaler.go
  test/e2e/aks_public_ip_prefix.go
  test/e2e/aks_upgrade.go
  test/e2e/aks_versions.go
  test/e2e/azure_clusterproxy.go
  test/e2e/azure_logcollector.go
  test/e2e/azure_privatecluster.go
  test/e2e/azure_vmextensions.go
  test/e2e/common.go
  test/e2e/helpers.go
  util/azure/azure.go
Labels: cncf-cla: yes, size/L, approved, release-note-action-required, ok-to-test, lgtm

#2939 Move alexeldeib to emeritus status
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#2738 add AKS resource health to AzureManagedControlPlane
  api/v1beta1/conditions_consts.go
  azure/converters/resourcehealth.go
  azure/converters/resourcehealth_test.go
  azure/defaults.go
  azure/scope/managedcontrolplane.go
  azure/services/resourcehealth/client.go
  azure/services/resourcehealth/mock_resourcehealth/client_mock.go
  azure/services/resourcehealth/mock_resourcehealth/doc.go
  azure/services/resourcehealth/mock_resourcehealth/resourcehealth_mock.go
  azure/services/resourcehealth/resourcehealth.go
  azure/services/resourcehealth/resourcehealth_test.go
  config/manager/manager.yaml
  docs/book/src/topics/managedcluster.md
  exp/controllers/azuremanagedcontrolplane_reconciler.go
  feature/feature.go
  hack/observability/opentelemetry/controller-manager-patch.yaml
  test/e2e/config/azure-dev.yaml
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, ok-to-test, lgtm, area/managedclusters

#2942 Bump GINKGO_VER to 2.5.1 to silence warnings
  Makefile
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2949 Discrete timeout for service deletes in E2E
  test/e2e/azure_lb.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2954 Fix CVEs on release branch release-1.6
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#2953 fix CVEs on release-1.5 branch
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#2957 bump aad-pod-identity image to v1.8.14 on branch release-1.5
  config/default/aad-pod-identity-deployment.yaml
Labels: cncf-cla: yes, size/XS, release-note, approved, lgtm

#2956 bump aad-pod-identity image to v1.8.14 on branch release-1.6
  config/default/aad-pod-identity-deployment.yaml
Labels: cncf-cla: yes, size/XS, release-note, approved, lgtm

#2602 Add proposal for AzureManagedCluster graduation from experimental
  docs/proposals/20220825-azuremanaged-cluster-exp-graduation.md
Labels: cncf-cla: yes, size/L, release-note-none, approved, kind/documentation, lgtm, area/managedclusters

#2941 Update conformance test for Ginkgo v2
  test/e2e/conformance_test.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#2823 Add environment variables to run e2e test with an existing image
  Makefile
  docs/book/src/developers/development.md
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  test/e2e/azure_test.go
  test/e2e/capi_test.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2915 Make e2e Helm install idempotent
  test/e2e/cloud-provider-azure.go
  test/e2e/common.go
  test/e2e/csi_migration_test.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, kind/failing-test

#2961 Bug_fix: validate non-nil AzureMachine.Spec.Diagnostic when upgrading to v1beta1
  api/v1beta1/azuremachine_webhook.go
  api/v1beta1/azuremachine_webhook_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2711 AzureManagedCluster spec.controlPlaneEndpoint is immutable
  azure/scope/managedcontrolplane.go
  exp/api/v1beta1/azuremanagedcluster_webhook.go
  exp/api/v1beta1/azuremanagedcluster_webhook_test.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  exp/controllers/azuremanagedcluster_controller.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm, area/managedclusters

#2960 add AGE column to custom printcolumn
  api/v1beta1/azurecluster_types.go
  api/v1beta1/azureclusteridentity_types.go
  api/v1beta1/azuremachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepoolmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  exp/api/v1beta1/azuremachinepool_types.go
  exp/api/v1beta1/azuremachinepoolmachine_types.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#2940 bump capi to v1.3.1
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#2966 Remove listen-client-urls hack from dual-stack templates
  docs/book/src/topics/ipv6.md
  templates/cluster-template-dual-stack.yaml
  templates/flavors/dual-stack/patches/kubeadm-controlplane.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test
