Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2022-09, with the labels that each got.

#2497 test: simplify capz provider metadata.yaml
  docs/book/src/developers/releasing.md
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, kind/documentation, lgtm

#2589 add lint config for `//go:build e2e` files
  .golangci.yml
  test/e2e/aks.go
  test/e2e/azure_clusterproxy.go
  test/e2e/azure_lb.go
  test/e2e/azure_logcollector.go
  test/e2e/azure_machinepool_drain.go
  test/e2e/azure_net_pol.go
  test/e2e/azure_privatecluster.go
  test/e2e/azure_selfhosted.go
  test/e2e/azure_test.go
  test/e2e/common.go
  test/e2e/csi_migration_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/helpers.go
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/networkpolicy/networkpolicy.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/log.go
  test/e2e/retry.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, ok-to-test, lgtm

#2612 Revert "Remove kcp adoption test"
  Makefile
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step1/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step2/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step2/kustomization.yaml
Labels: cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#2615 set AzureManagedMachinePool not ready for in-progress reconciliations
  exp/controllers/azuremanagedmachinepool_controller.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#2613 Temporarily remove cordon and drain test
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, ok-to-test, lgtm, kind/failing-test

#2623 Restore "latest" for Ubuntu images in test templates
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/prow-ci-version/patches/machine-deployment-ci-version.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2609 Update Kubescape to v2.0.167
  test/e2e/config/azure-dev.yaml
  test/e2e/kubescape.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#2620 E2E test error when collecting logs after deleting
  test/e2e/azure_privatecluster.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm, kind/failing-test

#2632 add back 0.5 metadata contract for v1alpha4
  docs/book/src/developers/releasing.md
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2630 Revert "use known-working Windows OS image"
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/prow-ci-version-windows-containerd-2022/patches/windows-image-update.yaml
  templates/test/ci/prow-ci-version/patches/machine-deployment-ci-version-windows.yaml
  templates/test/ci/prow-ci-version/patches/machine-deployment-ci-version.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version-windows.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/patches/machine-deployment-pr-version-windows.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#2637 add enableNodePublicIP to managed machine pools
  azure/converters/managedagentpool.go
  azure/scope/managedmachinepool.go
  azure/services/agentpools/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  exp/api/v1alpha3/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremanagedmachinepool_types.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  templates/cluster-template-aks.yaml
  templates/flavors/aks/cluster-template.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#2628 Document the CAPZ release cadence and support policy
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/M, release-note, approved, kind/documentation, lgtm

#2641 AzureMachineTemplate webhooks dry-run
  api/v1beta1/azuremachinetemplate_webhook.go
  api/v1beta1/azuremachinetemplate_webhook_test.go
Labels: cncf-cla: yes, size/M, kind/api-change, release-note, approved, lgtm

#2642 update metadata.yaml in preparation for v1.5.0 release
  metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2643 update CI apiversion contract for 1.6 release cycle
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2650 Upgrade azure sdk for go network package to 2021-08-01
  azure/converters/loadbalancers.go
  azure/converters/loadbalancers_test.go
  azure/converters/publicips.go
  azure/converters/publicips_test.go
  azure/converters/rules.go
  azure/converters/subnets.go
  azure/converters/subnets_test.go
  azure/services/bastionhosts/client.go
  azure/services/bastionhosts/spec.go
  azure/services/inboundnatrules/client.go
  azure/services/inboundnatrules/inboundnatrules_test.go
  azure/services/inboundnatrules/mock_inboundnatrules/client_mock.go
  azure/services/inboundnatrules/spec.go
  azure/services/loadbalancers/client.go
  azure/services/loadbalancers/spec.go
  azure/services/loadbalancers/spec_test.go
  azure/services/natgateways/client.go
  azure/services/natgateways/natgateways.go
  azure/services/natgateways/natgateways_test.go
  azure/services/natgateways/spec.go
  azure/services/networkinterfaces/client.go
  azure/services/networkinterfaces/spec.go
  azure/services/networkinterfaces/spec_test.go
  azure/services/publicips/client.go
  azure/services/publicips/publicips.go
  azure/services/publicips/publicips_test.go
  azure/services/publicips/spec.go
  azure/services/publicips/spec_test.go
  azure/services/routetables/client.go
  azure/services/routetables/spec.go
  azure/services/securitygroups/client.go
  azure/services/securitygroups/securitygroups_test.go
  azure/services/securitygroups/spec.go
  azure/services/securitygroups/spec_test.go
  azure/services/subnets/client.go
  azure/services/subnets/spec.go
  azure/services/subnets/spec_test.go
  azure/services/subnets/subnets.go
  azure/services/subnets/subnets_test.go
  azure/services/virtualmachines/spec_test.go
  azure/services/virtualmachines/virtualmachines.go
  azure/services/virtualmachines/virtualmachines_test.go
  azure/services/virtualnetworks/client.go
  azure/services/virtualnetworks/spec.go
  azure/services/virtualnetworks/virtualnetworks.go
  azure/services/virtualnetworks/virtualnetworks_test.go
  azure/services/vnetpeerings/client.go
  azure/services/vnetpeerings/spec.go
  test/e2e/azure_privatecluster.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, ok-to-test, lgtm

#2644 add toleration for control plane taints
  config/manager/manager.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, release-note, approved, lgtm

#2649 Use webhook default name for node outbound lb
  azure/scope/cluster.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#2666 read tilt-settings.yaml
  .gitignore
  Tiltfile
  docs/book/src/developers/development.md
  hack/observability/opentelemetry/readme.md
  hack/observability/readme.md
  templates/flavors/README.md
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, ok-to-test, lgtm

#2662 Show granular conditions during AzureCluster delete
  controllers/azurecluster_controller.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note, approved, lgtm

#2661 Add finalizer to AzureClusterIdentity
  controllers/azurecluster_controller.go
  controllers/helpers.go
  exp/api/v1beta1/azuremanagedcontrolplane_types.go
  exp/controllers/azuremanagedcontrolplane_controller.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#2663 support ccm to read config from secret
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, ok-to-test, lgtm

#2680 docs: add more detail about reviewing image promotion PR
  docs/book/src/developers/development.md
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#2631 Add support for custom vm extensions
  api/v1alpha3/azuremachine_conversion.go
  api/v1alpha3/azuremachinetemplate_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/azuremachine_conversion.go
  api/v1alpha4/azuremachinetemplate_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/azuremachine_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesets/vmssextension_spec.go
  azure/services/scalesets/vmssextension_spec_test.go
  azure/services/vmextensions/spec.go
  azure/services/vmextensions/spec_test.go
  azure/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  docs/book/src/SUMMARY.md
  docs/book/src/topics/custom-vm-extensions.md
  exp/api/v1alpha3/azuremachinepool_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremachinepool_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremachinepool_types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/azuremachinepool-vmextension.yaml
  templates/test/ci/patches/azuremachinetemplate-vmextension.yaml
  templates/test/ci/prow-machine-pool/kustomization.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/azure_test.go
  test/e2e/azure_vmextensions.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, ok-to-test, lgtm

#2672 Fix AzureMachineTemplate roleAssignmentName validation
  api/v1beta1/azuremachine_validation.go
  api/v1beta1/azuremachine_webhook.go
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/azuremachinetemplate_webhook_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm
