Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2022-04, with the labels that each got.

#2211 fix: Broken Refs
  api/v1beta1/azureclustertemplate_webhook.go
  api/v1beta1/azuremachinetemplate_webhook.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, ok-to-test, lgtm

#2007 Make private dns reconcile/delete async
  api/v1beta1/conditions_consts.go
  azure/scope/cluster.go
  azure/services/privatedns/client.go
  azure/services/privatedns/link_client.go
  azure/services/privatedns/link_reconciler.go
  azure/services/privatedns/link_spec.go
  azure/services/privatedns/link_spec_test.go
  azure/services/privatedns/mock_privatedns/client_mock.go
  azure/services/privatedns/mock_privatedns/doc.go
  azure/services/privatedns/mock_privatedns/privatedns_mock.go
  azure/services/privatedns/privatedns.go
  azure/services/privatedns/privatedns_test.go
  azure/services/privatedns/record_client.go
  azure/services/privatedns/record_reconciler.go
  azure/services/privatedns/record_spec.go
  azure/services/privatedns/record_spec_test.go
  azure/services/privatedns/zone_client.go
  azure/services/privatedns/zone_reconciler.go
  azure/services/privatedns/zone_spec.go
  azure/services/privatedns/zone_spec_test.go
  azure/types.go
Labels: kind/bug, cncf-cla: yes, kind/cleanup, area/provider/azure, release-note, approved, size/XXL, lgtm, sig/cluster-lifecycle

#2213 Skip Existing Secret During Identity Creation
  hack/create-identity-secret.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, ok-to-test, lgtm

#2216 Temporary disable test for Windows kubernetes CI
  test/e2e/data/kubetest/upstream-windows.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test, sig/windows

#2217 Add mboersma to maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#2219 Minor edits to "SSH access to nodes" doc
  docs/book/src/topics/ssh-access.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, kind/documentation, lgtm

#2220 test v1.22.7 until v1.22.8 image issues are addressed
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2224 Use latest stable
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2194 ci: Ci entrypoint windows 2022 support
  azure/defaults.go
  azure/defaults_test.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  templates/cluster-template-windows-containerd.yaml
  templates/flavors/windows-containerd/machine-deployment-windows.yaml
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/windows-server-version.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2227 fix: Add scope during service principal creation
  docs/book/src/topics/getting-started.md
  docs/book/src/topics/managedcluster.md
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#2222 wait longer for private cluster to account for add’l bastion create time
  test/e2e/azure_privatecluster.go
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2206 Apidiff test runs only if the changes are in api/ and exp/api/
  Makefile
  scripts/ci-apidiff.sh
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#2232 Revert "Apidiff test runs only if the changes are in api/ and exp/api/"
  Makefile
  scripts/ci-apidiff.sh
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#2209 e2e: use helm to install out-of-tree cloud-provider-azure
  .gitignore
  Makefile
  Tiltfile
  docs/book/src/developers/kubernetes-developers.md
  docs/book/src/topics/cloud-provider-config.md
  go.mod
  go.sum
  hack/create-dev-cluster.sh
  scripts/ci-build-azure-ccm.sh
  scripts/ci-entrypoint.sh
  templates/cluster-template-external-cloud-provider.yaml
  templates/flavors/external-cloud-provider/ccm-resource-set.yaml
  templates/flavors/external-cloud-provider/cloud-controller-manager.yaml
  templates/flavors/external-cloud-provider/cloud-node-manager.yaml
  templates/flavors/external-cloud-provider/kustomization.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider.yaml
  test/e2e/azure_test.go
  test/e2e/cloud-provider-azure.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#2240 Fix race condition when creating resource group with custom user tags
  azure/services/groups/spec.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#2238 Delete long running operation state when resource is not found
  azure/services/async/async.go
  azure/services/async/async_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#2247 [release-1.2] Fetch calico manifests from release artifacts
  .gitignore
  Makefile
  templates/addons/calico-ipv6/calico-policy-only.yaml
  templates/addons/calico-ipv6/kustomization.yaml
  templates/addons/calico/calico-vxlan.yaml
  templates/addons/calico/kustomization.yaml
Labels: cncf-cla: yes, area/provider/azure, release-note-none, approved, size/XXL, lgtm, sig/cluster-lifecycle

#2239 test: timeout log collection operations
  test/e2e/azure_logcollector.go
  test/e2e/retry.go
Labels: cncf-cla: yes, kind/flake, size/M, release-note-none, approved, lgtm

#2177 Make VM extension reconcile async and move VMSS extension into scaleset service
  api/v1beta1/conditions_consts.go
  azure/scope/cluster_test.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/services/scalesets/mock_scalesets/scalesets_mock.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesets/vmssextension_spec.go
  azure/services/vmextensions/client.go
  azure/services/vmextensions/mock_vmextensions/client_mock.go
  azure/services/vmextensions/mock_vmextensions/doc.go
  azure/services/vmextensions/mock_vmextensions/vmextensions_mock.go
  azure/services/vmextensions/spec.go
  azure/services/vmextensions/vmextensions.go
  azure/services/vmextensions/vmextensions_test.go
  azure/services/vmssextensions/client.go
  azure/services/vmssextensions/mock_vmssextensions/client_mock.go
  azure/services/vmssextensions/mock_vmssextensions/doc.go
  azure/services/vmssextensions/mock_vmssextensions/vmssextensions_mock.go
  azure/services/vmssextensions/vmssextensions.go
  azure/services/vmssextensions/vmssextensions_test.go
  azure/types.go
  exp/controllers/azuremachinepool_reconciler.go
Labels: kind/feature, cncf-cla: yes, area/provider/azure, release-note, approved, size/XXL, lgtm, sig/cluster-lifecycle

#2254 [release-1.2] test: don’t panic during log collection
  test/e2e/azure_logcollector.go
Labels: cncf-cla: yes, size/S, kind/flake, area/provider/azure, release-note-none, approved, lgtm, sig/cluster-lifecycle

#2259 Fix Azure docs dead link
  docs/book/src/topics/vm-identity.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm, kind/failing-test

#2253 ci: enabling containerd log collection on windows for more cluster templates
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/windows-enable-containerd-logger.yaml
  templates/test/ci/prow-ci-version/kustomization.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/kustomization.yaml
Labels: cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#2268 Fix case of userAssignedIdentityID in JSON serialization
  controllers/helpers.go
  controllers/helpers_test.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#2260 fix: Updating azure_logcollector.go to reflect containerd runtime on Windows
  test/e2e/azure_logcollector.go
Labels: kind/bug, cncf-cla: yes, size/XS, tide/merge-method-squash, kind/cleanup, release-note-none, approved, lgtm

#2262 Add Jont828 to reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm
