Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2022-11, with the labels that each got.

#2751 fix scaling managed machine pool to zero
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm, area/managedclusters

#2768 Disable Kubescape security scanner in e2e tests
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#2772 test: set private cluster E2E test to optional
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2755 Handle different base64 tools in Tiltfile
  Tiltfile
Labels: kind/bug, cncf-cla: yes, size/XS, tide/merge-method-squash, release-note-none, approved, lgtm

#2764 add AKS nodepool autoscale test
  test/e2e/aks.go
  test/e2e/azure_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2731 Remove kcp adoption test
  Makefile
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1beta1/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step1/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step2/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step2/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-upgrades.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
Labels: cncf-cla: yes, size/XL, tide/merge-method-squash, release-note-none, approved, lgtm

#2771 Revert "fix error pulling cloud provider images in e2e"
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2749 Introduce additional linters & bump golangci-lint to 1.50.0
  .codespellignore
  .golangci.yml
  Makefile
  azure/converters/futures_test.go
  azure/defaults_test.go
  azure/services/agentpools/agentpools_test.go
  azure/services/async/async_test.go
  azure/services/availabilitysets/availabilitysets_test.go
  azure/services/bastionhosts/bastionhosts_test.go
  azure/services/disks/disks_test.go
  azure/services/groups/groups_test.go
  azure/services/inboundnatrules/inboundnatrules_test.go
  azure/services/loadbalancers/loadbalancers_test.go
  azure/services/natgateways/natgateways_test.go
  azure/services/networkinterfaces/networkinterfaces_test.go
  azure/services/publicips/publicips_test.go
  azure/services/roleassignments/roleassignments_test.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesetvms/scalesetvms_test.go
  azure/services/subnets/subnets_test.go
  azure/services/tags/tags_test.go
  azure/services/virtualmachines/virtualmachines_test.go
  azure/services/virtualnetworks/virtualnetworks_test.go
  azure/services/vmextensions/vmextensions_test.go
  azure/services/vnetpeerings/vnetpeerings_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#2741 common funcs webhook immutable properties
  .golangci.yml
  api/v1beta1/azurecluster_webhook.go
  api/v1beta1/azuremachine_webhook.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook_test.go
  main.go
  util/webhook/validator.go
  util/webhook/validator_test.go
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note-none, approved, lgtm

#2757 chore: increase the ccm log verbosity in e2e test
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#2775 🌱 Uplift go version to v1.19.0
  .github/workflows/cover.yaml
  .github/workflows/release.yaml
  .golangci.yml
  Dockerfile
  Makefile
  Tiltfile
  docs/book/src/developers/development.md
  go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#2721 Use GetAtScope() to get tags when checking if a resource is managed
  azure/defaults.go
  azure/services/async/interfaces.go
  azure/services/async/mock_async/async_mock.go
  azure/services/privatedns/privatedns.go
  azure/services/privatedns/privatedns_test.go
  azure/services/publicips/publicips.go
  azure/services/publicips/publicips_test.go
  azure/services/tags/client.go
  azure/services/tags/tags.go
  azure/services/virtualnetworks/virtualnetworks.go
  azure/services/virtualnetworks/virtualnetworks_test.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, lgtm

#2791 Silence kubectl deprecation warning
  scripts/ci-configmap.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2747 fix: format azure compute gallery image ID
  azure/converters/image.go
  azure/converters/image_test.go
Labels: kind/bug, cncf-cla: yes, tide/merge-method-squash, size/M, release-note, approved, ok-to-test, lgtm

#2777 add “[Managed Kubernetes]” E2E test type
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lifecycle/active, lgtm

#2783 Fixes Issue 2779: Fix in multitenancy docs
  docs/book/src/topics/multitenancy.md
Labels: cncf-cla: yes, size/XS, release-note, approved, kind/documentation, ok-to-test, lgtm

#2788 Fixes docs bug in api server endpoint
  docs/book/src/topics/api-server-endpoint.md
Labels: cncf-cla: yes, size/XS, release-note, approved, kind/documentation, ok-to-test, lgtm

#2797 [release-1.5] update codespell definitions and fix go 1.19 lint
  .codespellignore
  azure/mock_azure/doc.go
  azure/scope/mocks/doc.go
  azure/services/async/mock_async/doc.go
  azure/services/availabilitysets/mock_availabilitysets/doc.go
  azure/services/bastionhosts/mocks_bastionhosts/doc.go
  azure/services/disks/mock_disks/doc.go
  azure/services/groups/mock_groups/doc.go
  azure/services/inboundnatrules/mock_inboundnatrules/doc.go
  azure/services/loadbalancers/mock_loadbalancers/doc.go
  azure/services/managedclusters/mock_managedclusters/doc.go
  azure/services/natgateways/mock_natgateways/doc.go
  azure/services/networkinterfaces/mock_networkinterfaces/doc.go
  azure/services/privatedns/mock_privatedns/doc.go
  azure/services/publicips/mock_publicips/doc.go
  azure/services/resourceskus/mock_resourceskus/doc.go
  azure/services/roleassignments/mock_roleassignments/doc.go
  azure/services/routetables/mock_routetables/doc.go
  azure/services/scalesets/client.go
  azure/services/scalesets/mock_scalesets/doc.go
  azure/services/scalesetvms/client.go
  azure/services/scalesetvms/mock_scalesetvms/doc.go
  azure/services/securitygroups/mock_securitygroups/doc.go
  azure/services/subnets/mock_subnets/doc.go
  azure/services/tags/mock_tags/doc.go
  azure/services/virtualmachineimages/mock_virtualmachineimages/doc.go
  azure/services/virtualmachines/mock_virtualmachines/doc.go
  azure/services/virtualnetworks/mock_virtualnetworks/doc.go
  azure/services/vmextensions/mock_vmextensions/doc.go
  azure/services/vnetpeerings/mock_vnetpeerings/doc.go
  exp/controllers/mocks/doc.go
  internal/test/mock_log/doc.go
  internal/test/record/logger.go
  pkg/coalescing/mocks/doc.go
  util/tele/corr_id.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#2776 docs: fix AzureManagedCluster example
  .gitignore
  docs/book/src/topics/managedcluster.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, lifecycle/active, kind/documentation, lgtm

#2789 Make base64 usage more portable in e2e setup
  hack/util.sh
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lifecycle/active, lgtm

#2808 update metadata.yaml for 1.6 release and 1.7 dev cycle
  metadata.yaml
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2795 ensure AKS immutable configuration has webhook enforcement
  exp/api/v1beta1/azuremanagedcontrolplane_webhook.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook.go
  util/webhook/validator.go
  util/webhook/validator_test.go
Labels: kind/bug, cncf-cla: yes, kind/cleanup, size/L, release-note, approved, lgtm

#2765 add managed machine pool scale tests
  test/e2e/aks.go
  test/e2e/azure_test.go
Labels: cncf-cla: yes, tide/merge-method-squash, kind/cleanup, size/L, release-note-none, approved, lgtm

#2767 Cleanup remote peerings when resource group is deleted
  azure/services/vnetpeerings/vnetpeerings.go
  azure/services/vnetpeerings/vnetpeerings_test.go
  controllers/azurecluster_reconciler.go
  controllers/azurecluster_reconciler_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lifecycle/active, ok-to-test, lgtm

#2819 omit benign errors in e2e logs
  test/e2e/aks.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2822 test managed machine pool delete in e2e
  test/e2e/aks.go
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#2824 ci: always use registry.k8s.io
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/patches/control-plane-kubeadm-boostrap-ci-version.yaml
  templates/test/ci/prow-ci-version/patches/kubeadm-bootstrap.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/patches/kubeadm-controlplane-bootstrap.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#2825 [release-1.5] Cleanup remote peerings when resource group is deleted
  azure/services/vnetpeerings/vnetpeerings.go
  azure/services/vnetpeerings/vnetpeerings_test.go
  controllers/azurecluster_reconciler.go
  controllers/azurecluster_reconciler_test.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm

#2743 Add AzureMachine condition when userAssignedIdentity is missing from the VM
  api/v1beta1/conditions_consts.go
  azure/converters/vm.go
  azure/scope/machine.go
  azure/services/identities/client.go
  azure/services/identities/mock_identities/client_mock.go
  azure/services/identities/mock_identities/doc.go
  azure/services/virtualmachines/mock_virtualmachines/virtualmachines_mock.go
  azure/services/virtualmachines/virtualmachines.go
  azure/services/virtualmachines/virtualmachines_test.go
  controllers/azuremachine_controller.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lifecycle/active, ok-to-test, lgtm

#2830 update readme links
  README.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#2804 add markdown linter changes
  docs/book/src/topics/failure-domains.md
  docs/book/src/topics/managedcluster.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, kind/documentation, lgtm

#2833 ci: fix custom build script
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/patches/kubeadm-controlplane-bootstrap.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#2841 k8s build: overwrite storage blob if exists
  scripts/ci-build-kubernetes.sh
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2835 Fix image architecture bug in Docker build
  Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#2845 ci-build-kubernetes fixes
  scripts/ci-build-kubernetes.sh
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#2849 print k8s build env vars during CI
  scripts/ci-build-kubernetes.sh
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2802 tags converters: return nil if src is nil
  azure/converters/tags.go
  azure/converters/tags_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#2745 Add AdditionalTags property to CRD AzureManagedMachinePool
  azure/converters/managedagentpool.go
  azure/converters/managedagentpool_test.go
  azure/scope/managedmachinepool.go
  azure/scope/managedmachinepool_test.go
  azure/services/agentpools/spec.go
  azure/services/managedclusters/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  exp/api/v1alpha3/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremanagedmachinepool_types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, cncf-cla: yes, size/L, kind/api-change, release-note, approved, ok-to-test, lgtm, area/managedclusters

#2816 add control plane tolerations to aad pod identity
  config/default/aad-pod-identity-deployment.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#2844 Bump CAPI to v1.2.6
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, lgtm

#2837 [cloud-provider-azure] Support specifying CCM cluster CIDR
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note, approved, lgtm

#2853 ci: print git info when building from k8s source
  scripts/ci-build-kubernetes.sh
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2875 Fix ci entrypoint rebase
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2714 Allow to set custom backend pool names for load balancers
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/azurecluster_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azurecluster_default_test.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#2879 fix bad generated template name on Mac
  hack/common-vars.sh
  hack/gen-flavors.sh
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#2883 lint: add correct link for upgrading clusters doc
  docs/book/src/topics/custom-images.md
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm
