Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2022-05, with the labels that each got.

#2273 docs/book/src/developers: fix typo GINKO_FOCUS -> GINKGO_FOCUS
  docs/book/src/developers/development.md
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#2276 update nvidia gpu operator to 1.10.1
  hack/fetch-nvidia-resources.sh
  templates/cluster-template-nvidia-gpu.yaml
  templates/flavors/nvidia-gpu/clusterpolicy-crd.yaml
  templates/flavors/nvidia-gpu/gpu-operator-components.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
Labels: cncf-cla: yes, release-note-none, approved, size/XXL, lgtm, kind/failing-test

#2274 azure: fix bootstrap extension command error path for bash
  azure/defaults.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#2281 Handle compression at docs.github.com when checking markdown links
  .markdownlinkcheck.json
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#2282 Fix a copied code comment
  test/e2e/azure_net_pol.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#2284 Update metadata.yaml to include v1.3 release
  docs/book/src/developers/releasing.md
  metadata.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#2278 Fix automatically found typos and remove some spotted trailing whitespace
  CONTRIBUTING.md
  api/v1alpha4/conditions_consts.go
  api/v1beta1/azurecluster_validation_test.go
  api/v1beta1/conditions_consts.go
  azure/scope/cluster_test.go
  azure/scope/identity.go
  azure/scope/machinepoolmachine.go
  azure/scope/machinepoolmachine_test.go
  azure/services/bastionhosts/azurebastion_spec.go
  azure/services/natgateways/natgateways.go
  azure/services/scalesetvms/client.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  docs/book/src/developers/development.md
  docs/book/src/developers/kubernetes-developers.md
  docs/book/src/topics/windows.md
  docs/proposals/20201214-bootstrap-failure-detection.md
  docs/proposals/20210716-async-azure-resource-creation-deletion.md
  exp/api/v1alpha3/azuremanagedcontrolplane_types.go
  exp/api/v1alpha4/azuremanagedcontrolplane_types.go
  exp/api/v1beta1/azuremanagedcontrolplane_types.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  hack/observability/prometheus/resources/bundle.yaml
  hack/util.sh
  scripts/ci-build-kubernetes.sh
  templates/flavors/aks/cluster-template.yaml
  templates/test/ci/cluster-template-prow-identity-from-env.yaml
  templates/test/dev/cluster-template-custom-builds-windows.yaml
  templates/test/dev/custom-builds-windows/patches/custom-builds-windows.yaml
  test/e2e/aks.go
  test/e2e/azure_selfhosted.go
  test/e2e/data/infrastructure-azure/v1alpha4/cluster-template-prow.yaml
  test/e2e/kubernetes/node/node.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2270 Add MHC as mitigation against cloudbase init bug on Windows prow jobs
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/mhc-windows.yaml
  templates/test/ci/prow-ci-version-windows-containerd-2022/kustomization.yaml
  templates/test/ci/prow-ci-version-windows-containerd-2022/patches/drop-mhc.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/ci/prow/mhc-windows.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/config/azure-dev.yaml
Labels: kind/bug, cncf-cla: yes, kind/flake, size/L, release-note-none, approved, lgtm

#2288 Update to compute API 2021-11-01
  api/v1beta1/azureimage_validation.go
  api/v1beta1/azuremachine_validation.go
  api/v1beta1/azuremachine_validation_test.go
  api/v1beta1/azuremachinetemplate_webhook_test.go
  azure/converters/identity.go
  azure/converters/identity_test.go
  azure/converters/image.go
  azure/converters/image_test.go
  azure/converters/spotinstances.go
  azure/converters/vm.go
  azure/converters/vmss.go
  azure/converters/vmss_test.go
  azure/scope/machine.go
  azure/services/availabilitysets/availabilitysets.go
  azure/services/availabilitysets/availabilitysets_test.go
  azure/services/availabilitysets/client.go
  azure/services/availabilitysets/spec.go
  azure/services/availabilitysets/spec_test.go
  azure/services/disks/client.go
  azure/services/networkinterfaces/spec_test.go
  azure/services/resourceskus/cache.go
  azure/services/resourceskus/cache_test.go
  azure/services/resourceskus/client.go
  azure/services/resourceskus/mock_resourceskus/resourceskus_mock.go
  azure/services/resourceskus/sku.go
  azure/services/roleassignments/roleassignments.go
  azure/services/roleassignments/roleassignments_test.go
  azure/services/scalesets/client.go
  azure/services/scalesets/mock_scalesets/client_mock.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesets/vmssextension_spec.go
  azure/services/scalesetvms/client.go
  azure/services/scalesetvms/mock_scalesetvms/client_mock.go
  azure/services/scalesetvms/scalesetvms_test.go
  azure/services/virtualmachines/client.go
  azure/services/virtualmachines/spec.go
  azure/services/virtualmachines/spec_test.go
  azure/services/virtualmachines/virtualmachines.go
  azure/services/virtualmachines/virtualmachines_test.go
  azure/services/vmextensions/client.go
  azure/services/vmextensions/spec.go
  controllers/azurecluster_reconciler_test.go
  controllers/azuremachine_reconciler_test.go
  exp/controllers/azuremachinepool_reconciler_test.go
  exp/controllers/azuremanagedmachinepool_reconciler.go
  go.mod
  go.sum
  test/e2e/azure_logcollector.go
  test/e2e/azure_privatecluster.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2223 fix for tags update and delete op
  azure/services/managedclusters/managedclusters.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#2297 Upgrade to calico 3.23.0
  Makefile
  templates/addons/calico-dual-stack.yaml
  templates/addons/calico-ipv6.yaml
  templates/addons/calico-ipv6/calico-policy-only.yaml
  templates/addons/calico.yaml
  templates/addons/calico/calico-vxlan.yaml
  templates/addons/windows/calico/calico.yaml
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
Labels: kind/bug, cncf-cla: yes, kind/cleanup, release-note, approved, size/XXL, lgtm, kind/failing-test

#2214 Use MSI ClientID as userAssignedIdentityID in azure.json
  azure/services/identities/client.go
  controllers/azurejson_machine_controller.go
  controllers/azurejson_machinepool_controller.go
  controllers/azurejson_machinetemplate_controller.go
  go.mod
  go.sum
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider.yaml
  templates/test/ci/prow-dual-stack/kustomization.yaml
  templates/test/ci/prow-dual-stack/patches/azure-machine-template-control-plane.yaml
  templates/test/ci/prow-dual-stack/patches/azure-machine-template.yaml
  templates/test/ci/prow-external-cloud-provider/kustomization.yaml
  templates/test/ci/prow-external-cloud-provider/patches/azure-machine-template-control-plane.yaml
  templates/test/ci/prow-external-cloud-provider/patches/azure-machine-template.yaml
  test/e2e/azure_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#2304 Fix apiserver cloud-provider arg for external cloud-provider template
  templates/cluster-template-external-cloud-provider.yaml
  templates/flavors/external-cloud-provider/patches/external-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#2300 Support using a customized template outside CAPZ repo
  Makefile
  docs/book/src/developers/development.md
  scripts/ci-entrypoint.sh
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, lgtm

#2306 Simplify use of tar in scripts for compatibility
  hack/observability/jaeger/fetch-jaeger-resources.sh
  hack/observability/opentelemetry/fetch-otel-resources.sh
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#2310 [release-1.3] Support using a customized template outside CAPZ repo
  Makefile
  docs/book/src/developers/development.md
  scripts/ci-entrypoint.sh
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, lgtm

#2308 docs: add upstream test maintenance criteria to release doc
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#2292 test: remove legacy Windows dockershim templates
  Makefile
  Tiltfile
  docs/book/src/topics/windows.md
  templates/addons/flannel-resource-set.yaml
  templates/addons/windows/flannel/flannel.yaml
  templates/addons/windows/flannel/kube-proxy-windows.yaml
  templates/cluster-template-machinepool-windows-containerd.yaml
  templates/cluster-template-machinepool-windows.yaml
  templates/cluster-template-windows-containerd.yaml
  templates/cluster-template-windows.yaml
  templates/flavors/base-windows/kustomization.yaml
  templates/flavors/base-windows/patches/cluster.yaml
  templates/flavors/base-windows/patches/kubeadm-control-plane.yaml
  templates/flavors/machinepool-windows-containerd/kustomization.yaml
  templates/flavors/machinepool-windows-containerd/machine-pool-deployment-windows.yaml
  templates/flavors/machinepool-windows/kustomization.yaml
  templates/flavors/machinepool-windows/machine-pool-deployment-windows.yaml
  templates/flavors/machinepool-windows/machine-pool-deployment.yaml
  templates/flavors/windows-containerd/kustomization.yaml
  templates/flavors/windows-containerd/machine-deployment-windows.yaml
  templates/flavors/windows/kustomization.yaml
  templates/flavors/windows/machine-deployment-windows.yaml
  templates/flavors/windows/machine-deployment.yaml
  templates/test/ci/cluster-template-prow-ci-version-windows.yaml
  templates/test/ci/cluster-template-prow-windows-addons.yaml
  templates/test/ci/cluster-template-prow-windows.yaml
  templates/test/ci/patches/cluster-cni-windows.yaml
  templates/test/ci/prow-ci-version-windows/kustomization.yaml
  templates/test/ci/prow-ci-version-windows/patches/machine-deployment-ci-version.yaml
  templates/test/ci/prow-ci-version-windows/patches/windows-image-update.yaml
  templates/test/ci/prow-machine-pool/kustomization.yaml
  templates/test/ci/prow-windows/cni-resource-set-windows.yaml
  templates/test/ci/prow-windows/kustomization.yaml
  templates/test/ci/prow-windows/patches/machine-deployment-worker-counts.yaml
  templates/test/ci/prow-windows/patches/windows-tmp-folder.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds-windows.yaml
  templates/test/dev/custom-builds-windows/kustomization.yaml
  templates/test/dev/custom-builds-windows/patches/custom-builds-windows.yaml
  templates/test/dev/custom-builds-windows/patches/windows-image-update.yaml
  test/e2e/azure_test.go
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, release-note, approved, size/XXL, lgtm

#2313 Reuse logic in ci scripts
  hack/create-dev-cluster.sh
  hack/util.sh
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2312 fix broken link for Windows flavor template
  docs/book/src/topics/windows.md
Labels: kind/bug, cncf-cla: yes, size/XS, tide/merge-method-squash, release-note-none, approved, kind/documentation, ok-to-test, lgtm

#2261 test: fix wait.PollImmediate so it actually retries after errors
  test/e2e/retry.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#2316 ci: support external-cloud-provider plus latest k8s releases
  scripts/ci-entrypoint.sh
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/prow-external-cloud-provider-ci-version/kustomization.yaml
Labels: cncf-cla: yes, release-note-none, approved, size/XXL, lgtm, kind/failing-test

#2324 [release-1.3] ci: support external-cloud-provider plus latest k8s rel…
  scripts/ci-entrypoint.sh
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/prow-external-cloud-provider-ci-version/kustomization.yaml
Labels: cncf-cla: yes, release-note-none, approved, size/XXL, lgtm

#2264 generalize helm install during E2E testing
  test/e2e/cloud-provider-azure.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2311 Check configmap existence before creation
  Makefile
  scripts/ci-configmap.sh
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm
