Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2022-10, with the labels that each got.

#2692 lint: gofmt -s lots of files
  azure/mock_azure/doc.go
  azure/scope/mocks/doc.go
  azure/services/async/mock_async/doc.go
  azure/services/availabilitysets/mock_availabilitysets/doc.go
  azure/services/bastionhosts/mocks_bastionhosts/doc.go
  azure/services/disks/mock_disks/doc.go
  azure/services/groups/mock_groups/doc.go
  azure/services/inboundnatrules/mock_inboundnatrules/doc.go
  azure/services/loadbalancers/mock_loadbalancers/doc.go
  azure/services/managedclusters/mock_managedclusters/doc.go
  azure/services/natgateways/mock_natgateways/doc.go
  azure/services/networkinterfaces/mock_networkinterfaces/doc.go
  azure/services/privatedns/mock_privatedns/doc.go
  azure/services/publicips/mock_publicips/doc.go
  azure/services/resourceskus/mock_resourceskus/doc.go
  azure/services/roleassignments/mock_roleassignments/doc.go
  azure/services/routetables/mock_routetables/doc.go
  azure/services/scalesets/client.go
  azure/services/scalesets/mock_scalesets/doc.go
  azure/services/scalesetvms/client.go
  azure/services/scalesetvms/mock_scalesetvms/doc.go
  azure/services/securitygroups/mock_securitygroups/doc.go
  azure/services/subnets/mock_subnets/doc.go
  azure/services/tags/mock_tags/doc.go
  azure/services/virtualmachineimages/mock_virtualmachineimages/doc.go
  azure/services/virtualmachines/mock_virtualmachines/doc.go
  azure/services/virtualnetworks/mock_virtualnetworks/doc.go
  azure/services/vmextensions/mock_vmextensions/doc.go
  azure/services/vnetpeerings/mock_vnetpeerings/doc.go
  exp/controllers/mocks/doc.go
  internal/test/mock_log/doc.go
  internal/test/record/logger.go
  pkg/coalescing/mocks/doc.go
  util/tele/corr_id.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#2700 fix agent pool created in failed state becoming ready
  exp/controllers/azuremanagedmachinepool_controller.go
Labels: kind/bug, cncf-cla: yes, size/XS, needs-ok-to-test, release-note-none, approved, lgtm, area/managedclusters

#2694 Sort summary topics
  docs/book/src/SUMMARY.md
Labels: kind/feature, cncf-cla: yes, size/XS, tide/merge-method-squash, release-note-none, approved, ok-to-test, lgtm

#2687 Add skipLogCollection input for E2E tests
  Makefile
  docs/book/src/developers/development.md
  test/e2e/azure_test.go
  test/e2e/common.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_suite_vars.go
Labels: kind/feature, cncf-cla: yes, size/S, release-note-none, approved, ok-to-test, lgtm

#2699 Use hash for AzureClusterIdentity finalizer
  controllers/helpers.go
  controllers/helpers_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#2682 enable mutable AKS node taints
  azure/services/agentpools/spec.go
  docs/book/src/topics/managedcluster.md
  exp/api/v1beta1/azuremanagedmachinepool_webhook.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook_test.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, lgtm, area/managedclusters

#2698 Change vm extension test to use resource group name correctly
  test/e2e/azure_vmextensions.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, ok-to-test, lgtm, kind/failing-test

#2688 detect Retry-After during async “does resource exist?” flow
  azure/services/async/async.go
  azure/services/async/async_test.go
  util/reconciler/defaults.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#2604 Implement ScaleSetPriority for AzureManagedMachinePool
  azure/converters/managedagentpool.go
  azure/scope/managedmachinepool.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  exp/api/v1alpha3/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremanagedmachinepool_types.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  templates/cluster-template-aks.yaml
  templates/flavors/aks/cluster-template.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
  util/azure/azure.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm, area/managedclusters

#2716 add GPG_TTY, promoted image wait to release docs
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#2667 AKS virtual network static placement for cross RG
  azure/scope/managedcontrolplane.go
  azure/scope/managedmachinepool.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  docs/book/src/topics/managedcluster.md
  exp/api/v1alpha3/azuremanagedcontrolplane_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremanagedcontrolplane_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremanagedcontrolplane_default.go
  exp/api/v1beta1/azuremanagedcontrolplane_types.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#2717 AKS: clarify that one system pool is required
  exp/api/v1beta1/azuremanagedmachinepool_webhook.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2708 add tags for ssa changes
  Makefile
  api/v1alpha3/azurecluster_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/azurecluster_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azurecluster_default_test.go
  api/v1beta1/azurecluster_validation_test.go
  api/v1beta1/azurecluster_webhook_test.go
  api/v1beta1/azureclustertemplate_validation.go
  api/v1beta1/azureclustertemplate_validation_test.go
  api/v1beta1/types.go
  api/v1beta1/types_class.go
  api/v1beta1/types_template.go
  azure/scope/cluster_test.go
  azure/scope/machine_test.go
  azure/scope/managedcontrolplane.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepoolmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  controllers/azurejson_machine_controller_test.go
  controllers/azurejson_machinepool_controller_test.go
  controllers/helpers_test.go
  templates/test/ci/cluster-template-prow-clusterclass-ci-default.yaml
  templates/test/ci/prow-clusterclass-ci-default/base.yaml
Labels: cncf-cla: yes, size/L, kind/api-change, release-note, approved, lgtm

#2706 Add sonasingh46 to reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#2726 remove as azure cloud provider config is auto-generated
  docs/book/src/topics/custom-vnet.md
Labels: cncf-cla: yes, size/XS, release-note, approved, kind/documentation, ok-to-test, lgtm

#2710 refactor: rename CreateResource to CreateOrUpdateResource
  .codespellignore
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/agentpools_test.go
  azure/services/async/async.go
  azure/services/async/async_test.go
  azure/services/async/interfaces.go
  azure/services/async/mock_async/async_mock.go
  azure/services/availabilitysets/availabilitysets.go
  azure/services/availabilitysets/availabilitysets_test.go
  azure/services/bastionhosts/bastionhosts.go
  azure/services/bastionhosts/bastionhosts_test.go
  azure/services/groups/groups.go
  azure/services/groups/groups_test.go
  azure/services/inboundnatrules/inboundnatrules.go
  azure/services/inboundnatrules/inboundnatrules_test.go
  azure/services/loadbalancers/loadbalancers.go
  azure/services/loadbalancers/loadbalancers_test.go
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/managedclusters_test.go
  azure/services/natgateways/natgateways.go
  azure/services/natgateways/natgateways_test.go
  azure/services/networkinterfaces/networkinterfaces.go
  azure/services/networkinterfaces/networkinterfaces_test.go
  azure/services/privatedns/link_reconciler.go
  azure/services/privatedns/privatedns_test.go
  azure/services/privatedns/record_reconciler.go
  azure/services/privatedns/zone_reconciler.go
  azure/services/publicips/publicips.go
  azure/services/publicips/publicips_test.go
  azure/services/roleassignments/roleassignments.go
  azure/services/roleassignments/roleassignments_test.go
  azure/services/routetables/routetables.go
  azure/services/routetables/routetables_test.go
  azure/services/securitygroups/securitygroups.go
  azure/services/securitygroups/securitygroups_test.go
  azure/services/subnets/subnets.go
  azure/services/subnets/subnets_test.go
  azure/services/virtualmachines/virtualmachines.go
  azure/services/virtualmachines/virtualmachines_test.go
  azure/services/virtualnetworks/virtualnetworks.go
  azure/services/virtualnetworks/virtualnetworks_test.go
  azure/services/vmextensions/vmextensions.go
  azure/services/vmextensions/vmextensions_test.go
  azure/services/vnetpeerings/vnetpeerings.go
  azure/services/vnetpeerings/vnetpeerings_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2664 Add nodePublicIPPrefixID to AzureManagedMachinePool
  azure/converters/managedagentpool.go
  azure/scope/managedmachinepool.go
  azure/services/agentpools/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  docs/book/src/topics/managedcluster.md
  exp/api/v1alpha3/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremanagedmachinepool_types.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  test/e2e/aks.go
  test/e2e/azure_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm, area/managedclusters

#2728 add shouldnot to codespellignore
  .codespellignore
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2732 Fix typo in ReconcileError logs
  controllers/azurecluster_controller.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, ok-to-test, lgtm

#2736 Quiet down VM image log messages
  azure/services/virtualmachineimages/cache.go
  azure/services/virtualmachineimages/images.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2626 standardize AzureManagedCluster webhooks
  exp/api/v1beta1/azuremachinepool_webhook.go
  exp/api/v1beta1/azuremachinepool_webhook_test.go
  exp/api/v1beta1/azuremanagedcluster_webhook.go
  exp/api/v1beta1/azuremanagedcluster_webhook_test.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook_test.go
  main.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, lgtm, area/managedclusters

#2737 test: enable using custom flavor for conformance test
  Makefile
  docs/book/src/developers/development.md
  test/e2e/conformance_test.go
  test/e2e/data/kubetest/conformance-dual-stack-ginkgo-v2.yaml
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2742 bump CAPI to v1.2.4
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, lgtm

#2753 Stop using the beta.kubernetes.io/os
  hack/observability/prometheus/resources/bundle.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2744 Fix UTC meeting time in README
  README.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#2763 fix error pulling cloud provider images in e2e
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test
