Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2022-08, with the labels that each got.

#2527 Clarify where to get help with CAPZ
  README.md
  SUPPORT.md
Labels: cncf-cla: yes, size/M, release-note, approved, kind/documentation, lgtm

#2529 Standardize more package import aliases
  .golangci.yml
  api/v1alpha3/azurecluster_types.go
  api/v1alpha3/azureclusteridentity_types.go
  api/v1alpha3/azuremachine_types.go
  api/v1alpha3/conditions_consts.go
  api/v1alpha4/azurecluster_types.go
  api/v1alpha4/azureclusteridentity_types.go
  api/v1alpha4/azuremachine_types.go
  api/v1alpha4/conditions_consts.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/scope/machinepoolmachine.go
  azure/scope/machinepoolmachine_test.go
  azure/scope/managedcontrolplane_test.go
  azure/scope/managedmachinepool.go
  azure/scope/managedmachinepool_test.go
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/agentpools_test.go
  azure/services/natgateways/natgateways_test.go
  azure/services/scalesetvms/scalesetvms_test.go
  controllers/azureidentity_controller.go
  controllers/azurejson_machine_controller_test.go
  controllers/azurejson_machinepool_controller.go
  controllers/azurejson_machinepool_controller_test.go
  controllers/helpers.go
  exp/api/v1alpha3/azuremachinepool_types.go
  exp/api/v1alpha3/azuremanagedcluster_types.go
  exp/api/v1alpha3/azuremanagedcontrolplane_types.go
  exp/api/v1alpha4/azuremachinepool_types.go
  exp/api/v1alpha4/azuremachinepoolmachine_types.go
  exp/api/v1alpha4/azuremanagedcluster_types.go
  exp/api/v1alpha4/azuremanagedcontrolplane_types.go
  exp/api/v1beta1/azuremachinepool_test.go
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/azuremachinepool_controller_unit_test.go
  exp/controllers/azuremachinepool_reconciler_test.go
  exp/controllers/azuremachinepoolmachine_controller_test.go
  exp/controllers/azuremanagedcontrolplane_controller.go
  exp/controllers/azuremanagedmachinepool_controller.go
  exp/controllers/helpers.go
  exp/controllers/helpers_test.go
  internal/test/env/env.go
  main.go
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note-none, approved, lgtm

#2531 Update deprecated annotation to `kubectl.kubernetes.io/default-container`
  config/manager/manager.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#2431 Update CAPI to v1.2.0
  Makefile
  Tiltfile
  azure/scope/cluster_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
  controllers/azurecluster_controller.go
  controllers/azureidentity_controller.go
  controllers/helpers_test.go
  exp/controllers/azuremanagedcluster_controller.go
  exp/controllers/azuremanagedcontrolplane_controller.go
  exp/controllers/azuremanagedmachinepool_controller.go
  go.mod
  go.sum
  templates/cluster-template-nvidia-gpu.yaml
  templates/flavors/nvidia-gpu/gpu-operator-components.yaml
  templates/test/ci/cluster-template-prow-identity-from-env.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  test/e2e/azure_failuredomains.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: cncf-cla: yes, release-note-none, approved, size/XXL, lgtm

#2536 enforce lowercase providerID RG to match cloud-provider-azure
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
  azure/services/virtualmachines/virtualmachines.go
  azure/services/virtualmachines/virtualmachines_test.go
  exp/controllers/azuremanagedmachinepool_reconciler.go
  util/azure/azure.go
  util/azure/azure_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#2535 Update Cluster API Visualizer chart to v1.0.0
  hack/observability/cluster-api-visualizer/chart/Chart.yaml
  hack/observability/cluster-api-visualizer/chart/templates/clusterrole.yaml
  hack/observability/cluster-api-visualizer/chart/templates/clusterrolebinding.yaml
  hack/observability/cluster-api-visualizer/chart/templates/deployment.yaml
  hack/observability/cluster-api-visualizer/chart/templates/secret.yaml
  hack/observability/cluster-api-visualizer/chart/templates/serveaccount.yaml
  hack/observability/cluster-api-visualizer/chart/templates/service.yaml
  hack/observability/cluster-api-visualizer/chart/values.yaml
  hack/observability/cluster-api-visualizer/fetch-visualizer-resources.sh
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2546 clean up hack/tools go.mod
  hack/tools/go.mod
  hack/tools/go.sum
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2547 Update and verify go modules in hack/tools
  Makefile
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2532 Watch Cluster for changes in AzureJSONMachineTemplate, AzureJSONMachine, and AzureJSONMachinePool controllers
  controllers/azurejson_machine_controller.go
  controllers/azurejson_machinepool_controller.go
  controllers/azurejson_machinetemplate_controller.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2556 Update support link
  docs/book/src/developers/releasing.md
  docs/book/src/topics/getting-started.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test, release-note-none, approved, kind/documentation, lgtm

#2560 Fix hack/tools imports so "make modules" works
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2563 fix typo for clusterctl generate cluster command
  templates/flavors/README.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, ok-to-test, lgtm

#2534 Enable linting on conversion and mock code
  .golangci.yml
  api/v1alpha3/azurecluster_conversion.go
  api/v1alpha3/azureclusteridentity_conversion.go
  api/v1alpha3/azuremachine_conversion.go
  api/v1alpha3/azuremachinetemplate_conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha4/azurecluster_conversion.go
  api/v1alpha4/azureclusteridentity_conversion.go
  api/v1alpha4/azuremachine_conversion.go
  api/v1alpha4/azuremachinetemplate_conversion.go
  api/v1alpha4/conversion_test.go
  azure/mock_azure/doc.go
  azure/scope/mocks/doc.go
  azure/services/agentpools/mock_agentpools/doc.go
  azure/services/async/mock_async/doc.go
  azure/services/availabilitysets/mock_availabilitysets/doc.go
  azure/services/bastionhosts/mocks_bastionhosts/doc.go
  azure/services/disks/mock_disks/doc.go
  azure/services/groups/mock_groups/doc.go
  azure/services/inboundnatrules/mock_inboundnatrules/doc.go
  azure/services/loadbalancers/mock_loadbalancers/doc.go
  azure/services/managedclusters/mock_managedclusters/doc.go
  azure/services/natgateways/mock_natgateways/doc.go
  azure/services/networkinterfaces/mock_networkinterfaces/doc.go
  azure/services/privatedns/mock_privatedns/doc.go
  azure/services/publicips/mock_publicips/doc.go
  azure/services/resourceskus/mock_resourceskus/doc.go
  azure/services/roleassignments/mock_roleassignments/doc.go
  azure/services/routetables/mock_routetables/doc.go
  azure/services/scalesets/mock_scalesets/doc.go
  azure/services/scalesetvms/mock_scalesetvms/doc.go
  azure/services/securitygroups/mock_securitygroups/doc.go
  azure/services/subnets/mock_subnets/doc.go
  azure/services/tags/mock_tags/doc.go
  azure/services/virtualmachineimages/mock_virtualmachineimages/doc.go
  azure/services/virtualmachines/mock_virtualmachines/doc.go
  azure/services/virtualnetworks/mock_virtualnetworks/doc.go
  azure/services/vmextensions/mock_vmextensions/doc.go
  azure/services/vnetpeerings/mock_vnetpeerings/doc.go
  exp/api/v1alpha3/azuremachinepool_conversion.go
  exp/api/v1alpha3/azuremanagedcluster_conversion.go
  exp/api/v1alpha3/azuremanagedcontrolplane_conversion.go
  exp/api/v1alpha3/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/conversion_test.go
  exp/api/v1alpha4/azuremachinepool_conversion.go
  exp/api/v1alpha4/azuremachinepoolmachine_conversion.go
  exp/api/v1alpha4/azuremanagedcluster_conversion.go
  exp/api/v1alpha4/azuremanagedcontrolplane_conversion.go
  exp/api/v1alpha4/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha4/conversion.go
  exp/api/v1alpha4/conversion_test.go
  exp/controllers/mocks/doc.go
  internal/test/env/env.go
  internal/test/env/env_test.go
  internal/test/matchers/gomock/matchers.go
  internal/test/mock_log/doc.go
  pkg/coalescing/mocks/doc.go
  util/cache/ttllru/mocks/doc.go
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note-none, approved, lgtm

#2562 add name and owner tags to NICs
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/services/networkinterfaces/spec.go
  azure/services/networkinterfaces/spec_test.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2568 update init K8s version of workload cluster during upgrade
  test/e2e/config/azure-dev.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#2559 update the node labels for existing AKS nodepools
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/agentpools_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#2447 add ability to specify custom DNS settings for a VM in the cluster
  api/v1alpha3/azuremachine_conversion.go
  api/v1alpha3/azuremachinetemplate_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/azuremachine_conversion.go
  api/v1alpha4/azuremachinetemplate_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/azuremachine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/services/networkinterfaces/spec.go
  azure/services/networkinterfaces/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#2575 Fix spelling errors pointed out by Codespell
  controllers/helpers.go
  hack/observability/prometheus/resources/bundle.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#2582 Temporarily set broken private cluster test to optional
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm, kind/failing-test

#2566 Bump CAPI to v1.2.1
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2585 Add unit tests for spot instances converter
  azure/converters/spotinstances_test.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, ok-to-test, lgtm

#2586 Revert "Temporarily set broken private cluster test to optional"
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#2573 fix error getting activity logs in e2e for managed clusters
  test/e2e/azure_clusterproxy.go
  test/e2e/azure_logcollector.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, ok-to-test, lgtm

#2576 Add unit tests for load balancers converter
  azure/converters/loadbalancers_test.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, ok-to-test, lgtm

#2567 Apidiff test runs only if the changes are in api/ and exp/api/
  Makefile
  scripts/ci-apidiff.sh
  scripts/go_install.sh
Labels: cncf-cla: yes, size/S, release-note-none, approved, ok-to-test, lgtm, kind/failing-test

#2578 fix: MachinePool ephemeral osDisk support
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#2580 fix: set evictionPolicy Delete when Spot & Ephemeral OsDisk
  azure/converters/spotinstances.go
  azure/converters/spotinstances_test.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
  azure/services/virtualmachines/spec.go
  azure/services/virtualmachines/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#2592 Update README for office hours time changes
  README.md
  SUPPORT.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#2444 When creating AKS clusters using autoscaler enabled, do not make an update api call to agentpool service based on difference in node count
  azure/const.go
  azure/scope/managedmachinepool.go
  azure/services/agentpools/agentpools.go
  config/rbac/role.yaml
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/azuremanagedmachinepool_controller.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm, area/managedclusters

#2510 Collect HNS crashes from Windows nodes
  go.mod
  go.sum
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/windows-collect-hns-crashes.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/azure_logcollector.go
  test/e2e/helpers.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#2564 Add unit tests for VM converter and remove unused err from SDKToVM
  azure/converters/vm.go
  azure/converters/vm_test.go
  azure/services/virtualmachines/virtualmachines.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, ok-to-test, lgtm

#2543 AKS: enable isVnetManaged, add caching
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/services/subnets/subnets.go
Labels: kind/bug, kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#2595 e2e test: Log status of test before cleaning up
  test/e2e/azure_test.go
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/conformance_test.go
Labels: kind/feature, cncf-cla: yes, size/S, release-note-none, approved, ok-to-test, lgtm

#2565 Restore lint check for go comments
  .golangci.yml
  api/v1alpha3/azurecluster_conversion.go
  api/v1alpha3/azureclusteridentity_conversion.go
  api/v1alpha3/azuremachine_conversion.go
  api/v1alpha3/azuremachinetemplate_conversion.go
  api/v1alpha4/azurecluster_conversion.go
  api/v1alpha4/azuremachine_conversion.go
  api/v1alpha4/azuremachinetemplate_conversion.go
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azureclustertemplate_webhook.go
  api/v1beta1/types.go
  api/v1beta1/types_template.go
  azure/converters/subnets.go
  azure/scope/cluster.go
  azure/scope/machine.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedmachinepool.go
  azure/services/groups/groups.go
  azure/services/privatedns/record_spec.go
  azure/services/publicips/client.go
  azure/services/virtualnetworks/virtualnetworks.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  exp/api/v1alpha3/azuremachinepool_conversion.go
  exp/api/v1beta1/azuremanagedcontrolplane_types.go
  exp/api/v1beta1/azuremanagedmachinepool_types.go
  internal/test/env/env.go
  internal/test/matchers/gomega/matchers.go
  internal/test/matchers/gomock/matchers.go
  internal/test/record/logger.go
  pkg/cloudtest/cloudtest.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2555 Add more linters and config from CAPI
  .golangci.yml
  api/v1alpha3/azurecluster_conversion.go
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azureclustertemplate_default.go
  api/v1beta1/azuremachine_validation.go
  azure/defaults_test.go
  azure/scope/cluster.go
  azure/scope/machine.go
  azure/scope/machinepool.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedmachinepool.go
  azure/services/resourceskus/cache.go
  azure/services/tags/tags.go
  azure/services/virtualmachineimages/images.go
  controllers/helpers.go
  controllers/helpers_test.go
  exp/controllers/azuremachinepool_annotations.go
  exp/controllers/helpers_test.go
  feature/feature.go
  internal/test/env/env.go
  internal/test/env/env_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2607 Bump golangci-lint to v1.49.0
  .golangci.yml
  Makefile
  azure/defaults_test.go
  main.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note, approved, lgtm

#2524 Remove UseExperimentalRetryJoin from reference templates
  templates/cluster-template-aad.yaml
  templates/flavors/aad/machine-deployment.yaml
  templates/flavors/aad/patches/kubeadm-controlplane.yaml
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/patches/control-plane-kubeadm-boostrap-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/patches/machine-deployment-pr-version.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
  test/e2e/data/infrastructure-azure/v1alpha3/cluster-template-prow.yaml
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#2599 Dump resources in private cluster test
  test/e2e/azure_privatecluster.go
  test/e2e/azure_test.go
  test/e2e/common.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, ok-to-test, lgtm

#2601 Remove kcp adoption test
  Makefile
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step1/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step2/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption/step2/kustomization.yaml
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note-none, approved, ok-to-test, lgtm

#2479 Make agent pools reconcile/delete async
  azure/converters/managedagentpool.go
  azure/converters/managedagentpool_test.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/scope/managedmachinepool.go
  azure/scope/managedmachinepool_test.go
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/agentpools_test.go
  azure/services/agentpools/client.go
  azure/services/agentpools/mock_agentpools/agentpools_mock.go
  azure/services/agentpools/mock_agentpools/doc.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  azure/types.go
  exp/controllers/azuremanagedmachinepool_reconciler.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#2456 add e2e for csi migration upgrade scenarios
  templates/test/ci/cluster-template-prow-azurediskcsi-migration-off.yaml
  templates/test/ci/cluster-template-prow-external-azurediskcsi-driver.yaml
  templates/test/ci/cluster-template-prow-user-assigned-managed-identity.yaml
  templates/test/ci/patches/azurediskcsi-migration-off.yaml
  templates/test/ci/prow-azurediskcsi-migration-off/kustomization.yaml
  templates/test/ci/prow-external-azurediskcsi-driver/kustomization.yaml
  templates/test/ci/prow-external-azurediskcsi-driver/patches/external-azurediskcsi-driver.yaml
  templates/test/ci/prow-user-assigned-managed-identity/kustomization.yaml
  test/e2e/azure_csidriver.go
  test/e2e/config/azure-dev.yaml
  test/e2e/csi_migration_test.go
  test/e2e/helpers.go
  test/e2e/kubernetes/pvc/pvc.go
  test/e2e/kubernetes/storageclass/storageclass.go
Labels: kind/feature, cncf-cla: yes, release-note-none, approved, size/XXL, lgtm

#2616 use known-working Windows OS image
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/prow-ci-version-windows-containerd-2022/patches/windows-image-update.yaml
  templates/test/ci/prow-ci-version/patches/machine-deployment-ci-version-windows.yaml
  templates/test/ci/prow-ci-version/patches/machine-deployment-ci-version.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version-windows.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/patches/machine-deployment-pr-version-windows.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test
