Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2023-11, with the labels that each got.

#4209 Fix containerd and systemd-resolved race condition in ipv6 clusters
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-ipv6.yaml
  templates/flavors/dual-stack/machine-deployment.yaml
  templates/flavors/dual-stack/patches/kubeadm-controlplane.yaml
  templates/flavors/ipv6/machine-deployment.yaml
  templates/flavors/ipv6/patches/kubeadm-controlplane.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/patches/control-plane-image-ci-version.yaml
  templates/test/ci/prow-ci-version-dual-stack/patches/machine-deployment.yaml
  templates/test/ci/prow-ci-version-ipv6/patches/machine-deployment.yaml
  templates/test/ci/prow-ci-version/patches/machine-deployment-ci-version.yaml
  templates/test/ci/prow-dual-stack/machine-pool-dualstack.yaml
  templates/test/ci/prow-ipv6/machine-pool-ipv6.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#4181 Add EnableEncryptionAtHost in ManagedMachinePool
  api/v1beta1/azuremanagedmachinepool_types.go
  api/v1beta1/azuremanagedmachinepool_webhook.go
  api/v1beta1/azuremanagedmachinepool_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/converters/managedagentpool.go
  azure/converters/managedagentpool_test.go
  azure/scope/managedmachinepool.go
  azure/services/agentpools/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
Labels: cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#4218 [release-1.10] Restart containerd in ipv6 templates when restarting systemd-resolved
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-ipv6.yaml
  templates/flavors/dual-stack/machine-deployment.yaml
  templates/flavors/dual-stack/patches/kubeadm-controlplane.yaml
  templates/flavors/ipv6/machine-deployment.yaml
  templates/flavors/ipv6/patches/kubeadm-controlplane.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/prow-dual-stack/machine-pool-dualstack.yaml
  templates/test/ci/prow-ipv6/machine-pool-ipv6.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm, kind/failing-test

#4216 [release-1.11] Restart containerd in ipv6 templates when restarting systemd-resolved
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-ipv6.yaml
  templates/flavors/dual-stack/machine-deployment.yaml
  templates/flavors/dual-stack/patches/kubeadm-controlplane.yaml
  templates/flavors/ipv6/machine-deployment.yaml
  templates/flavors/ipv6/patches/kubeadm-controlplane.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/prow-dual-stack/machine-pool-dualstack.yaml
  templates/test/ci/prow-ipv6/machine-pool-ipv6.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm, kind/failing-test

#4217 wait for ASO deployment in make create-management-cluster
  Makefile
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4188 test: Add functionality to collect init container logs
  test/e2e/azure_clusterproxy.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, ok-to-test, lgtm

#4211 eliminate short-circuiting in logic to add/remove finalizers
  controllers/azuremanagedcontrolplane_controller.go
  controllers/helpers.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, lgtm

#4226 workaround cloud provider chart federated token bug
  scripts/ci-entrypoint.sh
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, priority/critical-urgent, lgtm, kind/failing-test

#4109 Install azure disk CSI driver Helm chart with CAAPH
  Makefile
  hack/create-dev-cluster.sh
  templates/addons/cluster-api-helm/azuredisk-csi-driver.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider-machine-pool.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/cluster-label-azuredisk-csi-driver.yaml
  templates/test/ci/prow-azure-cni-v1/kustomization.yaml
  templates/test/ci/prow-custom-vnet/kustomization.yaml
  templates/test/ci/prow-dual-stack/kustomization.yaml
  templates/test/ci/prow-edgezone/kustomization.yaml
  templates/test/ci/prow-flatcar/kustomization.yaml
  templates/test/ci/prow-ipv6/kustomization.yaml
  templates/test/ci/prow-machine-pool/kustomization.yaml
  templates/test/ci/prow-nvidia-gpu/kustomization.yaml
  templates/test/ci/prow-private/kustomization.yaml
  templates/test/ci/prow-topology/kustomization.yaml
  templates/test/ci/prow-workload-identity/kustomization.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/cloud-provider-azure.go
  test/e2e/common.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1beta1/bases/azuredisk-csi-driver.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/patches/cluster-label-azuredisk-csi-driver.yaml
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#4172 Don't use job name as container name for CI binaries
  docs/book/src/developers/development.md
  docs/book/src/developers/kubernetes-developers.md
  scripts/ci-build-azure-ccm.sh
  scripts/ci-build-kubernetes.sh
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/kubeadm-bootstrap-machine-pool-windows-k8s-pr-binaries.yaml
  templates/test/dev/custom-builds/patches/kubeadm-bootstrap-windows-k8s-pr-binaries.yaml
  templates/test/dev/custom-builds/patches/kubeadm-bootstrap.yaml
  templates/test/dev/custom-builds/patches/kubeadm-controlplane-bootstrap.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#4230 Revert "workaround cloud provider chart federated token bug"
  scripts/ci-entrypoint.sh
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4169 Enable OOT credential provider for all CI templates
  scripts/ci-build-azure-ccm.sh
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/prow-ci-version/kustomization.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-kcp.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-win.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider.yaml
  templates/test/ci/prow-machine-pool-ci-version/kustomization.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/kubeadm-bootstrap-windows-k8s-ci-binaries.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/kustomization.yaml
  templates/test/dev/custom-builds-machine-pool/patches/custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/kubeadm-bootstrap-machine-pool-windows-k8s-pr-binaries.yaml
  templates/test/dev/custom-builds/kustomization.yaml
Labels: cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#4052 Allow joining AzureMachinePools to AKS clusters
  api/v1beta1/azuremanagedcontrolplane_types.go
  azure/interfaces.go
  azure/mock_azure/azure_mock.go
  azure/scope/cluster.go
  azure/scope/machine.go
  azure/scope/machinepool.go
  azure/scope/machinepoolmachine.go
  azure/scope/managedcontrolplane.go
  azure/services/availabilitysets/mock_availabilitysets/availabilitysets_mock.go
  azure/services/bastionhosts/mocks_bastionhosts/bastionhosts_mock.go
  azure/services/disks/mock_disks/disks_mock.go
  azure/services/groups/groups.go
  azure/services/groups/groups_test.go
  azure/services/inboundnatrules/mock_inboundnatrules/inboundnatrules_mock.go
  azure/services/loadbalancers/mock_loadbalancers/loadbalancers_mock.go
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/mock_managedclusters/managedclusters_mock.go
  azure/services/natgateways/mock_natgateways/natgateways_mock.go
  azure/services/networkinterfaces/mock_networkinterfaces/networkinterfaces_mock.go
  azure/services/privatedns/mock_privatedns/privatedns_mock.go
  azure/services/publicips/mock_publicips/publicips_mock.go
  azure/services/scalesets/mock_scalesets/scalesets_mock.go
  azure/services/scalesetvms/mock_scalesetvms/scalesetvms_mock.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  controllers/azurecluster_reconciler.go
  controllers/azurejson_machinepool_controller.go
  controllers/azurejson_machinepool_controller_test.go
  controllers/azuremanagedcontrolplane_reconciler.go
  controllers/helpers.go
  docs/book/src/topics/managedcluster.md
  exp/api/v1beta1/azuremachinepool_default.go
  exp/api/v1beta1/azuremachinepool_default_test.go
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/azuremachinepool_controller_test.go
  exp/controllers/azuremachinepoolmachine_controller.go
  exp/controllers/azuremachinepoolmachine_controller_test.go
  exp/controllers/helpers.go
  go.mod
  test/e2e/aks.go
  test/e2e/aks_byo_node.go
  test/e2e/aks_public_ip_prefix.go
  test/e2e/azure_test.go
  test/e2e/cni.go
Labels: cncf-cla: yes, release-note, approved, size/XXL, lgtm

#4224 remove redundant natgateway's Service struct
  azure/services/natgateways/natgateways.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#4225 Set correct fqdn on private cluster
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/managedclusters_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#4240 Remove usage of autorest.NullAuthorizer
  azure/scope/clients_test.go
  azure/scope/cluster_test.go
  azure/scope/managedcontrolplane_test.go
  controllers/azuremachine_controller_test.go
  controllers/helpers_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4242 [release-1.11] Set correct fqdn on private cluster
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/managedclusters_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#4241 [release-1.10] Set correct fqdn on private cluster
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/managedclusters_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#4239 Remove use of Azure/go-autorest/tracing package
  go.mod
  go.sum
  pkg/ot/opentelemetry.go
  pkg/ot/traces.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4247 Pin Azure disk CSI driver Helm chart to v1.29.0
  Makefile
  templates/addons/cluster-api-helm/azuredisk-csi-driver.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider-machine-pool.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/cloud-provider-azure.go
  test/e2e/common.go
  test/e2e/data/infrastructure-azure/v1beta1/bases/azuredisk-csi-driver.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3998 Add implementation for MachinePool Machines
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/scope/machinepoolmachine.go
  azure/scope/machinepoolmachine_test.go
  azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go
  azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/rbac/role.yaml
  exp/api/v1beta1/azuremachinepool_types.go
  exp/api/v1beta1/azuremachinepoolmachine_types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/azuremachinepoolmachine_controller.go
  exp/controllers/azuremachinepoolmachine_controller_test.go
  go.mod
  go.sum
  test/e2e/azure_machinepool_drain.go
  test/e2e/azure_test.go
Labels: kind/feature, cncf-cla: yes, approved, release-note-action-required, size/XXL, lgtm

#4263 bump actions/dependency-review-action from 3.1.2 to 3.1.3
  .github/workflows/dependency-review.yml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#4232 [release-1.11] Add support for OOT cred provider in ci templates
  scripts/ci-build-azure-ccm.sh
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/prow-ci-version/kustomization.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-kcp.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-win.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider.yaml
  templates/test/ci/prow-machine-pool-ci-version/kustomization.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/kubeadm-bootstrap-windows-k8s-ci-binaries.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/kustomization.yaml
  templates/test/dev/custom-builds-machine-pool/patches/custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/kubeadm-bootstrap-machine-pool-windows-k8s-pr-binaries.yaml
  templates/test/dev/custom-builds/kustomization.yaml
Labels: cncf-cla: yes, release-note-none, approved, size/XXL, lgtm, kind/failing-test

#4256 fix AKS to machine pool mapper
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/helpers.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4255 wait for provisioning state in AKS e2e tests
  test/e2e/aks_autoscaler.go
  test/e2e/aks_azure_cluster_autoscaler.go
  test/e2e/aks_node_labels.go
  test/e2e/aks_node_taints.go
  test/e2e/aks_tags.go
  test/e2e/aks_upgrade.go
Labels: cncf-cla: yes, size/S, kind/flake, release-note-none, approved, lgtm

#4271 [release-1.11] wait for provisioning state in AKS e2e tests
  test/e2e/aks_autoscaler.go
  test/e2e/aks_azure_cluster_autoscaler.go
  test/e2e/aks_node_labels.go
  test/e2e/aks_node_taints.go
  test/e2e/aks_tags.go
  test/e2e/aks_upgrade.go
Labels: cncf-cla: yes, size/S, kind/flake, release-note-none, approved, lgtm

#4272 [release-1.10] wait for provisioning state in AKS e2e tests
  test/e2e/aks_autoscaler.go
  test/e2e/aks_azure_cluster_autoscaler.go
  test/e2e/aks_node_labels.go
  test/e2e/aks_node_taints.go
  test/e2e/aks_tags.go
  test/e2e/aks_upgrade.go
Labels: cncf-cla: yes, size/S, kind/flake, release-note-none, approved, lgtm

#4069 convert managedclusters and agentpools to ASO
  Makefile
  api/v1beta1/azuremanagedcluster_webhook.go
  api/v1beta1/azuremanagedcluster_webhook_test.go
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/azuremanagedmachinepool_types.go
  api/v1beta1/azuremanagedmachinepool_webhook.go
  api/v1beta1/azuremanagedmachinepool_webhook_test.go
  api/v1beta1/consts.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/converters/managedagentpool.go
  azure/converters/managedagentpool_test.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/scope/managedmachinepool.go
  azure/scope/managedmachinepool_test.go
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/agentpools_test.go
  azure/services/agentpools/client.go
  azure/services/agentpools/mock_agentpools/agentpools_mock.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/managedclusters/client.go
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/managedclusters_test.go
  azure/services/managedclusters/mock_managedclusters/doc.go
  azure/services/managedclusters/mock_managedclusters/managedclusters_mock.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  config/aso/crds.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  config/rbac/role.yaml
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_controller_test.go
  controllers/azuremanagedcontrolplane_reconciler.go
  controllers/azuremanagedmachinepool_controller.go
  controllers/azuremanagedmachinepool_controller_test.go
  controllers/azuremanagedmachinepool_reconciler.go
  controllers/helpers_test.go
  docs/book/src/topics/managedcluster.md
  main.go
  test/e2e/aks_autoscaler.go
  test/e2e/aks_spot.go
  test/e2e/aks_tags.go
  util/maps/maps.go
  util/maps/maps_test.go
Labels: cncf-cla: yes, kind/cleanup, release-note, approved, size/XXL, lgtm, area/managedclusters

#4248 bump github.com/Azure/azure-service-operator/v2 from v2.3.0 to v2.4.0
  Makefile
  config/aso/crds.yaml
  config/aso/kustomization.yaml
  go.mod
  go.sum
  internal/test/env/env.go
  main.go
Labels: cncf-cla: yes, kind/cleanup, release-note, approved, size/XXL, lgtm

#4125 Increase test coverage for azurecluster_controller.go
  controllers/azurecluster_controller_test.go
  controllers/azurecluster_reconciler.go
  controllers/azurecluster_reconciler_test.go
  controllers/azuremachine_controller_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4280 Chores: upload credential-provider-config.yaml to artifact store in ci build
  scripts/ci-build-azure-ccm.sh
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-kcp.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-win.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/kubeadm-bootstrap-windows-k8s-ci-binaries.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/kubeadm-bootstrap-machine-pool-windows-k8s-pr-binaries.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm, kind/failing-test

#4254 Add constants for kind names
  api/v1beta1/azurecluster_default_test.go
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/azurecluster_validation_test.go
  api/v1beta1/azurecluster_webhook.go
  api/v1beta1/azureclusteridentity_validation.go
  api/v1beta1/azureclusteridentity_webhook.go
  api/v1beta1/azuremachine_default_test.go
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/consts.go
  azure/scope/cluster.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/scope/managedcontrolplane.go
  controllers/asosecret_controller.go
  controllers/azurecluster_controller.go
  controllers/azureidentity_controller.go
  controllers/azurejson_machine_controller.go
  controllers/azurejson_machine_controller_test.go
  controllers/azurejson_machinepool_controller.go
  controllers/azurejson_machinepool_controller_test.go
  controllers/azurejson_machinetemplate_controller.go
  controllers/azurejson_machinetemplate_controller_test.go
  controllers/azuremachine_controller_test.go
  controllers/azuremanagedcluster_controller.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_controller_test.go
  controllers/azuremanagedmachinepool_controller_test.go
  controllers/helpers.go
  controllers/helpers_test.go
  exp/api/v1beta1/azuremachinepool_webhook_test.go
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/azuremachinepool_controller_unit_test.go
  exp/controllers/azuremachinepoolmachine_controller_test.go
  exp/controllers/helpers_test.go
  util/tele/span_logger.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4273 Docs: Pod identity deprecation
  docs/book/src/SUMMARY.md
  docs/book/src/topics/identities-use-cases.md
  docs/book/src/topics/identities.md
  docs/book/src/topics/multitenancy.md
Labels: cncf-cla: yes, size/L, release-note, approved, kind/documentation, lgtm, kind/deprecation

#4284 update metadata.yaml for 1.12 release
  metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4283 [release-1.11] chores: upload credential-provider-config.yaml to artifact store in c…
  scripts/ci-build-azure-ccm.sh
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-kcp.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-win.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/kubeadm-bootstrap-windows-k8s-ci-binaries.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/kubeadm-bootstrap-machine-pool-windows-k8s-pr-binaries.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#4288 Update docs summary
  docs/book/src/SUMMARY.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#4285 update test metadata for 1.12 release
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4287 Add missing kind constants for API
  api/v1beta1/azureclustertemplate_webhook.go
  api/v1beta1/azuremachine_webhook.go
  api/v1beta1/azuremachinetemplate_webhook.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook.go
  api/v1beta1/azuremanagedmachinepool_webhook.go
  api/v1beta1/azuremanagedmachinepooltemplate_webhook.go
  api/v1beta1/consts.go
  azure/scope/managedcontrolplane.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4274 Fix "log.SetLogger(...) was never called" error
  main.go
  test/logger.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4289 Export env vars needed for SSH access
  hack/util.sh
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#4279 Revert "Pin Azure disk CSI driver Helm chart to v1.29.0"
  Makefile
  templates/addons/cluster-api-helm/azuredisk-csi-driver.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider-machine-pool.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/cloud-provider-azure.go
  test/e2e/common.go
  test/e2e/data/infrastructure-azure/v1beta1/bases/azuredisk-csi-driver.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#4296 Revert "workaround ASO swallowing updates into ongoing operations"
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#4278 Create test to cover path of azureMachinePool.Spec.UserAssignedIdenti…
  azure/services/identities/client.go
  controllers/azurejson_machinepool_controller.go
  controllers/azurejson_machinepool_controller_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, ok-to-test, lgtm

#4301 fix log flags
  main.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4269 Add unit tests to AzureIdentityReconciler
  controllers/azureidentity_controller.go
  controllers/azureidentity_controller_test.go
  controllers/azurejson_machine_controller_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, ok-to-test, lgtm

#4302 fix ever-growing log messages with overlapping fields
  controllers/asosecret_controller.go
  controllers/azureidentity_controller.go
  controllers/helpers.go
  exp/controllers/helpers.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#4307 Fix support for AKS BYOCNI by allowing networkPlugin: none
  api/v1beta1/types_class.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, ok-to-test, lgtm

#4305 Bump pre-commit pylint to v3.0.2
  .pre-commit-config.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4143 Convert bastionhosts to ASO
  Makefile
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/services/bastionhosts/bastionhosts.go
  azure/services/bastionhosts/bastionhosts_test.go
  azure/services/bastionhosts/client.go
  azure/services/bastionhosts/mocks_bastionhosts/bastionhosts_mock.go
  azure/services/bastionhosts/mocks_bastionhosts/doc.go
  azure/services/bastionhosts/spec.go
  azure/services/bastionhosts/spec_test.go
  config/aso/crds.yaml
  config/rbac/role.yaml
  controllers/azurecluster_controller.go
  controllers/azurecluster_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, release-note, approved, size/XXL, lgtm

#4295 test deleting all tags, node labels, and node taints in AKS e2e
  go.mod
  test/e2e/aks_node_labels.go
  test/e2e/aks_node_taints.go
  test/e2e/aks_tags.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4320 Work around mdbook installation on Apple Silicon
  docs/book/install-and-build.sh
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#4275 Update mdbook
  .gitignore
  docs/book/Makefile
  docs/book/book.toml
  docs/book/install-and-build.sh
  netlify.toml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#4303 Add unit tests to azuremanagedcontrolplane reconciler
  azure/scope/managedcontrolplane.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_controller_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, ok-to-test, lgtm
