Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2023-01, with the labels that each got.

#2977 OOT test uses MachineDeployment
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2964 :book: Add managed addon info
  docs/book/src/topics/addons.md
  docs/book/src/topics/managedcluster.md
Labels: cncf-cla: yes, size/M, release-note, approved, kind/documentation, ok-to-test, lgtm

#2962 Add unit tests for converters/vmss
  azure/converters/vmss_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2932 Update Cluster API Visualizer to v1.0.2
  Tiltfile
  hack/observability/cluster-api-visualizer/chart/Chart.yaml
  hack/observability/cluster-api-visualizer/chart/templates/clusterrole.yaml
  hack/observability/cluster-api-visualizer/fetch-visualizer-resources.sh
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2958 Standardize autorest/azure import alias as azureautorest
  .golangci.yml
  azure/defaults.go
  azure/errors.go
  azure/scope/clients.go
  azure/scope/machine_test.go
  azure/scope/machinepool_test.go
  azure/services/identities/client.go
  azure/services/natgateways/spec.go
  test/e2e/aks_versions.go
  test/e2e/azure_logcollector.go
  test/e2e/azure_privatecluster.go
  test/e2e/azure_vmextensions.go
  util/azure/azure.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2978 [release-1.6] fix machine pool wait in AKS and OOT e2e test
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#2986 Remove unused kubescape e2e spec
  test/e2e/helpers.go
  test/e2e/kubescape.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#2989 [release-1.6] bump CAPI to v1.2.8
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm, kind/failing-test

#2985 add marosset to reviewers list
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2988 Update Cluster API Visualizer to v1.1.0
  hack/observability/cluster-api-visualizer/chart/Chart.yaml
  hack/observability/cluster-api-visualizer/fetch-visualizer-resources.sh
Labels: kind/feature, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#2990 make AzureManagedMachinePool spec.name immutable
  docs/book/src/topics/managedcluster.md
  exp/api/v1beta1/azuremanagedmachinepool_webhook.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook_test.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, lgtm

#2938 Add support for kubeletDiskType
  azure/converters/managedagentpool.go
  azure/scope/managedmachinepool.go
  azure/scope/managedmachinepool_test.go
  azure/services/agentpools/agentpools_test.go
  azure/services/agentpools/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  docs/book/src/topics/managedcluster.md
  exp/api/v1alpha3/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremanagedmachinepool_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremanagedmachinepool_types.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#2411 Support for configurable Network Interfaces
  api/v1alpha3/azuremachine_conversion.go
  api/v1alpha3/azuremachinetemplate_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/azuremachine_conversion.go
  api/v1alpha4/azuremachinetemplate_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/azuremachine_default.go
  api/v1beta1/azuremachine_default_test.go
  api/v1beta1/azuremachine_types.go
  api/v1beta1/azuremachine_validation.go
  api/v1beta1/azuremachine_validation_test.go
  api/v1beta1/azuremachine_webhook.go
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/azuremachinetemplate_webhook.go
  api/v1beta1/azuremachinetemplate_webhook_test.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/defaults.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/services/networkinterfaces/networkinterfaces_test.go
  azure/services/networkinterfaces/spec.go
  azure/services/networkinterfaces/spec_test.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
  azure/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  controllers/azuremachine_reconciler.go
  exp/api/v1alpha3/azuremachinepool_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremachinepool_conversion.go
  exp/api/v1alpha4/azuremachinepoolmachine_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremachinepool_default.go
  exp/api/v1beta1/azuremachinepool_default_test.go
  exp/api/v1beta1/azuremachinepool_types.go
  exp/api/v1beta1/azuremachinepool_webhook.go
  exp/api/v1beta1/azuremachinepool_webhook_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  exp/controllers/azuremachinepool_reconciler.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, lifecycle/active, size/XXL, ok-to-test, lgtm

#2955 bump aad pod identity to v1.8.14
  config/default/aad-pod-identity-deployment.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, release-note, approved, lgtm

#3002 Handle ipv6 and dual stack CIDRs in ci-entrypoint.sh
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2996 prefer CAPI replicas-managed-by annotation for AKS autoscaler
  azure/const.go
  azure/scope/machinepool.go
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/agentpools_test.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#2838 AzureManagedCluster: Full support for AKS Cluster Autoscaler
  azure/converters/managedagentpool.go
  azure/converters/managedagentpool_test.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedmachinepool_test.go
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/client.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/managedclusters/client.go
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/managedclusters_test.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  docs/book/src/topics/managedcluster.md
  exp/api/v1alpha3/azuremanagedcontrolplane_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremanagedcontrolplane_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremanagedcontrolplane_default.go
  exp/api/v1beta1/azuremanagedcontrolplane_types.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  exp/api/v1beta1/azuremanagedmachinepool_webhook_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  test/e2e/aks_azure_cluster_autoscaler.go
  test/e2e/azure_test.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, lifecycle/active, size/XXL, lgtm, area/managedclusters

#2813 VMSS Flex support for MachinePools
  api/v1beta1/types.go
  azure/converters/vmss.go
  azure/converters/vmss_test.go
  azure/scope/machinepool.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesetvms/mock_scalesetvms/scalesetvms_mock.go
  azure/services/scalesetvms/scalesetvms.go
  azure/services/scalesetvms/scalesetvms_test.go
  azure/services/virtualmachines/client.go
  azure/services/virtualmachines/mock_virtualmachines/client_mock.go
  azure/types.go
  azure/types_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepoolmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  controllers/helpers.go
  controllers/helpers_test.go
  docs/book/src/topics/machinepools.md
  exp/api/v1alpha3/azuremachinepool_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremachinepool_conversion.go
  exp/api/v1alpha4/azuremachinepoolmachine_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremachinepool_test.go
  exp/api/v1beta1/azuremachinepool_types.go
  exp/api/v1beta1/azuremachinepool_webhook.go
  exp/api/v1beta1/azuremachinepool_webhook_test.go
  exp/api/v1beta1/azuremachinepoolmachine_types.go
  main.go
  templates/cluster-template-external-cloud-provider-machinepool.yaml
  templates/flavors/external-cloud-provider-machinepool/kustomization.yaml
  templates/flavors/external-cloud-provider-machinepool/machine-pool-deployment.yaml
  templates/flavors/external-cloud-provider-machinepool/patches/external-cloud-provider.yaml
  templates/flavors/external-cloud-provider-machinepool/patches/vmss-flex.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-vmss-flex.yaml
  templates/test/ci/patches/uami-mp-0.yaml
  templates/test/ci/prow-external-cloud-provider-vmss-flex/kustomization.yaml
  test/e2e/azure_machinepools.go
  test/e2e/azure_test.go
  test/e2e/config/azure-dev.yaml
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#2999 don’t default to AKS networkPolicy=calico
  azure/services/managedclusters/spec.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook.go
  exp/api/v1beta1/azuremanagedcontrolplane_webhook_test.go
Labels: kind/feature, cncf-cla: yes, size/XS, kind/flake, release-note, approved, lgtm

#3007 fix dependabot.yaml indentation
  .github/dependabot.yml
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3008 update dependabot-code-gen step
  .github/workflows/dependabot-code-gen.yml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3012 Update CAPI contract for v1.7 of CAPZ
  metadata.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3015 Update dependabot.yml
  .github/dependabot.yml
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3014 update E2E InfrastructureProvider API contract
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#3016 Add back commit-message.prefix as it is a dependency
  .github/dependabot.yml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3028 Update dependabot schedule to run weekly 9am EST
  .github/dependabot.yml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#3031 bump CAPI to v1.3.2
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#3034 [release-1.6] Bump CAPI to v1.2.9
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3030 fix agentpool taints diff check
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm, area/managedclusters

#3037 [release-1.6] fix agentpool taints diff check
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#3033 Wait for nodes after CCM install in ci-entrypoint
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#3050 fix unnecessary reconciles on AKS node taints
  azure/services/agentpools/spec.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test, area/managedclusters

#2970 Set build time GOARCH to the one reported by go env
  Tiltfile
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note, approved, ok-to-test, lgtm

#3011 update codecov workflow name
  .github/workflows/cover.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#2950 E2E: verify daemonset pods after machines
  test/e2e/azure_test.go
  test/e2e/cloud-provider-azure.go
  test/e2e/cni.go
  test/e2e/daemonsets.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, kind/failing-test

#3006 refactor agentpool test definitions
  azure/services/agentpools/agentpools_test.go
  azure/services/agentpools/spec_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm, area/managedclusters

#3060 add empty node taints agentpool parameters test
  azure/services/agentpools/spec_test.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#3056 enable security updates for release-1.7 and release 1.6
  .github/dependabot.yml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#3058 Always run AKS E2E get+update as transaction
  test/e2e/aks_autoscaler.go
  test/e2e/aks_azure_cluster_autoscaler.go
  test/e2e/aks_public_ip_prefix.go
  test/e2e/aks_tags.go
  test/e2e/aks_upgrade.go
  test/e2e/azure_machinepool_drain.go
Labels: cncf-cla: yes, kind/flake, size/L, release-note-none, approved, lgtm

#3061 docs/book/src/topics/data-disks.md: fix dead link
  docs/book/src/topics/data-disks.md
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3063 Fixing panic on AzureMachinePool creation with auto-scale
  azure/scope/managedmachinepool.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#3069 add release-note-none label to dependabot PRs
  .github/dependabot.yml
Labels: kind/bug, cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#2890 Add Flatcar Container Linux template
  Makefile
  Tiltfile
  docs/book/src/SUMMARY.md
  docs/book/src/topics/flatcar.md
  templates/cluster-template-flatcar.yaml
  templates/flavors/flatcar/kustomization.yaml
  templates/flavors/flatcar/machine-deployment.yaml
  templates/flavors/flatcar/patches/kubeadm-controlplane.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/prow-flatcar/kustomization.yaml
  test/e2e/azure_logcollector.go
  test/e2e/azure_test.go
  test/e2e/common.go
  test/e2e/config/azure-dev.yaml
  test/e2e/helpers.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, lgtm

#3068 add AKS node labels e2e test
  test/e2e/aks_node_labels.go
  test/e2e/azure_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#3078 Bump golangci-lint to v1.50.1
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3081 [release-1.7] Always run AKS E2E get+update as transaction
  test/e2e/aks_autoscaler.go
  test/e2e/aks_azure_cluster_autoscaler.go
  test/e2e/aks_public_ip_prefix.go
  test/e2e/aks_tags.go
  test/e2e/aks_upgrade.go
  test/e2e/azure_machinepool_drain.go
Labels: cncf-cla: yes, kind/flake, size/L, release-note-none, approved, lgtm

#3038 add e2e test for AKS node pool taints
  test/e2e/aks_node_taints.go
  test/e2e/azure_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm, area/managedclusters

#3079 standardize curl retries in scripts
  Makefile
  Tiltfile
  docs/book/install-and-build.sh
  hack/create-custom-cloud-provider-config.sh
  hack/ensure-azcli.sh
  hack/observability/prometheus/fetch-prometheus-resources.sh
  hack/util.sh
  hack/verify-starlark.sh
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/S, kind/flake, release-note-none, approved, lgtm

#3084 [release-1.7] E2E: use a common cluster-identity-secret
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/S, kind/flake, release-note-none, approved, lgtm

#3046 feat/ add outboundType support
  api/v1alpha3/azuremanagedcontrolplane_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/azuremanagedcontrolplane_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/services/managedclusters/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#3074 dependabot: ignore subpackage releases of opentelemetry-go
  .github/dependabot.yml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#3089 remove CSI migration test for EOL'd k8s v1.22
  test/e2e/csi_migration_test.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, kind/cleanup, size/L, approved, lgtm

#3086 E2E: retries in CopyConfigMap func
  test/e2e/cni.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/S, kind/flake, release-note-none, approved, lgtm

#3097 Add pod describe to e2e logger
  go.mod
  go.sum
  test/e2e/azure_clusterproxy.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3099 helm gpu-operator instead of ClusterResourceSet
  docs/book/src/topics/gpu.md
  hack/fetch-nvidia-resources.sh
  templates/cluster-template-nvidia-gpu.yaml
  templates/flavors/nvidia-gpu/clusterpolicy-crd.yaml
  templates/flavors/nvidia-gpu/gpu-operator-components.yaml
  templates/flavors/nvidia-gpu/gpu-operator-resources-set.yaml
  templates/flavors/nvidia-gpu/kustomization.yaml
  templates/flavors/nvidia-gpu/patches/cluster.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  test/e2e/azure_test.go
  test/e2e/cloud-provider-azure.go
  test/e2e/cni.go
  test/e2e/gpu_operator.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, kind/flake, release-note-none, approved, size/XXL, lgtm, kind/failing-test

#3110 Increase linter timeout to 10m
  .golangci.yml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3112 Add release instructions for updating the branch
  docs/book/src/developers/images/netlify_deploys.png
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#3115 Remove Calico felix override workaround
  Tiltfile
  docs/book/src/topics/addons.md
  scripts/ci-entrypoint.sh
  templates/addons/calico/felix-override.yaml
  test/e2e/cni.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#3076 add nojnhuh to reviewers list
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3128 log diffs for agentpools
  azure/services/agentpools/spec.go
Labels: kind/feature, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3088 Update default k8s version to v1.25 for testing
  Makefile
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#3120 removed SetBootstrapCondition
  azure/scope/machine.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
Labels: cncf-cla: yes, tide/merge-method-squash, size/L, release-note-none, approved, ok-to-test, lgtm
