Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2023-12, with the labels that each got.

#4321 Temporarily pin Flatcar version to v1.26.10
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#4323 Don't install CNI twice in e2e tests
  test/e2e/azure_test.go
  test/e2e/capi_test.go
  test/e2e/conformance_test.go
Labels: cncf-cla: yes, kind/flake, size/M, release-note-none, approved, lgtm

#4324 return from ASO reconcile early for no specs
  azure/services/aso/service.go
  azure/services/aso/service_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4268 Update privateclusters e2e test for SDKv2
  .golangci.yml
  go.mod
  go.sum
  test/e2e/azure_privatecluster.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4326 include *_test.go files for lint rules already ignored in test/
  .golangci.yml
  internal/test/env/env_test.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4334 label Cluster for azuredisk-csi HelmChartProxy at E2E runtime
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider-machine-pool.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/cluster-label-azuredisk-csi-driver.yaml
  templates/test/ci/prow-azure-cni-v1/kustomization.yaml
  templates/test/ci/prow-custom-vnet/kustomization.yaml
  templates/test/ci/prow-dual-stack/kustomization.yaml
  templates/test/ci/prow-edgezone/kustomization.yaml
  templates/test/ci/prow-flatcar/kustomization.yaml
  templates/test/ci/prow-ipv6/kustomization.yaml
  templates/test/ci/prow-machine-pool/kustomization.yaml
  templates/test/ci/prow-nvidia-gpu/kustomization.yaml
  templates/test/ci/prow-private/kustomization.yaml
  templates/test/ci/prow-topology/kustomization.yaml
  templates/test/ci/prow-workload-identity/kustomization.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/cloud-provider-azure.go
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/patches/cluster-label-azuredisk-csi-driver.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#4344 [release-1.12] Bump CAPI to v1.5.4
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4108 migrate private endpoints service to ASO
  Makefile
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/services/privateendpoints/client.go
  azure/services/privateendpoints/mock_privateendpoints/client_mock.go
  azure/services/privateendpoints/mock_privateendpoints/doc.go
  azure/services/privateendpoints/mock_privateendpoints/privateendpoints_mock.go
  azure/services/privateendpoints/privateendpoints.go
  azure/services/privateendpoints/privateendpoints_test.go
  azure/services/privateendpoints/spec.go
  azure/services/privateendpoints/spec_test.go
  config/aso/crds.yaml
  config/rbac/role.yaml
  controllers/azurecluster_controller.go
  controllers/azurecluster_reconciler.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_reconciler.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#4348 [release-1.11] Bump CAPI to v1.5.4
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, lgtm

#4349 Add missing kind make dependency
  Makefile
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4182 Bump CAPI to v1.6.0
  Makefile
  Tiltfile
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepoolmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepooltemplates.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  exp/api/v1beta1/zz_generated.deepcopy.go
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/aks_clusterclass.go
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note, priority/important-soon, approved, lgtm

#4357 Update Wasm docs for new containerd shims release
  docs/book/src/topics/wasi.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, kind/documentation, lgtm

#4350 Remove DNS workaround for ipv6 templates
  docs/book/src/topics/ipv6.md
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-ipv6.yaml
  templates/flavors/dual-stack/machine-deployment.yaml
  templates/flavors/dual-stack/patches/kubeadm-controlplane.yaml
  templates/flavors/ipv6/machine-deployment.yaml
  templates/flavors/ipv6/patches/kubeadm-controlplane.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/prow-ci-version-dual-stack/patches/machine-deployment.yaml
  templates/test/ci/prow-ci-version-ipv6/patches/machine-deployment.yaml
  templates/test/ci/prow-dual-stack/machine-pool-dualstack.yaml
  templates/test/ci/prow-ipv6/machine-pool-ipv6.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4366 Add automation to create release branch and tags
  .github/workflows/release.yaml
  .gitignore
  CHANGELOG/README.md
  Makefile
  docs/book/src/developers/releasing.md
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4308 Fix: DNSPrefix error on existing tenant cluster
  api/v1beta1/azuremanagedcontrolplane_default.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, ok-to-test, lgtm

#4315 chore: update AzCNI to new installer image
  templates/addons/azure-cni-v1.yaml
  templates/addons/azure-cni-v1/kustomization.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note, approved, ok-to-test, lgtm

#4345 bump github.com/Azure/azure-service-operator/v2 from v2.4.0 to v2.5.0
  Makefile
  config/aso/crds.yaml
  config/aso/kustomization.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, release-note, approved, size/XXL, lgtm

#4369 Add release notes for v1.12.1
  CHANGELOG/release-notes-v1.12.1.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4238 docs: adding crucial informations regarding Azure CNI usage with CAPZ
  docs/book/src/topics/addons.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, ok-to-test, lgtm

#4371 ASO: Return readyErr over not done err when tags fail
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#4377 Add release notes for v1.12.1 (fixed)
  CHANGELOG/v1.12.1.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4380 [release-1.11] ASO: Return readyErr over not done err when tags fail
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#4382 Add release notes for v1.11.7
  CHANGELOG/v1.11.7.md
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4370 Fix release-notes make target to work with new process
  CHANGELOG/release-notes-v1.12.1.md
  Makefile
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#4372 update ASO managed clusters to 20231001
  api/v1beta1/azuremanagedmachinepool_webhook_test.go
  azure/converters/managedagentpool.go
  azure/converters/managedagentpool_test.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/scope/managedmachinepool.go
  azure/scope/managedmachinepool_test.go
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/agentpools_test.go
  azure/services/agentpools/mock_agentpools/agentpools_mock.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/managedclusters_test.go
  azure/services/managedclusters/mock_managedclusters/managedclusters_mock.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  controllers/azuremanagedcontrolplane_controller_test.go
  main.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4381 hack: Use absolute path for SSH key vars
  hack/util.sh
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#4137 Added missing test coverage for azureimage_validation.go
  api/v1beta1/azureimage_validation_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, ok-to-test, lgtm

#4375 Add test, comment, cleanup for DNSPrefix webhook fix
  api/v1beta1/azuremanagedcontrolplane_default.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4387 Revert "Use clusterctl move annotation on last systempool validation"
  api/v1beta1/azuremanagedmachinepool_webhook.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#4374 update K8s version
  Tiltfile
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4213 handle clusterctl block-move annotation
  controllers/azurecluster_controller.go
  controllers/azurecluster_controller_test.go
  controllers/azuremachine_controller.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedmachinepool_controller.go
  controllers/helpers.go
  controllers/helpers_test.go
  exp/controllers/azuremachinepool_controller.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#4391 fix makefile error message when using on macOS
  Makefile
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4392 AzureManagedMachinePool ValidateDelete Webhook will check AMMP for DeleteForMoveAnnotation annotation
  api/v1beta1/azuremanagedmachinepool_webhook.go
  api/v1beta1/azuremanagedmachinepool_webhook_test.go
  api/v1beta1/azuremanagedmachinepooltemplate_webhook.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#4208 Remove unused function setCredentials
  azure/scope/clients.go
  azure/scope/clients_test.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  controllers/asosecret_controller_test.go
  controllers/azurecluster_controller_test.go
  controllers/azurejson_machine_controller_test.go
  controllers/azurejson_machinepool_controller_test.go
  controllers/azurejson_machinetemplate_controller_test.go
  controllers/azuremachine_controller_test.go
  controllers/azuremanagedcontrolplane_controller_test.go
  controllers/azuremanagedmachinepool_controller_test.go
  controllers/helpers_test.go
  exp/controllers/azuremachinepool_controller_test.go
  exp/controllers/azuremachinepoolmachine_controller_test.go
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm

#4300 convert subnets and virtualnetworks to ASO
  Makefile
  azure/converters/extendedlocation.go
  azure/converters/extendedlocation_test.go
  azure/converters/subnets.go
  azure/converters/subnets_test.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/services/subnets/client.go
  azure/services/subnets/mock_subnets/subnets_mock.go
  azure/services/subnets/spec.go
  azure/services/subnets/spec_test.go
  azure/services/subnets/subnets.go
  azure/services/subnets/subnets_test.go
  azure/services/virtualnetworks/client.go
  azure/services/virtualnetworks/mock_virtualnetworks/client_mock.go
  azure/services/virtualnetworks/mock_virtualnetworks/doc.go
  azure/services/virtualnetworks/mock_virtualnetworks/virtualnetworks_mock.go
  azure/services/virtualnetworks/spec.go
  azure/services/virtualnetworks/spec_test.go
  azure/services/virtualnetworks/virtualnetworks.go
  azure/services/virtualnetworks/virtualnetworks_test.go
  config/aso/crds.yaml
  config/rbac/role.yaml
  controllers/azurecluster_controller.go
  controllers/azurecluster_controller_test.go
  controllers/azurecluster_reconciler.go
  controllers/azurecluster_reconciler_test.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_controller_test.go
  controllers/azuremanagedcontrolplane_reconciler.go
  main.go
Labels: cncf-cla: yes, kind/cleanup, release-note, approved, size/XXL, lgtm

#4412 [release-1.11] Allow configuring ASO for non-public cloud at install
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/types_class.go
  config/aso/credentials.yaml
  config/aso/kustomization.yaml
  config/aso/settings.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  docs/book/src/topics/aso.md
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#4415 Add disk encryption options documentation
  docs/book/src/SUMMARY.md
  docs/book/src/topics/disk-encryption.md
  docs/book/src/topics/disks.md
Labels: cncf-cla: yes, size/M, release-note, approved, kind/documentation, ok-to-test, lgtm
