Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2023-09, with the labels that each got.

#3933 Convert roleassignments service to SDKv2
  azure/services/roleassignments/client.go
  azure/services/roleassignments/roleassignments.go
  azure/services/roleassignments/spec.go
  controllers/azuremachine_reconciler.go
  exp/controllers/azuremachinepool_controller_unit_test.go
  exp/controllers/azuremachinepool_reconciler.go
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3937 Convert vnetpeerings service to SDKv2
  azure/services/vnetpeerings/client.go
  azure/services/vnetpeerings/spec.go
  azure/services/vnetpeerings/vnetpeerings.go
  controllers/azurecluster_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3958 [release-1.9] Label kubeconfig with cluster name
  azure/scope/managedcontrolplane.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3957 [release-1.10] Label kubeconfig with cluster name
  azure/scope/managedcontrolplane.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3935 update routetables service to SDK v2
  azure/services/routetables/client.go
  azure/services/routetables/routetables.go
  azure/services/routetables/spec.go
  controllers/azurecluster_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3954 Convert resourcehealth service to SDKv2
  azure/converters/resourcehealth.go
  azure/converters/resourcehealth_test.go
  azure/services/resourcehealth/client.go
  azure/services/resourcehealth/mock_resourcehealth/client_mock.go
  azure/services/resourcehealth/resourcehealth.go
  azure/services/resourcehealth/resourcehealth_test.go
  controllers/azuremanagedcontrolplane_reconciler.go
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3951 Convert subnets service to SDKv2
  azure/converters/subnets.go
  azure/converters/subnets_test.go
  azure/services/subnets/client.go
  azure/services/subnets/spec.go
  azure/services/subnets/spec_test.go
  azure/services/subnets/subnets.go
  azure/services/subnets/subnets_test.go
  controllers/azurecluster_reconciler.go
  controllers/azuremanagedcontrolplane_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3934 fix asyncpoller long running op state cleanup
  azure/services/asyncpoller/asyncpoller.go
  azure/services/asyncpoller/asyncpoller_test.go
  azure/services/availabilitysets/client.go
  azure/services/bastionhosts/client.go
  azure/services/inboundnatrules/client.go
  azure/services/natgateways/client.go
  azure/services/vmextensions/client.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3953 Convert identities service to SDKv2
  azure/services/identities/client.go
  azure/services/identities/mock_identities/client_mock.go
  azure/services/virtualmachines/virtualmachines.go
  controllers/azuremachine_reconciler.go
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#3770 add doc for workload identity
  docs/book/src/SUMMARY.md
  docs/book/src/topics/multitenancy.md
  docs/book/src/topics/workload-identity.md
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#3959 Convert privatedns service to SDKv2
  azure/converters/dns.go
  azure/converters/dns_test.go
  azure/services/privatedns/link_client.go
  azure/services/privatedns/link_spec.go
  azure/services/privatedns/link_spec_test.go
  azure/services/privatedns/privatedns.go
  azure/services/privatedns/record_client.go
  azure/services/privatedns/record_spec.go
  azure/services/privatedns/record_spec_test.go
  azure/services/privatedns/zone_client.go
  azure/services/privatedns/zone_spec.go
  azure/services/privatedns/zone_spec_test.go
  controllers/azurecluster_reconciler.go
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3962 ignore AKS user-assigned ClientID/PrincipalID in diff
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#3949 bump github.com/Azure/azure-service-operator/v2 from v2.2.0 to v2.3.0
  Makefile
  config/aso/crds.yaml
  config/aso/kustomization.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#3963 [release-1.10] ignore AKS user-assigned ClientID/PrincipalID in diff
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#3938 convert securitygroups service to SDK v2
  azure/converters/rules.go
  azure/defaults.go
  azure/defaults_test.go
  azure/services/agentpools/client.go
  azure/services/managedclusters/client.go
  azure/services/securitygroups/client.go
  azure/services/securitygroups/securitygroups.go
  azure/services/securitygroups/securitygroups_test.go
  azure/services/securitygroups/spec.go
  azure/services/securitygroups/spec_test.go
  controllers/azurecluster_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3952 Convert virtualnetworks service to SDKv2
  azure/converters/extendedlocation.go
  azure/converters/extendedlocation_test.go
  azure/converters/subnets.go
  azure/converters/subnets_test.go
  azure/scope/managedcontrolplane.go
  azure/services/subnets/subnets.go
  azure/services/virtualnetworks/client.go
  azure/services/virtualnetworks/spec.go
  azure/services/virtualnetworks/virtualnetworks.go
  azure/services/virtualnetworks/virtualnetworks_test.go
  controllers/azurecluster_reconciler.go
  controllers/azuremanagedcontrolplane_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3967 convert networkinterfaces service to SDK v2
  azure/services/networkinterfaces/client.go
  azure/services/networkinterfaces/networkinterfaces.go
  azure/services/networkinterfaces/spec.go
  azure/services/networkinterfaces/spec_test.go
  azure/services/virtualmachines/virtualmachines.go
  azure/services/virtualmachines/virtualmachines_test.go
  controllers/azuremachine_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3964 restore capz-system namespace labels
  config/aso/kustomization.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3969 update loadbalancers service to use Azure SDK v2
  azure/converters/loadbalancers.go
  azure/converters/loadbalancers_test.go
  azure/services/loadbalancers/client.go
  azure/services/loadbalancers/loadbalancers.go
  azure/services/loadbalancers/spec.go
  azure/services/loadbalancers/spec_test.go
  controllers/azurecluster_reconciler.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#3799 Make scalesetvms delete async
  azure/scope/machinepoolmachine.go
  azure/scope/machinepoolmachine_test.go
  azure/services/scalesetvms/client.go
  azure/services/scalesetvms/mock_scalesetvms/client_mock.go
  azure/services/scalesetvms/mock_scalesetvms/scalesetvms_mock.go
  azure/services/scalesetvms/scalesetvms.go
  azure/services/scalesetvms/scalesetvms_test.go
  azure/services/scalesetvms/spec.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#3939 Convert tags service to SDKv2
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/services/async/interfaces.go
  azure/services/async/mock_async/async_mock.go
  azure/services/privatedns/privatedns.go
  azure/services/privatedns/privatedns_test.go
  azure/services/publicips/publicips.go
  azure/services/publicips/publicips_test.go
  azure/services/tags/client.go
  azure/services/tags/mock_tags/client_mock.go
  azure/services/tags/tags.go
  azure/services/tags/tags_test.go
  azure/services/virtualnetworks/virtualnetworks.go
  azure/services/virtualnetworks/virtualnetworks_test.go
  controllers/azurecluster_reconciler.go
  controllers/azuremachine_reconciler.go
  controllers/azuremanagedcontrolplane_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3987 Convert /api references to SDKv2
  api/v1beta1/azuremachine_default.go
  api/v1beta1/azuremachine_validation.go
  api/v1beta1/azuremachine_validation_test.go
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/azuremachinetemplate_webhook_test.go
  test/e2e/azure_machinepools.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3936 Convert resourceskus service to SDKv2
  azure/scope/machine.go
  azure/services/availabilitysets/availabilitysets_test.go
  azure/services/networkinterfaces/spec_test.go
  azure/services/resourceskus/cache.go
  azure/services/resourceskus/cache_test.go
  azure/services/resourceskus/client.go
  azure/services/resourceskus/mock_resourceskus/resourceskus_mock.go
  azure/services/resourceskus/sku.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesets/spec_test.go
  azure/services/virtualmachines/spec_test.go
  controllers/azurecluster_reconciler_test.go
  controllers/azuremachine_controller_test.go
  controllers/azuremachine_reconciler_test.go
  exp/controllers/azuremachinepool_controller_unit_test.go
  exp/controllers/azuremachinepool_reconciler_test.go
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note-none, approved, lgtm

#3983 fix unit test failure with Go 1.21
  azure/services/inboundnatrules/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3972 update publicips service to use Azure SDK v2
  azure/converters/extendedlocation.go
  azure/converters/extendedlocation_test.go
  azure/converters/publicips.go
  azure/converters/publicips_test.go
  azure/interfaces.go
  azure/mock_azure/azure_mock.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/machine_test.go
  azure/scope/managedcontrolplane.go
  azure/services/agentpools/mock_agentpools/agentpools_mock.go
  azure/services/availabilitysets/mock_availabilitysets/availabilitysets_mock.go
  azure/services/bastionhosts/mocks_bastionhosts/bastionhosts_mock.go
  azure/services/disks/mock_disks/disks_mock.go
  azure/services/inboundnatrules/mock_inboundnatrules/inboundnatrules_mock.go
  azure/services/loadbalancers/mock_loadbalancers/loadbalancers_mock.go
  azure/services/loadbalancers/spec.go
  azure/services/natgateways/mock_natgateways/natgateways_mock.go
  azure/services/networkinterfaces/mock_networkinterfaces/networkinterfaces_mock.go
  azure/services/networkinterfaces/spec.go
  azure/services/privatedns/mock_privatedns/privatedns_mock.go
  azure/services/publicips/client.go
  azure/services/publicips/mock_publicips/publicips_mock.go
  azure/services/publicips/publicips.go
  azure/services/publicips/publicips_test.go
  azure/services/publicips/spec.go
  azure/services/publicips/spec_test.go
  azure/services/scalesets/mock_scalesets/scalesets_mock.go
  azure/services/scalesetvms/mock_scalesetvms/scalesetvms_mock.go
  azure/services/virtualmachines/virtualmachines.go
  azure/services/virtualnetworks/spec.go
  controllers/azuremachine_reconciler.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#3975 fix endless reconciliation on AKS system node labels
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm, area/managedclusters

#3989 [release-1.10] fix endless reconciliation on AKS system node labels
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm, area/managedclusters

#3950 update readme links
  README.md
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#3932 Implement UserAssignedMSI auth for ASO
  azure/scope/cluster.go
  azure/scope/identity.go
  azure/scope/identity_test.go
  azure/scope/managedcontrolplane.go
  azure/services/aso/aso_test.go
  azure/services/aso/interfaces.go
  azure/services/aso/mock_aso/aso_mock.go
  azure/services/aso/tags.go
  azure/services/aso/tags_test.go
  azure/services/asogroups/groups.go
  azure/services/asogroups/groups_test.go
  azure/services/asogroups/mock_asogroups/doc.go
  azure/services/asogroups/mock_asogroups/groups_mock.go
  azure/services/asogroups/spec.go
  azure/services/groups/client.go
  azure/services/groups/groups.go
  azure/services/groups/groups_test.go
  azure/services/groups/mock_groups/client_mock.go
  azure/services/groups/mock_groups/doc.go
  azure/services/groups/mock_groups/groups_mock.go
  azure/services/groups/spec.go
  azure/services/groups/spec_test.go
  controllers/asosecret_controller.go
  controllers/asosecret_controller_test.go
  controllers/azurecluster_reconciler.go
  controllers/azurecluster_reconciler_test.go
  controllers/azuremanagedcontrolplane_reconciler.go
  controllers/helpers.go
Labels: kind/feature, cncf-cla: yes, release-note-none, approved, size/XXL, lgtm

#3986 Convert scalesetvms service to SDKv2
  azure/converters/vmss.go
  azure/converters/vmss_test.go
  azure/services/scalesets/client.go
  azure/services/scalesets/mock_scalesets/client_mock.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesets/spec.go
  azure/services/scalesetvms/client.go
  azure/services/scalesetvms/mock_scalesetvms/client_mock.go
  azure/services/scalesetvms/scalesetvms.go
  azure/services/scalesetvms/scalesetvms_test.go
  controllers/azuremanagedmachinepool_controller_test.go
  controllers/azuremanagedmachinepool_reconciler.go
  controllers/nodelister_mock.go
  exp/controllers/azuremachinepoolmachine_controller.go
  exp/controllers/azuremachinepoolmachine_controller_test.go
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note-none, approved, lgtm

#3992 Convert various references to SDKv2
  azure/converters/subnets.go
  azure/converters/subnets_test.go
  azure/scope/machine.go
  azure/services/async/async_test.go
  azure/services/roleassignments/roleassignments.go
  azure/services/roleassignments/roleassignments_test.go
  azure/services/subnets/subnets.go
  azure/services/virtualnetworks/virtualnetworks.go
  exp/api/v1beta1/azuremachinepool_webhook.go
  exp/api/v1beta1/azuremachinepool_webhook_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3995 use ASO constants
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
  azure/services/groups/groups.go
  azure/services/groups/groups_test.go
  controllers/asosecret_controller.go
  controllers/azurecluster_reconciler_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3996 Convert virtualmachines service to SDKv2
  azure/converters/diagnostics.go
  azure/converters/diagnostics_test.go
  azure/converters/extendedlocation.go
  azure/converters/extendedlocation_test.go
  azure/converters/identity.go
  azure/converters/identity_test.go
  azure/converters/image.go
  azure/converters/image_test.go
  azure/converters/spotinstances.go
  azure/converters/spotinstances_test.go
  azure/converters/vm.go
  azure/converters/vm_test.go
  azure/services/roleassignments/roleassignments.go
  azure/services/roleassignments/roleassignments_test.go
  azure/services/scalesets/spec.go
  azure/services/scalesets/spec_test.go
  azure/services/scalesetvms/scalesetvms.go
  azure/services/virtualmachines/client.go
  azure/services/virtualmachines/mock_virtualmachines/client_mock.go
  azure/services/virtualmachines/spec.go
  azure/services/virtualmachines/spec_test.go
  azure/services/virtualmachines/virtualmachines.go
  azure/services/virtualmachines/virtualmachines_test.go
  controllers/azuremanagedmachinepool_controller_test.go
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm

#3977 Set cloud provider config to have shorter cache ttl
  hack/create-custom-cloud-provider-config.sh
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#3973 add oidcIssuerProfile to AzureManagedControlPlane
  api/v1beta1/azuremanagedcontrolplane_default.go
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/managedcontrolplane.go
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/managedclusters_test.go
  azure/services/managedclusters/mock_managedclusters/managedclusters_mock.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm, area/managedclusters

#4000 Rename "asyncpoller" package to "async"
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/client.go
  azure/services/async/async.go
  azure/services/async/async_test.go
  azure/services/async/interfaces.go
  azure/services/async/mock_async/async_mock.go
  azure/services/async/mock_async/doc.go
  azure/services/asyncpoller/asyncpoller.go
  azure/services/asyncpoller/asyncpoller_test.go
  azure/services/asyncpoller/interfaces.go
  azure/services/asyncpoller/mock_asyncpoller/asyncpoller_mock.go
  azure/services/asyncpoller/mock_asyncpoller/doc.go
  azure/services/availabilitysets/availabilitysets.go
  azure/services/bastionhosts/bastionhosts.go
  azure/services/bastionhosts/client.go
  azure/services/disks/client.go
  azure/services/disks/disks.go
  azure/services/inboundnatrules/client.go
  azure/services/inboundnatrules/inboundnatrules.go
  azure/services/loadbalancers/client.go
  azure/services/loadbalancers/loadbalancers.go
  azure/services/managedclusters/client.go
  azure/services/managedclusters/managedclusters.go
  azure/services/natgateways/client.go
  azure/services/natgateways/natgateways.go
  azure/services/networkinterfaces/client.go
  azure/services/networkinterfaces/networkinterfaces.go
  azure/services/privatedns/link_client.go
  azure/services/privatedns/privatedns.go
  azure/services/privatedns/zone_client.go
  azure/services/privateendpoints/client.go
  azure/services/privateendpoints/privateendpoints.go
  azure/services/publicips/client.go
  azure/services/publicips/publicips.go
  azure/services/roleassignments/roleassignments.go
  azure/services/routetables/client.go
  azure/services/routetables/routetables.go
  azure/services/scalesets/client.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesetvms/client.go
  azure/services/scalesetvms/scalesetvms.go
  azure/services/securitygroups/client.go
  azure/services/securitygroups/securitygroups.go
  azure/services/subnets/client.go
  azure/services/subnets/subnets.go
  azure/services/virtualmachines/client.go
  azure/services/virtualmachines/virtualmachines.go
  azure/services/virtualnetworks/client.go
  azure/services/virtualnetworks/virtualnetworks.go
  azure/services/vmextensions/client.go
  azure/services/vmextensions/vmextensions.go
  azure/services/vnetpeerings/client.go
  azure/services/vnetpeerings/vnetpeerings.go
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm

#3988 add spec.networkPluginMode to AzureManagedControlPlane
  api/v1beta1/azuremanagedcontrolplane_default.go
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/managedcontrolplane.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm, area/managedclusters

#4006 Update metadata.yaml for release 1.11
  metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4007 Update test metadata for 1.11 release
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4014 fix privateendpoints panic and diff
  azure/services/privateendpoints/spec.go
  azure/services/privateendpoints/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#4018 Arm64 should be upper cased and a const
  azure/defaults.go
  azure/defaults_test.go
Labels: cncf-cla: yes, size/XS, release-note, approved, lgtm

#4017 update Workload Identity doc for ASO
  docs/book/src/topics/workload-identity.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4023 generalize "if AKS" check in Tilt for custom flavors
  Tiltfile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4019 Fix nil pointer exception when deleting MachinePools
  azure/scope/machinepool.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#4026 Convert AKS e2e tests to SDKv2
  test/e2e/aks_autoscaler.go
  test/e2e/aks_node_labels.go
  test/e2e/aks_node_taints.go
  test/e2e/aks_public_ip_prefix.go
  test/e2e/aks_tags.go
  test/e2e/aks_upgrade.go
  test/e2e/aks_versions.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4028 update envtest k8s to 1.27
  Makefile
  controllers/suite_test.go
  exp/controllers/suite_test.go
  internal/test/env/env.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#4027 Fix "typeHandlerVersion is invalid" azure API error when using Arm64 machine pool
  azure/defaults.go
  azure/defaults_test.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#4011 delete LRO state when operations fail
  azure/services/async/async.go
  azure/services/async/async_test.go
Labels: kind/bug, cncf-cla: yes, kind/flake, size/M, release-note-none, approved, lgtm

#4042 [release-1.10] Update CAPI to v1.4.7
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4039 add transient error handling to AMMP delete
  controllers/azuremanagedmachinepool_controller.go
  controllers/azuremanagedmachinepool_controller_test.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, lgtm, area/managedclusters

#4041 Update CAPI to v1.5.2
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4048 [release-1.10] add transient error handling to AMMP delete
  controllers/azuremanagedmachinepool_controller.go
  controllers/azuremanagedmachinepool_controller_test.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, lgtm, area/managedclusters

#4045 Replace Paid SKU tier with Standard
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  docs/book/src/topics/managedcluster.md
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, lgtm

#4049 flatcar: Run kubeadm after containerd
  templates/cluster-template-flatcar.yaml
  templates/flavors/flatcar/machine-deployment.yaml
  templates/flavors/flatcar/patches/kubeadm-controlplane.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, lgtm

#4055 Update jaeger all-in-one chart to v0.1.11
  hack/observability/jaeger/chart/Chart.yaml
  hack/observability/jaeger/chart/templates/_helpers.tpl
  hack/observability/jaeger/chart/templates/ingress.yaml
  hack/observability/jaeger/chart/templates/jaeger-volume.yaml
  hack/observability/jaeger/chart/templates/service-headless.yaml
  hack/observability/jaeger/chart/templates/service.yaml
  hack/observability/jaeger/chart/templates/serviceaccount.yaml
  hack/observability/jaeger/chart/templates/statefulset.yaml
  hack/observability/jaeger/chart/templates/tests/test-connection.yaml
  hack/observability/jaeger/chart/values.yaml
  hack/observability/jaeger/fetch-jaeger-resources.sh
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4051 Update CAPZ roadmap
  docs/book/src/roadmap.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#3997 use generics for ASO services
  azure/interfaces.go
  azure/mock_azure/azure_mock.go
  azure/scope/cluster.go
  azure/scope/managedcontrolplane.go
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
  azure/services/aso/interfaces.go
  azure/services/aso/mock_aso/aso_mock.go
  azure/services/aso/service.go
  azure/services/aso/service_test.go
  azure/services/aso/tags.go
  azure/services/aso/tags_test.go
  azure/services/groups/groups.go
  azure/services/groups/groups_test.go
  azure/services/groups/mock_groups/groups_mock.go
  azure/services/groups/spec.go
  azure/services/groups/spec_test.go
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm
