Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2023-06, with the labels that each got.

#3601 [release-1.9] Pin Calico to v3.25.1
  Makefile
  Tiltfile
  docs/book/src/topics/addons.md
  scripts/ci-e2e.sh
  scripts/ci-entrypoint.sh
  templates/addons/calico-dual-stack.yaml
  templates/addons/calico-ipv6.yaml
  templates/addons/calico-ipv6/calico-policy-only.yaml
  templates/addons/calico.yaml
  templates/addons/calico/calico-vxlan.yaml
  templates/addons/windows/calico/calico.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider-machine-pool.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/cloud-provider-azure.go
  test/e2e/cni.go
  test/e2e/common.go
  test/e2e/gpu_operator.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm, kind/failing-test

#3602 [release-1.8] Pin Calico to v3.25.1
  Makefile
  Tiltfile
  docs/book/src/topics/addons.md
  scripts/ci-e2e.sh
  scripts/ci-entrypoint.sh
  templates/addons/calico-dual-stack.yaml
  templates/addons/calico-ipv6.yaml
  templates/addons/calico-ipv6/calico-policy-only.yaml
  templates/addons/calico.yaml
  templates/addons/calico/calico-vxlan.yaml
  templates/addons/windows/calico/calico.yaml
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider-machine-pool.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/cloud-provider-azure.go
  test/e2e/cni.go
  test/e2e/common.go
  test/e2e/gpu_operator.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm, kind/failing-test

#3574 add asogroups
  .golangci.yml
  azure/scope/cluster.go
  azure/scope/managedcontrolplane.go
  azure/services/asogroups/groups.go
  azure/services/asogroups/groups_test.go
  azure/services/asogroups/mock_asogroups/doc.go
  azure/services/asogroups/mock_asogroups/groups_mock.go
  azure/services/asogroups/spec.go
  azure/services/asogroups/spec_test.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#3606 Revert "Update virtualmachineimages service to SDK v2"
  azure/defaults.go
  azure/defaults_test.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/services/virtualmachineimages/cache.go
  azure/services/virtualmachineimages/cache_test.go
  azure/services/virtualmachineimages/client.go
  azure/services/virtualmachineimages/images.go
  azure/services/virtualmachineimages/images_test.go
  azure/services/virtualmachineimages/mock_virtualmachineimages/client_mock.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, kind/failing-test

#3596 Improve api server LB probe
  azure/services/loadbalancers/loadbalancers.go
  azure/services/loadbalancers/spec.go
  azure/services/loadbalancers/spec_test.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, ok-to-test, lgtm

#3484 add unit tests for azuremachinetemplate_webhook ValidateCreate
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/azuremachinetemplate_webhook_test.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, ok-to-test, lgtm

#3265 Add support for confidential VMs
  api/v1beta1/azuremachine_validation.go
  api/v1beta1/azuremachine_validation_test.go
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/services/resourceskus/sku.go
  azure/services/virtualmachines/spec.go
  azure/services/virtualmachines/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  docs/book/src/SUMMARY.md
  docs/book/src/topics/confidential-vms.md
  docs/book/src/topics/trusted-launch-for-vms.md
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#3617 vendor and sanitize ASO CRDs
  Makefile
  config/aso/crds.yaml
  config/aso/kustomization.yaml
Labels: kind/bug, cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#3623 Fix e2e config gob conversion to string
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3625 Apply codecov config to patch
  .github/codecov.yml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3616 Allow azure:// prefix when parsing resource IDs
  azure/defaults.go
  azure/defaults_test.go
  azure/scope/machinepool.go
  azure/services/identities/client.go
  azure/services/natgateways/spec.go
  azure/services/scalesetvms/scalesetvms.go
  azure/services/virtualmachines/client.go
  test/e2e/azure_edgezone.go
  test/e2e/azure_logcollector.go
  test/e2e/azure_privatecluster.go
  test/e2e/azure_vmextensions.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#3587 Refactor and add missing test coverage for validateclustertemplatespec
  api/v1beta1/azureclustertemplate_validation.go
  api/v1beta1/azureclustertemplate_validation_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, ok-to-test, lgtm

#3628 fix codespell highlighted error
  controllers/azureidentity_controller.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3612 Update CAPI to v1.4.3
  Makefile
  Tiltfile
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, lgtm

#3608 add BYO ASO resource
  api/v1beta1/consts.go
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
  azure/services/asogroups/groups.go
  azure/services/asogroups/groups_test.go
  azure/services/asogroups/mock_asogroups/groups_mock.go
  util/maps/maps.go
  util/maps/maps_test.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#3636 Temporarily disable useHostProcessContainers
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3618 Validate providerID for user-assigned IDs in webhook
  api/v1beta1/azuremachine_validation.go
  api/v1beta1/azuremachine_validation_test.go
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/azuremachinetemplate_webhook_test.go
  azure/converters/identity.go
  azure/defaults.go
  azure/defaults_test.go
  azure/scope/machine.go
  azure/scope/machinepool.go
  azure/services/identities/client.go
  azure/services/natgateways/spec.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesetvms/scalesetvms.go
  azure/services/virtualmachines/client.go
  azure/services/virtualmachines/virtualmachines.go
  azure/types.go
  controllers/azuremanagedmachinepool_reconciler.go
  exp/api/v1beta1/azuremachinepool_webhook_test.go
  test/e2e/azure_edgezone.go
  test/e2e/azure_logcollector.go
  test/e2e/azure_privatecluster.go
  test/e2e/azure_vmextensions.go
  util/azure/azure.go
  util/azure/azure_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#3508 add azure cni e2e tests with one NIC per linux node
  Makefile
  templates/addons/azure-cni-v1.yaml
  templates/addons/azure-cni-v1/kustomization.yaml
  templates/cluster-template-azure-cni-v1.yaml
  templates/flavors/azure-cni-v1/kustomization.yaml
  templates/flavors/azure-cni-v1/patches/azure-machine-template-controlplane.yaml
  templates/flavors/azure-cni-v1/patches/azure-machine-template.yaml
  templates/flavors/azure-cni-v1/patches/kubeadm-control-plane.yaml
  templates/flavors/azure-cni-v1/patches/kubeadm-worker-node.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/prow-azure-cni-v1/kustomization.yaml
  test/e2e/azure_test.go
  test/e2e/cloud-provider-azure.go
  test/e2e/cni.go
  test/e2e/common.go
  test/e2e/config/azure-dev.yaml
Labels: kind/feature, cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#3631 [release-1.9] Update CAPI to v1.4.3
  Makefile
  Tiltfile
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, lgtm

#3647 Use && to run clean-release-git after test-e2e
  Makefile
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3639 Fix managed clusters and agent pools diffs
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#3657 Increase AKS reconcile timeout
  azure/services/managedclusters/managedclusters.go
  util/reconciler/defaults.go
Labels: cncf-cla: yes, size/XS, release-note, approved, lgtm, kind/failing-test

#3633 add BYO Azure resource with ASO
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3425 feat: AKS user-assigned identity for control plane and kubelet
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/managedcontrolplane.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm
