Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2023-08, with the labels that each got.

#3759 Adding EnableFIPS flag in ManageMachinePool struct
  api/v1beta1/azuremanagedmachinepool_types.go
  api/v1beta1/azuremanagedmachinepool_webhook.go
  api/v1beta1/azuremanagedmachinepool_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/converters/managedagentpool.go
  azure/converters/managedagentpool_test.go
  azure/scope/managedmachinepool.go
  azure/services/agentpools/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#3784 [release-1.9] Bump CAPI to v1.4.5
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#3786 Fix codecov missing token error
  .github/workflows/cover.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3653 fix AuthorizedIPRanges disable -> enable bug
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#3797 Remove unused multi-tenancy creds
  hack/parse-prow-creds.sh
  test/e2e/common.go
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3803 Upgrading otel and related packages
  go.mod
  go.sum
  pkg/ot/metrics.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, ok-to-test, lgtm

#3783 add pause handling for AzureManagedControlPlane
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_controller_test.go
  controllers/azuremanagedcontrolplane_reconciler.go
  controllers/azuremanagedcontrolplane_reconciler_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#3788 add ASO pause logic
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
  azure/services/asogroups/groups.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#3624 Add proposal for Node OS image caching
  docs/proposals/20230612-node-os-image-caching.md
  docs/proposals/images/node-os-image-cache.plantuml
  docs/proposals/images/node-os-image-cache.png
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#3812 Update error funcs for SDKv2
  azure/errors.go
  azure/errors_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3809 fix Cluster -> AzureManagedMachinePool mapper
  controllers/azuremanagedmachinepool_controller.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#3698 Add support for Azure authentication in ASO
  azure/scope/identity.go
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
  controllers/asosecret_controller.go
  controllers/asosecret_controller_test.go
  controllers/helpers.go
  main.go
  util/aso/defaults.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, ok-to-test, lgtm

#3811 add `controller: true` to azure.json Secret ownerRef
  controllers/azurejson_machine_controller.go
  controllers/azurejson_machinepool_controller.go
  controllers/azurejson_machinetemplate_controller.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#3805 [release-1.10] fix AuthorizedIPRanges disable -> enable bug
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#3807 [release-1.9] fix AuthorizedIPRanges disable -> enable bug
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#3820 [release-1.10] Upgrading otel and related packages
  go.mod
  go.sum
  pkg/ot/metrics.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3821 [release-1.9] Upgrading otel and related packages
  go.mod
  go.sum
  pkg/ot/metrics.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3724 Run local verifying targets too before git commit
  .pre-commit-config.yaml
  docs/book/src/developers/development.md
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#3814 Add future conversion funcs for SDKv2
  azure/converters/futures.go
  azure/converters/futures_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#3808 add pause handling for AzureMachine, AzureManagedMachinePool, AzureMachinePool
  controllers/azuremachine_controller.go
  controllers/azuremachine_controller_test.go
  controllers/azuremachine_reconciler.go
  controllers/azuremachine_reconciler_test.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedmachinepool_controller.go
  controllers/azuremanagedmachinepool_controller_test.go
  controllers/azuremanagedmachinepool_reconciler.go
  controllers/azuremanagedmachinepool_reconciler_test.go
  controllers/helpers.go
  controllers/helpers_test.go
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/azuremachinepool_controller_test.go
  exp/controllers/azuremachinepool_reconciler.go
  exp/controllers/azuremachinepool_reconciler_test.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#3826 validate DNS Service IP to be a .10 IP belonging to Service CIDR
  api/v1beta1/azuremachine_default_test.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#3827 Remove old comment and log line from zone_reconciler.go
  azure/services/privatedns/zone_reconciler.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, ok-to-test, lgtm

#3793 Require AzureClusterIdentity for auth
  api/v1beta1/azurecluster_default_test.go
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/azurecluster_validation_test.go
  config/capz/credentials.yaml
  config/capz/kustomization.yaml
  config/capz/manager_credentials_patch.yaml
  controllers/asosecret_controller.go
  controllers/asosecret_controller_test.go
  controllers/helpers.go
  docs/book/src/developers/development.md
  docs/book/src/topics/getting-started.md
  docs/book/src/topics/identities-use-cases.md
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, lgtm

#3813 Add ARM client options func for SDKv2
  azure/defaults.go
  azure/defaults_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#3841 [release-1.10] improve dns service ip validation
  api/v1beta1/azuremachine_default_test.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#3767 Update e2e test versions of k8s to 1.26/1.27
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3828 remove userAssignedIdenties client ID lookup code for CCM
  controllers/azurejson_machine_controller.go
  controllers/azurejson_machinepool_controller.go
  controllers/azurejson_machinetemplate_controller.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, ok-to-test, lgtm

#3849 make dependabot avoid updating golang in Dockerfile
  .github/dependabot.yml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3848 Bump controller-runtime to v0.15.1
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3850 Bump CAPI visualizer to v1.2.0
  Tiltfile
  hack/observability/cluster-api-visualizer/chart/Chart.yaml
  hack/observability/cluster-api-visualizer/chart/templates/deployment.yaml
  hack/observability/cluster-api-visualizer/chart/values.yaml
  hack/observability/cluster-api-visualizer/fetch-visualizer-resources.sh
Labels: kind/feature, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#3111 Make scaleset reconcile/delete async
  azure/converters/vmss.go
  azure/converters/vmss_test.go
  azure/scope/machinepool.go
  azure/services/roleassignments/roleassignments.go
  azure/services/roleassignments/roleassignments_test.go
  azure/services/scalesets/client.go
  azure/services/scalesets/mock_scalesets/client_mock.go
  azure/services/scalesets/mock_scalesets/scalesets_mock.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesets/spec.go
  azure/services/scalesets/spec_test.go
  azure/services/scalesets/vmssextension_spec_test.go
  exp/controllers/azuremachinepool_controller.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#3851 Allow authentication with Azure Workload Identity for ASO
  controllers/asosecret_controller.go
  controllers/asosecret_controller_test.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, ok-to-test, lgtm

#3831 chore(make): ignoring gcloud project name for local builds
  Makefile
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#3847 Adding HTTP Proxy support for managed cluster
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/managedcontrolplane.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#3864 Update script to support OOT credential provider
  scripts/ci-build-azure-ccm.sh
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3843 Update virtualmachineimages service to SDK v2
  azure/interfaces.go
  azure/mock_azure/azure_mock.go
  azure/scope/clients.go
  azure/scope/cluster.go
  azure/scope/identity.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/services/agentpools/mock_agentpools/agentpools_mock.go
  azure/services/availabilitysets/mock_availabilitysets/availabilitysets_mock.go
  azure/services/bastionhosts/mocks_bastionhosts/bastionhosts_mock.go
  azure/services/disks/mock_disks/disks_mock.go
  azure/services/groups/mock_groups/groups_mock.go
  azure/services/inboundnatrules/mock_inboundnatrules/inboundnatrules_mock.go
  azure/services/loadbalancers/mock_loadbalancers/loadbalancers_mock.go
  azure/services/managedclusters/mock_managedclusters/managedclusters_mock.go
  azure/services/natgateways/mock_natgateways/natgateways_mock.go
  azure/services/networkinterfaces/mock_networkinterfaces/networkinterfaces_mock.go
  azure/services/privatedns/mock_privatedns/privatedns_mock.go
  azure/services/privateendpoints/mock_privateendpoints/privateendpoints_mock.go
  azure/services/publicips/mock_publicips/publicips_mock.go
  azure/services/resourcehealth/mock_resourcehealth/resourcehealth_mock.go
  azure/services/roleassignments/mock_roleassignments/roleassignments_mock.go
  azure/services/routetables/mock_routetables/routetables_mock.go
  azure/services/scalesets/mock_scalesets/scalesets_mock.go
  azure/services/scalesetvms/mock_scalesetvms/scalesetvms_mock.go
  azure/services/securitygroups/mock_securitygroups/securitygroups_mock.go
  azure/services/subnets/mock_subnets/subnets_mock.go
  azure/services/tags/mock_tags/tags_mock.go
  azure/services/virtualmachineimages/cache.go
  azure/services/virtualmachineimages/cache_test.go
  azure/services/virtualmachineimages/client.go
  azure/services/virtualmachineimages/images.go
  azure/services/virtualmachineimages/images_test.go
  azure/services/virtualmachineimages/mock_virtualmachineimages/client_mock.go
  azure/services/virtualmachines/mock_virtualmachines/virtualmachines_mock.go
  azure/services/virtualnetworks/mock_virtualnetworks/virtualnetworks_mock.go
  azure/services/vmextensions/mock_vmextensions/vmextensions_mock.go
  azure/services/vnetpeerings/mock_vnetpeerings/vnetpeerings_mock.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note, approved, lgtm

#3829 🚨 Azureutil alias rule added and respective fixed lint issues
  .golangci.yml
  exp/api/v1beta1/azuremachinepool_webhook.go
  test/e2e/azure_machinepools.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, ok-to-test, lgtm

#3872 Remove control-plane-azure-json before creation
  hack/create-custom-cloud-provider-config.sh
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#3858 Convert natgateways service to SDKv2
  azure/services/asyncpoller/asyncpoller.go
  azure/services/asyncpoller/asyncpoller_test.go
  azure/services/asyncpoller/interfaces.go
  azure/services/asyncpoller/mock_asyncpoller/asyncpoller_mock.go
  azure/services/asyncpoller/mock_asyncpoller/doc.go
  azure/services/natgateways/client.go
  azure/services/natgateways/natgateways.go
  azure/services/natgateways/natgateways_test.go
  azure/services/natgateways/spec.go
  controllers/azurecluster_reconciler.go
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm

#3876 Update shellcheck to v0.9.0
  hack/verify-shellcheck.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3887 Fix a natgateways return value
  azure/services/natgateways/client.go
  azure/services/virtualmachineimages/client.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#3901 fix MachinePool rolling upgrade
  azure/scope/machinepool.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3723 Enable ASO
  Tiltfile
  azure/scope/cluster.go
  azure/scope/managedcontrolplane.go
  azure/services/asogroups/groups.go
  azure/services/asogroups/groups_test.go
  config/aso/credentials.yaml
  config/default/kustomization.yaml
  config/rbac/role.yaml
  controllers/azurecluster_controller.go
  controllers/azurecluster_controller_test.go
  controllers/azurecluster_reconciler.go
  controllers/azurecluster_reconciler_test.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_controller_test.go
  controllers/azuremanagedcontrolplane_reconciler.go
  controllers/helpers.go
  docs/book/src/SUMMARY.md
  docs/book/src/topics/aso.md
  hack/observability/prometheus/resources/prometheus.yaml
  main.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, lgtm

#3908 Update CAPI to v1.5.1
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#3902 added doc.go file
  controllers/doc.go
  controllers/nodelister_mock.go
Labels: kind/bug, cncf-cla: yes, size/S, tide/merge-method-squash, release-note-none, approved, ok-to-test, lgtm

#3857 Convert managedclusters service to SDKv2
  api/v1beta1/azuremanagedmachinepool_webhook_test.go
  azure/converters/managedagentpool.go
  azure/converters/managedagentpool_test.go
  azure/defaults.go
  azure/defaults_test.go
  azure/pointers.go
  azure/pointers_test.go
  azure/scope/managedmachinepool_test.go
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/client.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/managedclusters/client.go
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/managedclusters_test.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_reconciler.go
  controllers/azuremanagedmachinepool_controller.go
  controllers/azuremanagedmachinepool_reconciler.go
  go.mod
  go.sum
  test/e2e/aks_azure_cluster_autoscaler.go
  test/e2e/aks_public_ip_prefix.go
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm

#3915 [release-1.9] Update CAPI to v1.4.6
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#3912 fix spurious ASO secret controller errors
  controllers/asosecret_controller.go
  controllers/asosecret_controller_test.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#3914 Convert disks service to SDKv2
  azure/services/disks/client.go
  azure/services/disks/disks.go
  controllers/azuremachine_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#3906 Convert bastionhosts service to SDKv2
  azure/services/bastionhosts/bastionhosts.go
  azure/services/bastionhosts/client.go
  azure/services/bastionhosts/spec.go
  controllers/azurecluster_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3911 fix tilt for non-kind clusters
  Tiltfile
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3916 bump github.com/azure-sdk-for-go/sdk/resource/containerservice/armcontainerservice/v4 from 4.1.0 to 4.2.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3894 Convert vmextensions service to SDKv2
  azure/services/vmextensions/client.go
  azure/services/vmextensions/spec.go
  azure/services/vmextensions/spec_test.go
  azure/services/vmextensions/vmextensions.go
  controllers/azuremachine_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3882 Convert inboundnatrules service to SDKv2
  azure/services/inboundnatrules/client.go
  azure/services/inboundnatrules/inboundnatrules.go
  azure/services/inboundnatrules/inboundnatrules_test.go
  azure/services/inboundnatrules/mock_inboundnatrules/client_mock.go
  azure/services/inboundnatrules/spec.go
  azure/services/inboundnatrules/spec_test.go
  controllers/azuremachine_reconciler.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3878 enable users to `allow` or `deny` the security rules
  api/v1beta1/azurecluster_default_test.go
  api/v1beta1/types.go
  azure/converters/rules.go
  azure/scope/cluster.go
  azure/services/securitygroups/securitygroups_test.go
  azure/services/securitygroups/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclustertemplates.yaml
  docs/book/src/topics/custom-vnet.md
  test/e2e/azure_securitygroups.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm
