Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2023-07, with the labels that each got.

#3682 persist AKS kubelet user-assigned identity in spec
  azure/scope/managedcontrolplane.go
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/managedclusters_test.go
  azure/services/managedclusters/mock_managedclusters/managedclusters_mock.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3591 Delete security rules if removed from spec
  azure/const.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/services/securitygroups/mock_securitygroups/securitygroups_mock.go
  azure/services/securitygroups/securitygroups.go
  azure/services/securitygroups/securitygroups_test.go
  azure/services/securitygroups/spec.go
  azure/services/securitygroups/spec_test.go
  test/e2e/azure_securitygroups.go
  test/e2e/azure_test.go
  test/e2e/config/azure-dev.yaml
Labels: kind/bug, cncf-cla: yes, size/XL, release-note, approved, lgtm

#3662 make ASO adopt previously managed resources
  azure/interfaces.go
  azure/mock_azure/azure_mock.go
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
  azure/services/asogroups/spec.go
  azure/services/asogroups/spec_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#3676 Fix custom backendPool not being used
  azure/interfaces.go
  azure/mock_azure/azure_mock.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/services/bastionhosts/mocks_bastionhosts/bastionhosts_mock.go
  azure/services/loadbalancers/mock_loadbalancers/loadbalancers_mock.go
  azure/services/natgateways/mock_natgateways/natgateways_mock.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#3686 renaming cleanup function in ci-build-azure-ccm.sh and ci-build-kubernetes.sh
  hack/verify-starlark.sh
  scripts/ci-build-azure-ccm.sh
  scripts/ci-build-kubernetes.sh
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#3674 Update CAPI to v1.4.4
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  scripts/kind-with-registry.sh
  test/e2e/config/azure-dev.yaml
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, lgtm

#3583 (feat): add workload identity in capz
  Makefile
  api/v1beta1/azureclusteridentity_webhook.go
  api/v1beta1/azureclusteridentity_webhook_test.go
  api/v1beta1/types.go
  azure/scope/identity.go
  azure/scope/workload_identity.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
  config/manager/manager.yaml
  config/rbac/service_account.yaml
  scripts/kind-with-registry.sh
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/patches/azureclusteridentity-azwi.yaml
  templates/test/ci/prow-workload-identity/kustomization.yaml
  test/e2e/azure_test.go
  test/e2e/config/azure-dev.yaml
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, size/XL, release-note, approved, lgtm

#3609 update tiltfile to support azure cni dev
  Tiltfile
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, lifecycle/active, lgtm

#3646 Revert "Temporarily disable useHostProcessContainers"
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3699 fix Cluster to AzureManagedControlPlane mapper
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_controller_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3710 allow AZWI opt-out for e2e tests
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note, approved, lgtm

#3700 Don't default NAT Gateway for existing node subnet
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azurecluster_default_test.go
  azure/services/subnets/spec.go
  azure/services/subnets/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#3702 Update Azure documentation links
  README.md
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/azuremachine_types.go
  api/v1beta1/types.go
  azure/defaults.go
  azure/services/loadbalancers/spec.go
  azure/services/managedclusters/spec.go
  azure/services/virtualmachineimages/client.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  docs/book/src/developers/development.md
  docs/book/src/topics/api-server-endpoint.md
  docs/book/src/topics/confidential-vms.md
  docs/book/src/topics/custom-images.md
  docs/book/src/topics/custom-vnet.md
  docs/book/src/topics/data-disks.md
  docs/book/src/topics/failure-domains.md
  docs/book/src/topics/getting-started.md
  docs/book/src/topics/identities-use-cases.md
  docs/book/src/topics/machinepools.md
  docs/book/src/topics/multitenancy.md
  docs/book/src/topics/node-outbound-connection.md
  docs/book/src/topics/os-disk.md
  docs/book/src/topics/publicmec-clusters.md
  docs/book/src/topics/spot-vms.md
  docs/book/src/topics/ssh-access.md
  docs/book/src/topics/troubleshooting.md
  docs/book/src/topics/vm-diagnostics.md
  docs/book/src/topics/vm-identity.md
  docs/proposals/20201214-bootstrap-failure-detection.md
  docs/proposals/20210222-azure-machinepool-machine.md
  exp/api/v1beta1/azuremachinepool_types.go
  hack/observability/readme.md
Labels: cncf-cla: yes, size/L, release-note-none, approved, kind/documentation, lgtm

#3713 Update metadata.yaml for release 1.10
  metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3627 add docs on using Azure cni v1 using single NIC per node
  docs/book/src/topics/addons.md
Labels: cncf-cla: yes, size/L, release-note, approved, kind/documentation, lgtm

#3714 Update test metadata for 1.10 release
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3717 fix `make kind-create` default for AZWI
  Makefile
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3726 Corrected a language error in the documentation
  docs/book/src/developers/development.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#3706 Update security configs
  .github/dependabot.yml
  docs/book/src/developers/development.md
Labels: kind/feature, cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#3734 [release-1.9] ensure codecov does not block PRs
  .github/codecov.yml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3672 Allow setting ScaleDownMode and SpotMaxPrice for AzureManagedMachinePool
  api/v1beta1/azuremanagedmachinepool_types.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/converters/managedagentpool.go
  azure/scope/managedmachinepool.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  test/e2e/aks_spot.go
  test/e2e/azure_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#3630 add makefile targets to install codespell and verify using codespell
  .github/workflows/codespell.yml
  Makefile
  docs/book/src/developers/development.md
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#3677 Allow skipping Linux profile on managed clusters
  api/v1beta1/azuremanagedcontrolplane_default.go
  api/v1beta1/azuremanagedcontrolplane_default_test.go
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/managedcontrolplane.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#3729 added priorityClassName for capz-nmi
  config/capz/aad-pod-identity-deployment.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, release-note, approved, ok-to-test, lgtm

#3731 move devigned (justice) to emeritus
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3728 Updated wasm docs to include wasm workers server
  docs/book/src/topics/multitenancy.md
  docs/book/src/topics/wasi.md
Labels: cncf-cla: yes, size/M, release-note, approved, kind/documentation, ok-to-test, lgtm

#3742 List WorkloadIdentity as one of available IdentityTypes
  api/v1beta1/azureclusteridentity_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#3715 [release-1.9] Update Azure documentation links
  README.md
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/azuremachine_types.go
  api/v1beta1/types.go
  azure/defaults.go
  azure/services/loadbalancers/spec.go
  azure/services/managedclusters/spec.go
  azure/services/virtualmachineimages/client.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  docs/book/src/developers/development.md
  docs/book/src/topics/api-server-endpoint.md
  docs/book/src/topics/custom-images.md
  docs/book/src/topics/custom-vnet.md
  docs/book/src/topics/data-disks.md
  docs/book/src/topics/failure-domains.md
  docs/book/src/topics/getting-started.md
  docs/book/src/topics/identities-use-cases.md
  docs/book/src/topics/machinepools.md
  docs/book/src/topics/multitenancy.md
  docs/book/src/topics/node-outbound-connection.md
  docs/book/src/topics/os-disk.md
  docs/book/src/topics/publicmec-clusters.md
  docs/book/src/topics/spot-vms.md
  docs/book/src/topics/ssh-access.md
  docs/book/src/topics/troubleshooting.md
  docs/book/src/topics/vm-diagnostics.md
  docs/book/src/topics/vm-identity.md
  docs/proposals/20201214-bootstrap-failure-detection.md
  docs/proposals/20210222-azure-machinepool-machine.md
  exp/api/v1beta1/azuremachinepool_types.go
  hack/observability/readme.md
Labels: cncf-cla: yes, size/L, release-note-none, approved, kind/documentation, lgtm

#3746 Document using a Mariner Linux custom image
  docs/book/src/topics/custom-images.md
Labels: cncf-cla: yes, size/M, release-note, approved, kind/documentation, lgtm

#3739 Add nojnhuh to maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3740 Add sonasingh46 to maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3762 Pin k8s e2e version to v1.25.11
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3761 add machine pool wait to default e2e parameters
  test/e2e/common.go
Labels: cncf-cla: yes, size/XS, kind/flake, release-note-none, approved, lgtm

#3766 fix bug preventing AKS autoscaling from being disabled
  azure/scope/managedmachinepool.go
  azure/scope/managedmachinepool_test.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/managedclusters/spec_test.go
  controllers/azuremanagedmachinepool_controller_test.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#3735 add pause handling for AzureCluster controller
  azure/interfaces.go
  azure/mock_azure/azure_mock.go
  controllers/azurecluster_controller.go
  controllers/azurecluster_controller_test.go
  controllers/azurecluster_reconciler.go
  controllers/azurecluster_reconciler_test.go
  controllers/helpers.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#3777 [release-1.10] update project maintainers
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3778 [release-1.9] update project maintainers
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3741 Add ARM64 support for CAPZ Bootstrapping Extension
  azure/defaults.go
  azure/defaults_test.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/services/resourceskus/sku.go
  exp/controllers/azuremachinepool_controller.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#3757 Use Helm binary in e2e tests to avoid import
  Makefile
  go.mod
  go.sum
  test/e2e/cloud-provider-azure.go
  test/e2e/cni.go
  test/e2e/gpu_operator.go
  test/e2e/helm.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3769 [release-1.9] add machine pool wait to default e2e parameters
  test/e2e/common.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3756 Bump CAPI to v1.4.5
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#3733 refactor ASO label/annotation updates
  azure/services/aso/aso.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm
