Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2023-02, with the labels that each got.

#3100 use g.Expect when assertions are clearest
  test/e2e/aks_public_ip_prefix.go
  test/e2e/aks_upgrade.go
  test/e2e/azure_failuredomains.go
  test/e2e/azure_gpu.go
  test/e2e/azure_lb.go
  test/e2e/azure_machinepool_drain.go
  test/e2e/helpers.go
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/namespace/namespace.go
  test/e2e/kubernetes/networkpolicy/networkpolicy.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/pvc/pvc.go
  test/e2e/kubernetes/storageclass/storageclass.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3130 missing context wrapping
  azure/scope/machinepool.go
  controllers/azurecluster_controller.go
  controllers/azureidentity_controller.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3080 Retry VMSS Flex validation if no parent MP is found
  exp/api/v1beta1/azuremachinepool_webhook.go
  exp/api/v1beta1/azuremachinepool_webhook_test.go
  util/azure/azure.go
  util/azure/azure_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#3138 Fix wrong LB idletimeout for node outbound
  azure/scope/cluster.go
  azure/scope/cluster_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#3139 Bump cert-manager to v1.11.0
  Tiltfile
  hack/install-cert-manager.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note, approved, lgtm

#3096 Don't delete VMSS upon failure and add bootstrap status condition
  azure/converters/vmss.go
  azure/defaults.go
  azure/scope/machinepoolmachine.go
  azure/types.go
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/azuremachinepoolmachine_controller.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, ok-to-test, lgtm

#3141 [release-1.6] Bump CAPI to v1.2.10
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#3059 use outboundlb name as the lb name in cloud config
  controllers/helpers.go
  controllers/helpers_test.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#3116 Update roadmap
  docs/book/src/developers/releasing.md
  docs/book/src/roadmap.md
Labels: cncf-cla: yes, size/M, release-note, approved, kind/documentation, ok-to-test, lgtm

#3144 [release-1.7] Bump cert-manager to v1.11.0
  Tiltfile
  hack/install-cert-manager.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note, approved, lgtm

#3143 [release-1.6] Bump cert-manager to v1.11.0
  Tiltfile
  hack/install-cert-manager.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note, approved, lgtm

#3154 [release-1.6]use outboundlb name as the lb name in cloud config
  controllers/helpers.go
  controllers/helpers_test.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#3148 overcome transient errors in ci-entrypoint.sh
  Makefile
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, kind/flake, size/L, release-note-none, approved, lgtm

#3155 [release-1.7] overcome transient errors in ci-entrypoint.sh
  Makefile
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, kind/flake, size/L, release-note-none, approved, lgtm

#3153 Add 30s timeout to test helper SSH config
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3158 [release-1.6] Add 30s timeout to test helper SSH config
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3157 [release-1.7] Add 30s timeout to test helper SSH config
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3156 Fetch Calico Helm chart from new URL
  Tiltfile
  docs/book/src/topics/addons.md
  scripts/ci-entrypoint.sh
  test/e2e/cni.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#3142 Bump Windows Calico to v3.25.0
  .codespellignore
  Makefile
  templates/addons/calico-dual-stack.yaml
  templates/addons/calico-ipv6.yaml
  templates/addons/calico-ipv6/calico-policy-only.yaml
  templates/addons/calico.yaml
  templates/addons/calico/calico-vxlan.yaml
  templates/addons/windows/calico/calico.yaml
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note, approved, lgtm

#3159 [release-1.7] Fetch Calico Helm chart from new URL
  Tiltfile
  docs/book/src/topics/addons.md
  scripts/ci-entrypoint.sh
  test/e2e/cni.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#3136 bump CAPI to v1.3.3
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#3003 Refactor repeated code in E2E test specs to helper functions
  test/e2e/azure_privatecluster.go
  test/e2e/azure_selfhosted.go
  test/e2e/azure_test.go
  test/e2e/common.go
  test/e2e/conformance_test.go
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note-none, approved, lgtm

#3164 [release-1.7] bump CAPI to v1.3.3
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#3117 Updated the version of metrics-server to v0.6.2
  templates/addons/metrics-server/kustomization.yaml
  templates/addons/metrics-server/metrics-server.yaml
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#3165 Skip test pending fix for VMSS Flex API changes
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#3169 Fix unbound CIDR1 in ci-entrypoint when testing CCM
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#2973 feat: add linux OS custom configuration
  api/v1alpha3/azuremanagedmachinepool_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/azuremanagedmachinepool_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/azuremanagedmachinepool_types.go
  api/v1beta1/azuremanagedmachinepool_webhook.go
  api/v1beta1/azuremanagedmachinepool_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/converters/managedagentpool.go
  azure/scope/managedmachinepool.go
  azure/services/agentpools/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  controllers/helpers_test.go
  docs/book/src/topics/managedcluster.md
  templates/test/ci/cluster-template-prow-aks.yaml
  templates/test/ci/prow-aks/patches/aks-pool1.yaml
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#3176 Fix Windows external CI version template to use OOT
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/prow-external-cloud-provider-ci-version/kustomization.yaml
  templates/test/ci/prow-external-cloud-provider-ci-version/patches/external-cloud-provider-windows.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#3044 Add support for private endpoints
  api/v1alpha3/azurecluster_conversion.go
  api/v1alpha3/azuremanagedcontrolplane_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/azurecluster_conversion.go
  api/v1alpha4/azuremanagedcontrolplane_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/consts.go
  api/v1beta1/types.go
  api/v1beta1/types_class.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/cluster.go
  azure/scope/managedcontrolplane.go
  azure/services/privateendpoints/client.go
  azure/services/privateendpoints/mock_privateendpoints/client_mock.go
  azure/services/privateendpoints/mock_privateendpoints/doc.go
  azure/services/privateendpoints/mock_privateendpoints/privateendpoints_mock.go
  azure/services/privateendpoints/privateendpoints.go
  azure/services/privateendpoints/privateendpoints_test.go
  azure/services/privateendpoints/spec.go
  azure/services/privateendpoints/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  controllers/azurecluster_reconciler.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_reconciler.go
  docs/book/src/topics/custom-vnet.md
Labels: kind/feature, cncf-cla: yes, release-note, approved, lifecycle/active, size/XXL, ok-to-test, lgtm

#2965 Allow for configurable scope in system assigned identities
  api/v1alpha3/azuremachine_conversion.go
  api/v1alpha3/azuremachinetemplate_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/azuremachine_conversion.go
  api/v1alpha4/azuremachinetemplate_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/azuremachine_default.go
  api/v1beta1/azuremachine_default_test.go
  api/v1beta1/azuremachine_types.go
  api/v1beta1/azuremachine_validation.go
  api/v1beta1/azuremachine_validation_test.go
  api/v1beta1/azuremachine_webhook.go
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/azuremachinetemplate_webhook.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/defaults.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  docs/book/src/topics/vm-identity.md
  exp/api/v1alpha3/azuremachinepool_conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/azuremachinepool_conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/azuremachinepool_default.go
  exp/api/v1beta1/azuremachinepool_default_test.go
  exp/api/v1beta1/azuremachinepool_types.go
  exp/api/v1beta1/azuremachinepool_webhook.go
  exp/api/v1beta1/azuremachinepool_webhook_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  main.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, lifecycle/active, size/XXL, lgtm

#3179 Collect node describe artifacts in logger
  test/e2e/azure_clusterproxy.go
  test/e2e/e2e_suite_vars.go
Labels: cncf-cla: yes, tide/merge-method-squash, size/M, release-note-none, approved, lgtm

#3161 add documentation for running wasm workloads
  .codespellignore
  docs/book/src/SUMMARY.md
  docs/book/src/topics/wasi.md
Labels: cncf-cla: yes, size/L, release-note, approved, kind/documentation, lgtm

#3057 Add support for bastion tiers
  api/v1alpha4/azurecluster_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/types.go
  azure/scope/cluster.go
  azure/services/bastionhosts/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  docs/book/src/topics/ssh-access.md
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/prow-private/patches/bastion.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#3166 Add clusterclass template for Tilt
  Makefile
  Tiltfile
  templates/cluster-template-clusterclass.yaml
  templates/flavors/clusterclass/azure-cluster-template.yaml
  templates/flavors/clusterclass/azure-machine-template-controlplane.yaml
  templates/flavors/clusterclass/azure-machine-template-worker.yaml
  templates/flavors/clusterclass/cluster.yaml
  templates/flavors/clusterclass/clusterclass.yaml
  templates/flavors/clusterclass/kubeadm-config-template.yaml
  templates/flavors/clusterclass/kubeadm-controlplane-template.yaml
  templates/flavors/clusterclass/kustomization.yaml
  templates/test/ci/cluster-template-prow-clusterclass-ci-default.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/prow-clusterclass-ci-default/base.yaml
  templates/test/ci/prow-clusterclass-ci-default/kubeadm-config-template.yaml
  templates/test/ci/prow-clusterclass-ci-default/kustomization.yaml
  templates/test/ci/prow-clusterclass-ci-default/patches.yaml
  templates/test/ci/prow-clusterclass-ci-default/variables.yaml
  templates/test/ci/prow-clusterclass-ci-default/windows.yaml
  templates/test/ci/prow-topology/cluster.yaml
  templates/test/ci/prow-topology/kustomization.yaml
  test/e2e/azure_test.go
Labels: kind/feature, cncf-cla: yes, release-note-none, approved, size/XXL, lgtm

#3186 Allow parallel flavor resources in Tilt
  Tiltfile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3196 Detect Flex from VMSS orchestration mode
  azure/converters/vmss.go
  azure/converters/vmss_test.go
  azure/scope/machinepool.go
  azure/scope/machinepoolmachine.go
  azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesetvms/mock_scalesetvms/scalesetvms_mock.go
  azure/services/scalesetvms/scalesetvms.go
  azure/services/scalesetvms/scalesetvms_test.go
  azure/types.go
  azure/types_test.go
  test/e2e/azure_machinepools.go
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, kind/failing-test

#3194 MachinePools: Fix AzureMachinePool default for SystemAssignedIdentityRole
  api/v1beta1/azuremachine_default_test.go
  exp/api/v1beta1/azuremachinepool_default.go
  exp/api/v1beta1/azuremachinepool_default_test.go
  exp/api/v1beta1/azuremachinepool_webhook.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3134 Custom data model fix
  azure/const.go
  azure/scope/machinepool.go
  azure/services/scalesets/mock_scalesets/scalesets_mock.go
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
  config/rbac/role.yaml
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/helpers.go
  main.go
Labels: cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#3187 fix tag delete following resource create
  azure/services/tags/tags.go
  azure/services/tags/tags_test.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#3127 E2E: don’t stop/start kubelet before kubeadm runs
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/patches/control-plane-kubeadm-boostrap-ci-version.yaml
  templates/test/ci/prow-ci-version/patches/kubeadm-bootstrap.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/custom-builds.yaml
  templates/test/dev/custom-builds/patches/kubeadm-bootstrap.yaml
  templates/test/dev/custom-builds/patches/kubeadm-controlplane-bootstrap.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm
