Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2023-04, with the labels that each got.

#3358 [e2e] Support more flexible env var for cloud-provider-azure
  scripts/ci-build-azure-ccm.sh
  scripts/ci-e2e.sh
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#3368 Run codecov job on every PR with threshold of 1%
  .github/codecov.yml
  .github/workflows/cover.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3340 Enable setting VNet peering properties
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/services/vnetpeerings/spec.go
  azure/services/vnetpeerings/vnetpeerings_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclustertemplates.yaml
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, lgtm

#3298 Bump CAPI to v1.4.1
  .golangci.yml
  Makefile
  Tiltfile
  api/v1beta1/azuremachine_default.go
  api/v1beta1/azuremachine_default_test.go
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedmachinepool_webhook.go
  api/v1beta1/azuremanagedmachinepool_webhook_test.go
  azure/scope/cluster.go
  azure/scope/identity.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/scope/managedmachinepool.go
  azure/scope/managedmachinepool_test.go
  azure/services/natgateways/natgateways_test.go
  controllers/azureidentity_controller.go
  controllers/azurejson_machine_controller_test.go
  controllers/azurejson_machinepool_controller_test.go
  controllers/azuremachine_controller_test.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/helpers.go
  controllers/helpers_test.go
  exp/controllers/azuremachinepool_controller_unit_test.go
  exp/controllers/helpers.go
  go.mod
  go.sum
  main.go
  test/e2e/aks.go
  test/e2e/aks_versions.go
  test/e2e/azure_edgezone.go
  test/e2e/azure_machinepool_drain.go
  test/e2e/azure_machinepools.go
  test/e2e/azure_selfhosted.go
  test/e2e/azure_test.go
  test/e2e/azure_vmextensions.go
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/kubernetes/pod/pod.go
  test/logger.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, lgtm

#3397 Set log level of cloud-provider-azure in ci-e2e test to 4
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3382 add trivy image scan actions
  .github/workflows/scan.yml
  Makefile
  hack/verify-container-images.sh
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm

#3403 Replace KCPRemediationSpec with MachineDeploymentRemediationSpec
  test/e2e/capi_test.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#3388 Allow feature gates to be passed through for Windows CI
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider-machine-pool.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/windows-containerd-patch.yaml
  templates/test/ci/patches/windows-feature-gates.yaml
  templates/test/ci/prow-ci-version/kustomization.yaml
  templates/test/ci/prow-machine-pool/kustomization.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/kustomization.yaml
  test/e2e/conformance_test.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#3381 mark context canceled or exceeded as transient failures
  azure/errors.go
  azure/errors_test.go
  azure/services/async/async.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#3416 [release-1.8] return 1 in ci-entrypoint funcs when necessary
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#3417 [release-1.7] return 1 in ci-entrypoint funcs when necessary
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#3415 Remove WINDOWS_FLAVOR usage and Windows specific dev/ci templates
  docs/book/src/developers/development.md
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/prow-ci-version-windows-containerd-2022/kustomization.yaml
  templates/test/ci/prow-ci-version-windows-containerd-2022/patches/windows-image-update.yaml
  test/e2e/config/azure-dev.yaml
  test/e2e/conformance_test.go
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm

#3424 Change default nat gateway IP name
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azurecluster_default_test.go
  azure/defaults.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm, kind/failing-test

#3113 Add proposal for Azure Service Operator
  docs/proposals/20230123-azure-service-operator.md
  docs/proposals/images/aso-delete.plantuml
  docs/proposals/images/aso-delete.png
  docs/proposals/images/aso-reconcile.plantuml
  docs/proposals/images/aso-reconcile.png
Labels: cncf-cla: yes, kind/design, size/L, release-note-none, approved, lgtm

#3448 Add a cherry-pick candidate box in PR template
  .github/pull_request_template.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3449 add resource health registration to book
  docs/book/src/topics/getting-started.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#3440 disable surging if externally managed autoscaler is used
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, ok-to-test, lgtm

#3414 update SDKImageToImage func to handle different image types
  azure/converters/vmss.go
  azure/converters/vmss_test.go
  azure/scope/machinepoolmachine.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#3444 add i/o timeout for e2e SSH log collection
  test/e2e/azure_logcollector.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#3418 Add unit tests for AzureMachine controller
  controllers/azuremachine_controller_test.go
  controllers/azuremachine_reconciler.go
  controllers/azuremachine_reconciler_test.go
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note-none, approved, lgtm

#3463 Add missing variable export to AKS docs
  docs/book/src/topics/managedcluster.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#3455 Don't reuse IMAGE_TAG var in multiple test scripts
  scripts/ci-build-azure-ccm.sh
  scripts/ci-build-kubernetes.sh
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#3465 [release-1.8] disable surging if externally managed autoscaler is used
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
Labels: cncf-cla: yes, size/XS, release-note, approved, ok-to-test, lgtm

#3464 [release-1.7] disable surging if externally managed autoscaler is used
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
Labels: cncf-cla: yes, size/XS, release-note, approved, ok-to-test, lgtm

#3466 [release-1.8] SDKImageToImage func to handle different image types
  azure/converters/vmss.go
  azure/converters/vmss_test.go
  azure/scope/machinepoolmachine.go
Labels: cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#3399 add explicit securityContexts to the controller and namespace label for privileged
  config/default/namespace.yaml
  config/manager/manager.yaml
Labels: kind/feature, cncf-cla: yes, size/S, release-note, approved, lgtm

#3458 Revert "E2E: don’t stop/start kubelet before kubeadm runs"
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/patches/control-plane-kubeadm-boostrap-ci-version.yaml
  templates/test/ci/prow-ci-version/patches/kubeadm-bootstrap.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/custom-builds.yaml
  templates/test/dev/custom-builds/patches/kubeadm-bootstrap.yaml
  templates/test/dev/custom-builds/patches/kubeadm-controlplane-bootstrap.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#3468 [release-1.8] fix some variables in ci-build-azure-ccm.sh
  scripts/ci-build-azure-ccm.sh
  scripts/ci-build-kubernetes.sh
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  scripts/ci-entrypoint.sh
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#3469 [release-1.7] update SDKImageToImage func to handle different image types
  azure/converters/vmss.go
  azure/converters/vmss_test.go
  azure/scope/machinepoolmachine.go
Labels: cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#3477 Fix tilt error creating process.txt
  Tiltfile
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#3454 Fix ci-entrypoint.sh array export for macOS
  scripts/ci-entrypoint.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3456 Switch k8s custom build templates to external cloud-provider
  hack/util.sh
  scripts/ci-build-azure-ccm.sh
  scripts/ci-build-kubernetes.sh
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/kustomization.yaml
  templates/test/dev/custom-builds/kustomization.yaml
  templates/test/dev/custom-builds/patches/kubeadm-controlplane-bootstrap.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#3480 [release-1.8] Switch k8s custom build templates to out of tree
  hack/util.sh
  scripts/ci-build-azure-ccm.sh
  scripts/ci-build-kubernetes.sh
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/kustomization.yaml
  templates/test/dev/custom-builds/kustomization.yaml
  templates/test/dev/custom-builds/patches/kubeadm-controlplane-bootstrap.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
  test/e2e/cloud-provider-azure.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#3482 Revert change to reuse artifacts for Windows
  scripts/ci-build-azure-ccm.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#3487 [release-1.8] Cherry-picking 1d6c199 into release-1.8
  docs/book/src/topics/windows.md
  scripts/ci-entrypoint.sh
  templates/cluster-template-machinepool-windows.yaml
  templates/cluster-template-windows.yaml
  templates/flavors/base-windows-containerd/kubeadm-control-plane.yaml
  templates/flavors/machinepool-windows/kustomization.yaml
  templates/flavors/machinepool-windows/machine-pool-deployment-windows.yaml
  templates/flavors/windows/kustomization.yaml
  templates/flavors/windows/machine-deployment-windows.yaml
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-clusterclass-ci-default.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider-machine-pool.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/prow-clusterclass-ci-default/windows.yaml
  templates/test/ci/prow-intree-cloud-provider-machine-pool/patches/intree-mp.yaml
  templates/test/ci/prow-intree-cloud-provider/patches/intree-md-win.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/azure_test.go
  test/e2e/capi_test.go
  test/e2e/conformance_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#3488 [release-1.8] Allow feature gates to be passed through for Windows
  templates/test/ci/cluster-template-prow-ci-version-windows-containerd-2022.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider-machine-pool.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/windows-containerd-patch.yaml
  templates/test/ci/patches/windows-feature-gates.yaml
  templates/test/ci/prow-ci-version/kustomization.yaml
  templates/test/ci/prow-machine-pool/kustomization.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/kustomization.yaml
  test/e2e/conformance_test.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#3491 Replace n1 highcpu 8 with e2 highcpu 8
  cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, ok-to-test, lgtm

#3478 update golang to v1.20
  .github/workflows/cover.yaml
  .github/workflows/dependabot-code-gen.yml
  .github/workflows/release.yaml
  .github/workflows/scan.yml
  .golangci.yml
  Dockerfile
  Makefile
  Tiltfile
  azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go
  docs/book/src/developers/development.md
  go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#3475 Add missing tests for azuremachinepool_default.go
  exp/api/v1beta1/azuremachinepool_default_test.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, ok-to-test, lgtm

#3451 Add issue template for kind/cleanup
  .github/ISSUE_TEMPLATE/cleanup_request.md
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#3481 Use Ubuntu 22.04 as base OS image for k8s CI tests
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/patches/control-plane-image-ci-version.yaml
  templates/test/ci/prow-ci-version/patches/machine-deployment-ci-version.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/custom-builds.yaml
  templates/test/dev/custom-builds/patches/machine-deployment-pr-version.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm
