Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2024-03, with the labels that each got.

#4607 update pre-commit config
  .pre-commit-config.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#4613 fix mariner docs link
  docs/book/src/topics/custom-images.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#4606 use existing virtualNetwork from a different rg
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook.go
  azure/defaults.go
  azure/defaults_test.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/services/groups/spec.go
  azure/services/groups/spec_test.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, lgtm

#4608 docs: add flexible language to release docs
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4627 add 1.14 release to metadata
  CHANGELOG/v1.14.0.md
  metadata.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4629 Update roadmap
  docs/book/src/roadmap.md
Labels: cncf-cla: yes, size/S, release-note, approved, kind/documentation, lgtm

#4632 Minor update to v1.14.0 CHANGELOG
  CHANGELOG/v1.14.0.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#4634 Bump release notes tool to include additional link fix
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4641 Enable E2E testing for v1.15 release cycle
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.13.2/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.14.0/cluster-template-prow.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#4643 Bump CAPI to v1.6.3
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4631 Change release job logic to handle more files
  .github/workflows/release.yaml
Labels: kind/feature, cncf-cla: yes, size/S, tide/merge-method-squash, kind/cleanup, release-note-none, approved, lgtm

#4644 [release-1.14] Bump CAPI to v1.6.3
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4642 Improve release process
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/L, release-note, approved, kind/documentation, lgtm

#4593 test: surround CAAPH values strings in quotes
  templates/addons/cluster-api-helm/cloud-provider-azure-ci.yaml
  templates/addons/cluster-api-helm/cloud-provider-azure-flatcar.yaml
  templates/addons/cluster-api-helm/cloud-provider-azure.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-spot.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
Labels: cncf-cla: yes, kind/flake, size/L, release-note-none, approved, lgtm

#4625 Add principal type to role assignment create parameters
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/services/roleassignments/spec.go
Labels: kind/feature, cncf-cla: yes, size/S, release-note, approved, ok-to-test, lgtm

#4662 [release-1.13] test: surround CAAPH values strings in quotes
  templates/addons/cluster-api-helm/cloud-provider-azure-ci.yaml
  templates/addons/cluster-api-helm/cloud-provider-azure-flatcar.yaml
  templates/addons/cluster-api-helm/cloud-provider-azure.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4660 Set nonzero default control plane node count in templates
  templates/cluster-template-aad.yaml
  templates/cluster-template-aks.yaml
  templates/cluster-template-azure-bastion.yaml
  templates/cluster-template-azure-cni-v1.yaml
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-edgezone.yaml
  templates/cluster-template-ephemeral.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-ipv6.yaml
  templates/cluster-template-machinepool-windows.yaml
  templates/cluster-template-machinepool.yaml
  templates/cluster-template-nvidia-gpu.yaml
  templates/cluster-template-private.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template-windows.yaml
  templates/cluster-template.yaml
  templates/flavors/aad/machine-deployment.yaml
  templates/flavors/aks/cluster-template.yaml
  templates/flavors/base/cluster-template.yaml
  templates/flavors/default/machine-deployment.yaml
  templates/flavors/dual-stack/machine-deployment.yaml
  templates/flavors/flatcar/machine-deployment.yaml
  templates/flavors/ipv6/machine-deployment.yaml
  templates/flavors/machinepool-windows/machine-pool-deployment-windows.yaml
  templates/flavors/machinepool/machine-pool-deployment.yaml
  templates/flavors/nvidia-gpu/machine-deployment.yaml
  templates/flavors/topology/cluster.yaml
  templates/flavors/windows/machine-deployment-windows.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-spot.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4677 Make AKS extension.Plan optional
  api/v1beta1/azuremanagedcontrolplane_default.go
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/types.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/services/aksextensions/spec.go
  azure/services/aksextensions/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
  docs/book/src/topics/managedcluster.md
  test/e2e/aks_marketplace.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#4529 Update Go to v1.21
  .github/workflows/cover.yaml
  .github/workflows/dependabot-code-gen.yml
  .github/workflows/scan.yml
  .golangci.yml
  Dockerfile
  Makefile
  Tiltfile
  docs/book/src/developers/development.md
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4686 ignore k8s v1.29 in AKS e2e test
  test/e2e/aks_versions.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#4680 remove redundant steps in docker build
  Dockerfile
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#4685 [release-1.13] Set nonzero default control plane node count in templates
  templates/cluster-template-aad.yaml
  templates/cluster-template-aks.yaml
  templates/cluster-template-azure-bastion.yaml
  templates/cluster-template-azure-cni-v1.yaml
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-edgezone.yaml
  templates/cluster-template-ephemeral.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-ipv6.yaml
  templates/cluster-template-machinepool-windows.yaml
  templates/cluster-template-machinepool.yaml
  templates/cluster-template-nvidia-gpu.yaml
  templates/cluster-template-private.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template-windows.yaml
  templates/cluster-template.yaml
  templates/flavors/aad/machine-deployment.yaml
  templates/flavors/aks/cluster-template.yaml
  templates/flavors/base/cluster-template.yaml
  templates/flavors/default/machine-deployment.yaml
  templates/flavors/dual-stack/machine-deployment.yaml
  templates/flavors/flatcar/machine-deployment.yaml
  templates/flavors/ipv6/machine-deployment.yaml
  templates/flavors/machinepool-windows/machine-pool-deployment-windows.yaml
  templates/flavors/machinepool/machine-pool-deployment.yaml
  templates/flavors/nvidia-gpu/machine-deployment.yaml
  templates/flavors/topology/cluster.yaml
  templates/flavors/windows/machine-deployment-windows.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4689 remove kubeletConfig.topologyManagerPolicy from AKS test templates
  templates/test/ci/cluster-template-prow-aks-clusterclass.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
  templates/test/ci/prow-aks-clusterclass/patches/aks-clusterclass-pool1.yaml
  templates/test/ci/prow-aks/patches/aks-pool1.yaml
  test/e2e/aks_versions.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm
