Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2024-06, with the labels that each got.

#4896 fix dead link
  docs/book/src/topics/identities.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#4900 Skip MEC e2e test
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#4910 use default k8s version for spot e2e test
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#4915 Bump CAPI to v1.7.3
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4916 [release-1.14] Bump CAPI to v1.6.6
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4918 add user-assigned identity to worker nodes for CI version templates
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/prow-ci-version/kustomization.yaml
  templates/test/ci/prow-machine-pool-ci-version/kustomization.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4919 [release-1.15] Bump CAPI to v1.7.3
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4920 remove user-defined MP count from aks-aso-clusterclass template
  templates/cluster-template-aks-aso-clusterclass.yaml
  templates/flavors/aks-aso-clusterclass/clusterclass.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4923 cut v1.14.6
  CHANGELOG/v1.14.6.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4924 cut v1.15.2
  CHANGELOG/v1.15.2.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4890 ci-build-auzre-ccm build windows host-process-container based images
  scripts/ci-build-azure-ccm.sh
Labels: kind/feature, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4926 set EXP_ASO_API=true for CI
  Makefile
  hack/observability/opentelemetry/controller-manager-patch.yaml
  templates/flavors/aks-aso/credentials.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4932 Bump Cluster API Visualizer to v1.3.1
  hack/observability/cluster-api-visualizer/chart/Chart.yaml
  hack/observability/cluster-api-visualizer/chart/templates/clusterrole.yaml
  hack/observability/cluster-api-visualizer/fetch-visualizer-resources.sh
Labels: kind/feature, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4878 Refactored codebase to use camel case for spec parameter in field.NewPath method
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/azurecluster_webhook.go
  api/v1beta1/azuremachine_validation.go
  api/v1beta1/azuremachine_webhook.go
  api/v1beta1/azuremachinetemplate_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook.go
  api/v1beta1/azuremanagedmachinepool_webhook.go
  api/v1beta1/azuremanagedmachinepooltemplate_webhook.go
  exp/api/v1beta1/azuremachinepool_webhook.go
  util/webhook/validator_test.go
Labels: cncf-cla: yes, tide/merge-method-squash, size/L, release-note-none, approved, ok-to-test, lgtm

#4929 handle non-native autoscalers for AzureASOManagedMachinePool
  exp/controllers/azureasomanagedmachinepool_controller.go
  exp/mutators/azureasomanagedcontrolplane.go
  exp/mutators/azureasomanagedmachinepool.go
  exp/mutators/azureasomanagedmachinepool_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm, area/managedclusters

#4944 remove westeurope from test regions
  hack/util.sh
Labels: cncf-cla: yes, size/XS, kind/flake, release-note-none, approved, lgtm

#4942 fix: panic in MachinePool log
  azure/scope/machinepool.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#4933 ✨ Add aggregated role support
  config/rbac/aggregation_role.yaml
  config/rbac/capz_manager_role_patch.yaml
  config/rbac/kustomization.yaml
  config/rbac/role_binding.yaml
Labels: kind/feature, cncf-cla: yes, size/S, release-note, approved, lgtm

#4943 fix: delete Machine instead of AzureMachinePoolMachine if VMSS VM is failed
  exp/controllers/azuremachinepoolmachine_controller.go
  exp/controllers/azuremachinepoolmachine_controller_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, ok-to-test, lgtm

#4946 allow managed clusters for ci-entrypoint
  Makefile
  hack/create-dev-cluster.sh
  scripts/ci-entrypoint.sh
  scripts/kind-with-registry.sh
Labels: kind/feature, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4931 🌱 Decouple MachinePool reconciler from Kubeadm
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/azuremachinepool_controller_test.go
  exp/controllers/helpers.go
  exp/controllers/suite_test.go
  main.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm
