Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2024-01, with the labels that each got.

#4427 fix envtest setup flake
  internal/test/env/env.go
Labels: cncf-cla: yes, size/XS, kind/flake, release-note-none, approved, lgtm

#4425 Remove last uses of old Azure SDK for Go
  go.mod
  go.sum
  test/e2e/azure_clusterproxy.go
  version/version.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4416 Revert "Temporarily pin Flatcar version to v1.26.10"
  test/e2e/config/azure-dev.yaml
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4429 Skip book output files in codespell verification
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4434 Update e2e test k8s versions
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4436 Remove deprecated kubelet credential provider flag
  docs/book/src/topics/managedcluster.md
  templates/cluster-template-aad.yaml
  templates/cluster-template-azure-bastion.yaml
  templates/cluster-template-azure-cni-v1.yaml
  templates/cluster-template-clusterclass.yaml
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-edgezone.yaml
  templates/cluster-template-ephemeral.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-intree-cloud-provider.yaml
  templates/cluster-template-ipv6.yaml
  templates/cluster-template-nvidia-gpu.yaml
  templates/cluster-template-private.yaml
  templates/cluster-template-windows.yaml
  templates/cluster-template.yaml
  templates/flavors/aad/machine-deployment.yaml
  templates/flavors/clusterclass/kubeadm-config-template.yaml
  templates/flavors/clusterclass/kubeadm-controlplane-template.yaml
  templates/flavors/default/machine-deployment.yaml
  templates/flavors/dual-stack/machine-deployment.yaml
  templates/flavors/flatcar/machine-deployment.yaml
  templates/flavors/ipv6/machine-deployment.yaml
  templates/flavors/nvidia-gpu/machine-deployment.yaml
  templates/test/ci/cluster-template-prow-aks-clusterclass.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-clusterclass-ci-default.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-intree-cloud-provider.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/azurediskcsi-migration-off.yaml
  templates/test/ci/prow-aks-clusterclass/patches/kubeadm-config-template.yaml
  templates/test/ci/prow-ci-version-ipv6/patches/machine-deployment.yaml
  templates/test/ci/prow-clusterclass-ci-default/kubeadm-config-template.yaml
  templates/test/ci/prow-clusterclass-ci-default/windows.yaml
  templates/test/ci/prow-intree-cloud-provider/patches/intree-md-0.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/custom-builds.yaml
  test/e2e/aks_byo_node.go
  test/e2e/data/infrastructure-azure/v1.0.2/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1beta1/bases/mp.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-upgrades.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4438 fix HTTP 409 flake in AKS Cluster Class test
  test/e2e/aks_clusterclass.go
Labels: cncf-cla: yes, size/XS, kind/flake, release-note-none, approved, lgtm

#4433 Use newer v1beta1 version in API version upgrade test
  docs/book/src/developers/releasing.md
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.11.7/cluster-template-prow.yaml
  test/e2e/data/shared/v1alpha3/metadata.yaml
  test/e2e/data/shared/v1alpha3_provider/metadata.yaml
  test/e2e/data/shared/v1alpha4/metadata.yaml
  test/e2e/data/shared/v1alpha4_provider/metadata.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, kind/failing-test

#4447 Replace most usage of go-autorest in unit tests
  azure/scope/managedcontrolplane_test.go
  azure/services/availabilitysets/availabilitysets_test.go
  azure/services/disks/disks_test.go
  azure/services/inboundnatrules/inboundnatrules_test.go
  azure/services/loadbalancers/loadbalancers_test.go
  azure/services/networkinterfaces/networkinterfaces_test.go
  azure/services/privatedns/privatedns_test.go
  azure/services/publicips/publicips_test.go
  azure/services/roleassignments/roleassignments_test.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesetvms/scalesetvms_test.go
  azure/services/tags/tags_test.go
  azure/services/virtualmachines/virtualmachines_test.go
  azure/services/vmextensions/vmextensions_test.go
  azure/services/vnetpeerings/vnetpeerings_test.go
  controllers/asosecret_controller_test.go
  controllers/azurejson_machine_controller_test.go
  controllers/azurejson_machinepool_controller_test.go
  controllers/azurejson_machinetemplate_controller_test.go
  controllers/azuremanagedmachinepool_controller_test.go
  controllers/helpers_test.go
  exp/controllers/azuremachinepoolmachine_controller_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4448 [release-1.12] Change upgrade test to newer CAPI
  docs/book/src/developers/releasing.md
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.10.8/cluster-template-prow.yaml
  test/e2e/data/shared/v1alpha3/metadata.yaml
  test/e2e/data/shared/v1alpha3_provider/metadata.yaml
  test/e2e/data/shared/v1alpha4/metadata.yaml
  test/e2e/data/shared/v1alpha4_provider/metadata.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, kind/failing-test

#4453 Skip AvailabilitySet creation for Spot instances
  azure/scope/machine.go
  azure/scope/machine_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#4424 Remove support for AAD Pod Identity
  Tiltfile
  api/v1beta1/types.go
  azure/scope/cluster_test.go
  azure/scope/identity.go
  azure/scope/identity_test.go
  azure/scope/managedcontrolplane_test.go
  config/capz/aad-pod-identity-deployment.yaml
  config/capz/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/asosecret_controller_test.go
  controllers/azurecluster_controller_test.go
  controllers/azureidentity_controller.go
  controllers/azureidentity_controller_test.go
  controllers/azurejson_machine_controller_test.go
  controllers/azurejson_machinepool_controller_test.go
  controllers/azurejson_machinetemplate_controller_test.go
  controllers/azuremachine_controller_test.go
  controllers/azuremanagedcontrolplane_controller_test.go
  controllers/azuremanagedmachinepool_controller_test.go
  controllers/helpers_test.go
  docs/book/src/topics/identities.md
  docs/book/src/topics/multitenancy.md
  exp/controllers/azuremachinepool_controller_test.go
  exp/controllers/azuremachinepoolmachine_controller_test.go
  go.mod
  go.sum
  main.go
  test/e2e/azure_clusterproxy.go
Labels: cncf-cla: yes, kind/cleanup, release-note, approved, size/XXL, lgtm

#4461 bump Makefile kubectl to v1.28.4
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4455 Remove leftover in-tree cloud-provider configurations
  templates/cluster-template-aad.yaml
  templates/cluster-template-azure-bastion.yaml
  templates/cluster-template-azure-cni-v1.yaml
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-edgezone.yaml
  templates/cluster-template-ephemeral.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-intree-cloud-provider.yaml
  templates/cluster-template-ipv6.yaml
  templates/cluster-template-machinepool-windows.yaml
  templates/cluster-template-machinepool.yaml
  templates/cluster-template-nvidia-gpu.yaml
  templates/cluster-template-private.yaml
  templates/cluster-template-windows.yaml
  templates/cluster-template.yaml
  templates/flavors/aad/patches/kubeadm-controlplane.yaml
  templates/flavors/base/cluster-template.yaml
  templates/flavors/dual-stack/patches/kubeadm-controlplane.yaml
  templates/flavors/machinepool-windows/machine-pool-deployment-windows.yaml
  templates/flavors/machinepool/machine-pool-deployment.yaml
  templates/flavors/windows/machine-deployment-windows.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/azurediskcsi-migration-off.yaml
  templates/test/ci/prow-dual-stack/machine-pool-dualstack.yaml
  templates/test/ci/prow-ipv6/machine-pool-ipv6.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4464 [release-1.12] Bump CAPI to v1.5.5
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4463 Bump CAPI to v1.6.1
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4465 [release-1.11] Bump CAPI to v1.5.5
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4467 [release-1.12] Remove leftover in-tree credential provider configurations
  templates/cluster-template-aad.yaml
  templates/cluster-template-azure-bastion.yaml
  templates/cluster-template-azure-cni-v1.yaml
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-edgezone.yaml
  templates/cluster-template-ephemeral.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-intree-cloud-provider.yaml
  templates/cluster-template-ipv6.yaml
  templates/cluster-template-machinepool-windows.yaml
  templates/cluster-template-machinepool.yaml
  templates/cluster-template-nvidia-gpu.yaml
  templates/cluster-template-private.yaml
  templates/cluster-template-windows.yaml
  templates/cluster-template.yaml
  templates/flavors/aad/patches/kubeadm-controlplane.yaml
  templates/flavors/base/cluster-template.yaml
  templates/flavors/dual-stack/patches/kubeadm-controlplane.yaml
  templates/flavors/machinepool-windows/machine-pool-deployment-windows.yaml
  templates/flavors/machinepool/machine-pool-deployment.yaml
  templates/flavors/windows/machine-deployment-windows.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/azurediskcsi-migration-off.yaml
  templates/test/ci/prow-dual-stack/machine-pool-dualstack.yaml
  templates/test/ci/prow-ipv6/machine-pool-ipv6.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4316 Add support for joining clusters to AKS Fleet
  Makefile
  api/v1beta1/azuremanagedcontrolplane_default.go
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/consts.go
  api/v1beta1/types.go
  api/v1beta1/types_class.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/defaults.go
  azure/scope/managedcontrolplane.go
  azure/services/bastionhosts/spec_test.go
  azure/services/fleetsmembers/fleetsmembers.go
  azure/services/fleetsmembers/spec.go
  azure/services/fleetsmembers/spec_test.go
  config/aso/crds.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
  config/rbac/role.yaml
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_controller_test.go
  controllers/azuremanagedcontrolplane_reconciler.go
  docs/book/src/topics/managedcluster.md
  go.mod
  go.sum
  main.go
  test/e2e/aks_fleets_member.go
  test/e2e/azure_test.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#4469 update metadata to include 1.13 tag
  metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4466 Update metrics address flag in Tilt
  hack/observability/opentelemetry/controller-manager-patch.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4475 Add release notes for v1.11.8
  CHANGELOG/v1.11.8.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4474 Add release notes for v1.12.2
  CHANGELOG/v1.12.2.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4477 add release notes for CAPZ v1.13.0
  CHANGELOG/v1.13.0.md
Labels: cncf-cla: yes, size/L, release-note-none, approved, kind/documentation, lgtm

#4476 Remove unused Makefile target
  Makefile
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#4478 Fix broken path in kpromo tool install
  Makefile
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4470 overcome transient failures + retry when creating test cluster
  Makefile
  hack/create-dev-cluster.sh
Labels: cncf-cla: yes, kind/flake, size/M, release-note-none, approved, lgtm

#4482 [release-1.12] overcome transient failures + retry when creating test cluster
  Makefile
  hack/create-dev-cluster.sh
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#4473 set v1.14 as the next release in azure-dev and test/metadata
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4480 remove unneeded embedded interfaces from ASO services
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/mock_agentpools/agentpools_mock.go
  azure/services/bastionhosts/bastionhosts.go
  azure/services/natgateways/mock_natgateways/natgateways_mock.go
  azure/services/natgateways/natgateways.go
Labels: cncf-cla: yes, size/XL, kind/cleanup, release-note-none, approved, lgtm

#4484 Update release-notes tool and add --repo-path flag
  Makefile
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4483 Minor improvements to "CAPZ Releases" docs
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, kind/documentation, lgtm

#4485 Add mdbook output files to .gitignore
  .gitignore
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4498 simplify aso.Reconciler interface
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
  azure/services/aso/interfaces.go
  azure/services/aso/mock_aso/aso_mock.go
  azure/services/aso/service.go
  azure/services/aso/service_test.go
  azure/services/groups/groups.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4497 simplify updates to ASO resources
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4446 Add test that upgrades CAPZ from latest release branch to HEAD
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.12.2/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.13.0/cluster-template-prow.yaml
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm

#4499 use owner refs to determine ownership for ASO resources
  api/v1beta1/consts.go
  azure/interfaces.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/scope/managedmachinepool.go
  azure/scope/managedmachinepool_test.go
  azure/services/agentpools/mock_agentpools/agentpools_mock.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
  azure/services/aso/interfaces.go
  azure/services/aso/mock_aso/aso_mock.go
  azure/services/aso/service.go
  azure/services/aso/service_test.go
  azure/services/bastionhosts/spec.go
  azure/services/bastionhosts/spec_test.go
  azure/services/fleetsmembers/spec.go
  azure/services/fleetsmembers/spec_test.go
  azure/services/groups/groups.go
  azure/services/groups/groups_test.go
  azure/services/groups/mock_groups/groups_mock.go
  azure/services/groups/spec.go
  azure/services/groups/spec_test.go
  azure/services/managedclusters/mock_managedclusters/managedclusters_mock.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  azure/services/natgateways/mock_natgateways/natgateways_mock.go
  azure/services/natgateways/spec.go
  azure/services/natgateways/spec_test.go
  azure/services/privateendpoints/mock_privateendpoints/privateendpoints_mock.go
  azure/services/privateendpoints/spec.go
  azure/services/privateendpoints/spec_test.go
  azure/services/subnets/mock_subnets/subnets_mock.go
  azure/services/subnets/spec.go
  azure/services/virtualnetworks/mock_virtualnetworks/virtualnetworks_mock.go
  azure/services/virtualnetworks/spec.go
  azure/services/virtualnetworks/spec_test.go
  controllers/azurecluster_reconciler_test.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, lgtm

#4502 Set specific token permissions in GH actions
  .github/workflows/dependabot-code-gen.yml
  .github/workflows/release.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#4504 Update go vendoring in hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm

#4505 move sonasingh46 to emeritus
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4360 Add support for AKS Extensions & Marketplace Offers
  Makefile
  api/v1beta1/azuremanagedcontrolplane_default.go
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook_test.go
  api/v1beta1/consts.go
  api/v1beta1/types.go
  api/v1beta1/types_class.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/services/aksextensions/aksextensions.go
  azure/services/aksextensions/spec.go
  azure/services/aksextensions/spec_test.go
  config/aso/crds.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
  config/rbac/role.yaml
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_reconciler.go
  docs/book/src/topics/managedcluster.md
  go.mod
  go.sum
  main.go
  test/e2e/aks_marketplace.go
  test/e2e/azure_test.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#4509 [release-1.12] Set specific token permissions in GH actions
  .github/workflows/dependabot-code-gen.yml
  .github/workflows/release.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#4500 Move CecileRobertMichon to emeritus
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4442 Add additionalPrinterColumns to CAPZ resources
  api/v1beta1/azureclusteridentity_types.go
  api/v1beta1/azuremachine_types.go
  api/v1beta1/azuremanagedcluster_types.go
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedmachinepool_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#4507 dedicated make config file for conformance tests
  Makefile
  conformance.mk
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4510 dedicated make config file for E2E tests
  Makefile
  e2e.mk
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4511 Update subnet validation webhook regex
  api/v1beta1/azuremanagedmachinepool_webhook.go
  api/v1beta1/azuremanagedmachinepool_webhook_test.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, ok-to-test, lgtm

#4520 update codecov GitHub Action to 3.15
  .github/workflows/cover.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4506 clean up unreferenced ASO resources
  azure/services/aso/service.go
  azure/services/aso/service_test.go
  azure/services/bastionhosts/bastionhosts.go
  azure/services/fleetsmembers/fleetsmembers.go
  azure/services/groups/groups.go
  azure/services/natgateways/natgateways.go
  azure/services/subnets/subnets.go
  test/e2e/aks_fleets_member.go
  util/slice/slice.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#4524 align tools k8s dependency versions
  hack/tools/go.mod
  hack/tools/go.sum
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#4523 clarify template patch name that injects windows replica count
  templates/test/ci/patches/windows-machine-deployment-replicas.yaml
  templates/test/ci/prow-ci-version/kustomization.yaml
  templates/test/ci/prow/kustomization.yaml
  templates/test/dev/custom-builds/kustomization.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm
