Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2024-10, with the labels that each got.

#5143 clean up scope unit tests
  azure/scope/cluster_test.go
  azure/scope/managedcontrolplane_test.go
  azure/scope/managedmachinepool_test.go
Labels: cncf-cla: yes, release-note-none, approved, size/XXL, lgtm

#5150 Bump otel to v1.30.0/v0.52.0
  go.mod
  go.sum
  hack/observability/opentelemetry/chart/Chart.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#5155 Add release notes for CAPZ v1.16.2
  CHANGELOG/v1.16.2.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#5146 refactor(manager): set machinepool true as default
  config/manager/manager.yaml
  docs/book/src/developers/development.md
  docs/book/src/managed/managedcluster.md
  docs/book/src/self-managed/machinepools.md
  hack/observability/opentelemetry/controller-manager-patch.yaml
Labels: cncf-cla: yes, size/S, release-note, approved, ok-to-test, lgtm

#5103 Add MachinePools to CAPI apiversion upgrade test
  Makefile
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.16.1/cluster-template-prow-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1.17.0/cluster-template-prow-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-and-machine-pool/kustomization.yaml
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm

#5109 Custom builds: fall back to curl with az login fails
  templates/test/ci/cluster-template-prow-ci-version-dra.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-kcp.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-win.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/kubeadm-bootstrap-windows-k8s-ci-binaries.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds-dra.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/kubeadm-bootstrap-machine-pool-windows-k8s-pr-binaries.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
Labels: cncf-cla: yes, size/XL, release-note, approved, lgtm, kind/failing-test

#5166 remove unnecassary caching of of golangci-lint
  .github/workflows/pr-golangci-lint.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5120 dump resources on delete timeout
  test/e2e/common.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#5170 bump ASO to v2.9.0
  Makefile
  config/aso/crds.yaml
  config/aso/kustomization.yaml
  go.mod
  go.sum
  main.go
Labels: cncf-cla: yes, kind/cleanup, release-note, approved, size/XXL, lgtm

#5172 remove invalid caBundle from CRDs
  config/crd/patches/webhook_in_azureclusteridentities.yaml
  config/crd/patches/webhook_in_azureclusters.yaml
  config/crd/patches/webhook_in_azureclustertemplates.yaml
  config/crd/patches/webhook_in_azuremachinepoolmachines.yaml
  config/crd/patches/webhook_in_azuremachinepools.yaml
  config/crd/patches/webhook_in_azuremachines.yaml
  config/crd/patches/webhook_in_azuremachinetemplates.yaml
  config/crd/patches/webhook_in_azuremanagedclusters.yaml
  config/crd/patches/webhook_in_azuremanagedcontrolplanes.yaml
  config/crd/patches/webhook_in_azuremanagedmachinepools.yaml
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#5182 fix can_reuse_artifacts when artifact is missing
  scripts/ci-build-kubernetes.sh
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#5181 disable shared key access on AZWI storage accounts
  scripts/kind-with-registry.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5185 [release-1.16] Bump CAPI to v1.7.7
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5186 Bump CAPI to v1.8.4
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5190 [release-1.17] Bump CAPI to v1.8.4
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5191 Fix aks-create when default az output isn't JSON
  scripts/aks-as-mgmt.sh
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#5197 all required vars have values in aks-as-mgmt.sh
  scripts/aks-as-mgmt.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5193 Add FAQs to Documentation
  docs/book/src/SUMMARY.md
  docs/book/src/topics/FAQ.md
  docs/book/src/topics/topics.md
Labels: cncf-cla: yes, tide/merge-method-squash, size/M, release-note-none, approved, kind/documentation, ok-to-test, lgtm

#5164 fix(machinepool): clear VirtualMachineProfile if no model/custom data update
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesets/spec.go
  azure/services/scalesets/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#5205 cut v1.17.1
  CHANGELOG/v1.17.1.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#5206 cut v1.16.3
  CHANGELOG/v1.16.3.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#5207 Bump CAPZ versions used in upgrade tests
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.16.3/cluster-template-prow-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1.16.3/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.17.1/cluster-template-prow-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1.17.1/cluster-template-prow.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5218 Fix bug where REGISTRY is not set when gcloud isn't present
  Makefile
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#5219 Remove unused SECURITY_SCAN vars
  test/e2e/common.go
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5213 update .pre-commit config
  .pre-commit-config.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5220 rebase DRA templates onto machinepool templates
  templates/test/ci/cluster-template-prow-ci-version-dra.yaml
  templates/test/ci/prow-ci-version-dra/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds-dra.yaml
  templates/test/dev/custom-builds-dra/kustomization.yaml
Labels: cncf-cla: yes, kind/cleanup, release-note-none, approved, size/XXL, lgtm

#5209 Use internal LB's IP for intra-node communication
  Makefile
  api/v1beta1/tags.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/services/loadbalancers/spec.go
  scripts/aks-as-mgmt.sh
  templates/cluster-template-azure-bastion.yaml
  templates/cluster-template-azure-cni-v1.yaml
  templates/cluster-template-edgezone.yaml
  templates/cluster-template-ephemeral.yaml
  templates/cluster-template-windows.yaml
  templates/cluster-template.yaml
  templates/flavors/default/kustomization.yaml
  templates/flavors/default/patches/control-plane.yaml
  templates/flavors/default/patches/kubeadm-config-template.yaml
  templates/flavors/windows/kustomization.yaml
  templates/flavors/windows/patches/kubeadm-config-template.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-spot.yaml
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#5221 check for google project silently
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5167 Use community gallery for default VM images
  Dockerfile
  Makefile
  Tiltfile
  api/v1beta1/azuremachine_types.go
  azure/converters/vmss.go
  azure/defaults.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/services/virtualmachineimages/cache.go
  azure/services/virtualmachineimages/cache_test.go
  azure/services/virtualmachineimages/client.go
  azure/services/virtualmachineimages/images.go
  azure/services/virtualmachineimages/images_test.go
  azure/services/virtualmachineimages/mock_virtualmachineimages/client_mock.go
  azure/services/virtualmachineimages/mock_virtualmachineimages/doc.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  docs/book/src/self-managed/custom-images.md
  hack/create-dev-cluster.sh
  test/e2e/azure_test.go
  test/e2e/common.go
  test/e2e/helpers.go
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#5222 fix KubeadmConfig patches for DRA templates
  templates/test/ci/cluster-template-prow-ci-version-dra.yaml
  templates/test/ci/patches/dra-kubeadmconfig.yaml
  templates/test/ci/prow-ci-version-dra/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds-dra.yaml
  templates/test/dev/custom-builds-dra/kustomization.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#5226 simplify DRA config for containerd
  templates/test/ci/cluster-template-prow-ci-version-dra.yaml
  templates/test/ci/patches/dra-kubeadmconfig.yaml
  templates/test/ci/patches/dra-kubeadmcontrolplane.yaml
  templates/test/dev/cluster-template-custom-builds-dra.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm
