Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2024-08, with the labels that each got.

#5041 ensure more uniqueness for CI storage accounts
  scripts/kind-with-registry.sh
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#5043 CI: use generated identity w/ storage privileges
  hack/log/redact.sh
  scripts/kind-with-registry.sh
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/prow-ci-version/patches/machine-deployment-ci-version-control-plane.yaml
  templates/test/ci/prow-ci-version/patches/machine-deployment-ci-version-windows.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/patches/machine-deployment-pr-version-windows.yaml
  templates/test/dev/custom-builds/patches/machine-deployment-pr-version.yaml
  test/e2e/data/kubetest/upstream-windows-ginkgo-v2.yaml
  test/e2e/data/kubetest/upstream-windows-serial-slow-ginkgo-v2.yaml
  test/e2e/data/kubetest/upstream-windows-serial-slow.yaml
  test/e2e/data/kubetest/upstream-windows.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#5049 ci: remove upstream-windows-serial-slow configs
  docs/book/src/developers/development.md
  test/e2e/data/kubetest/upstream-windows-serial-slow-ginkgo-v2.yaml
  test/e2e/data/kubetest/upstream-windows-serial-slow.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5047 set AZURE_CLIENT_ID_USER_ASSIGNED_IDENTITY for create-custom-cloud-provider-config.sh
  Makefile
  hack/create-custom-cloud-provider-config.sh
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#5055 ASOAPI: truncate expected node label values at max length
  controllers/azureasomanagedmachinepool_controller.go
Labels: kind/bug, cncf-cla: yes, size/XS, kind/flake, release-note, approved, lgtm

#5059 allow setting AzureClusterIdentity spec.type with variable
  templates/azure-cluster-identity/azure-cluster-identity.yaml
  templates/cluster-template-aad.yaml
  templates/cluster-template-aks-clusterclass.yaml
  templates/cluster-template-aks.yaml
  templates/cluster-template-azure-bastion.yaml
  templates/cluster-template-azure-cni-v1.yaml
  templates/cluster-template-clusterclass.yaml
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-edgezone.yaml
  templates/cluster-template-ephemeral.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-ipv6.yaml
  templates/cluster-template-machinepool-windows.yaml
  templates/cluster-template-machinepool.yaml
  templates/cluster-template-nvidia-gpu.yaml
  templates/cluster-template-private.yaml
  templates/cluster-template-windows.yaml
  templates/cluster-template.yaml
  templates/test/ci/cluster-template-prow-aks-clusterclass.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-clusterclass-ci-default.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-spot.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-upgrades.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, lgtm

#5054 eliminate unnecessary tag updates to VMSS resources
  azure/scope/machinepool.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#5060 use sufficient identity roles for conformance tests
  scripts/kind-with-registry.sh
Labels: cncf-cla: yes, size/XS, tide/merge-method-squash, kind/cleanup, release-note-none, approved, lgtm

#5071 use token from AzureClusterIdentity for AAD-enabled AKS clusters
  azure/services/managedclusters/managedclusters.go
  azure/services/token/client.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#5074 reduce to one credential provider implementation
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/identity.go
  azure/scope/identity_test.go
  azure/scope/managedcontrolplane.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#5075 Revert "update default custom cloud provider config for managed identity"
  hack/create-custom-cloud-provider-config.sh
  templates/test/ci/default-custom-cloud-provider-config.json
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5072 Bump CAPI to v1.7.5
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5078 add namespace to ci-entrypoint cleanup
  scripts/ci-entrypoint.sh
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#5084 remove explicit k8s 1.26 for VMSS flex e2e test
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#5083 Update mdbook deps
  docs/book/book.toml
  docs/book/install-and-build.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note, approved, lgtm

#5077 [release-1.16] Bump CAPI to v1.7.5
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5088 Documentation refactor
  README.md
  docs/README.md
  docs/book/src/SUMMARY.md
  docs/book/src/developers/development.md
  docs/book/src/developers/releasing.md
  docs/book/src/getting-started.md
  docs/book/src/managed/adopting-clusters.md
  docs/book/src/managed/asomanagedcluster.md
  docs/book/src/managed/managed.md
  docs/book/src/managed/managedcluster-join-vmss.md
  docs/book/src/managed/managedcluster.md
  docs/book/src/managed/troubleshooting.md
  docs/book/src/self-managed/addons.md
  docs/book/src/self-managed/api-server-endpoint.md
  docs/book/src/self-managed/cloud-provider-config.md
  docs/book/src/self-managed/confidential-vms.md
  docs/book/src/self-managed/control-plane-outbound-lb.md
  docs/book/src/self-managed/custom-dns.md
  docs/book/src/self-managed/custom-images.md
  docs/book/src/self-managed/custom-vm-extensions.md
  docs/book/src/self-managed/custom-vnet.md
  docs/book/src/self-managed/data-disks.md
  docs/book/src/self-managed/disk-encryption.md
  docs/book/src/self-managed/disks.md
  docs/book/src/self-managed/dual-stack.md
  docs/book/src/self-managed/externally-managed-azure-infrastructure.md
  docs/book/src/self-managed/failure-domains.md
  docs/book/src/self-managed/flatcar.md
  docs/book/src/self-managed/gpu.md
  docs/book/src/self-managed/ipv6.md
  docs/book/src/self-managed/machinepools.md
  docs/book/src/self-managed/node-outbound-connection.md
  docs/book/src/self-managed/os-disk.md
  docs/book/src/self-managed/publicmec-clusters.md
  docs/book/src/self-managed/self-managed.md
  docs/book/src/self-managed/spot-vms.md
  docs/book/src/self-managed/ssh-access.md
  docs/book/src/self-managed/troubleshooting.md
  docs/book/src/self-managed/trusted-launch-for-vms.md
  docs/book/src/self-managed/vm-diagnostics.md
  docs/book/src/self-managed/vm-identity.md
  docs/book/src/self-managed/wasi.md
  docs/book/src/self-managed/windows.md
  docs/book/src/topics/aso.md
  docs/book/src/topics/identities.md
  docs/book/src/topics/multitenancy.md
  docs/book/src/topics/topics.md
Labels: cncf-cla: yes, size/XL, tide/merge-method-squash, release-note, approved, kind/documentation, lgtm

#5093 explicitly set EXP_ASO_API=true for controller-manager
  config/manager/manager.yaml
  test/e2e/config/azure-dev.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#5064 Use AKS Cluster as a management cluster for local dev
  .gitignore
  Makefile
  Tiltfile
  scripts/aks-as-mgmt.sh
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#5089 honor *-concurrency flags for ASO API controllers
  controllers/agentpooladopt_controller.go
  controllers/azureasomanagedcluster_controller.go
  controllers/azureasomanagedcontrolplane_controller.go
  controllers/azureasomanagedmachinepool_controller.go
  controllers/managedclusteradopt_controller.go
  main.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#5058 split cluster class/topology in e2e AKS templates
  templates/test/ci/cluster-template-prow-aks-clusterclass.yaml
  templates/test/ci/cluster-template-prow-aks-topology.yaml
  templates/test/ci/prow-aks-clusterclass/kustomization.yaml
  templates/test/ci/prow-aks-topology/kustomization.yaml
  templates/test/ci/prow-aks-topology/patches/cluster.yaml
  test/e2e/azure_test.go
  test/e2e/config/azure-dev.yaml
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#5012 Update managed vnet check logic
  azure/scope/cluster.go
  azure/scope/cluster_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#5092 Add omitempty to SSHPublicKey
  api/v1beta1/azuremachine_types.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm

#4869 Bump CAAPH to v0.2.5
  Makefile
  Tiltfile
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1_addon_provider/metadata.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#4949 fix: ensure Machines with delete-machine annotation are deleted first
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go
  azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#5061 add explicit --auth-mode login to az storage commands
  hack/ensure-azcli.sh
  scripts/ci-build-azure-ccm.sh
  scripts/ci-build-kubernetes.sh
  scripts/kind-with-registry.sh
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm
