Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2024-02, with the labels that each got.

#4129 Support for auto upgrade channel
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook_test.go
  api/v1beta1/types_class.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedcontrolplane_test.go
  azure/scope/managedmachinepool.go
  azure/scope/managedmachinepool_test.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/managedclusters_test.go
  azure/services/managedclusters/mock_managedclusters/managedclusters_mock.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
  util/versions/version.go
  util/versions/version_test.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, priority/important-soon, approved, lgtm

#4526 Add Jonathan Tong to maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4245 Support for managed cluster security profile
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook.go
  api/v1beta1/types_class.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/managedcontrolplane.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
  docs/book/src/topics/managedcluster.md
Labels: kind/feature, cncf-cla: yes, release-note, priority/important-soon, approved, size/XXL, lgtm

#4253 Support deploying an azure infra cluster using a single subnet for both control plane and worker nodes.
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azurecluster_default_test.go
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/azurecluster_validation_test.go
  api/v1beta1/azureclustertemplate_default.go
  api/v1beta1/azureclustertemplate_default_test.go
  api/v1beta1/types.go
  api/v1beta1/types_class.go
  api/v1beta1/types_template.go
  azure/scope/cluster.go
  azure/scope/machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclustertemplates.yaml
  controllers/helpers.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, priority/important-soon, approved, lgtm

#4532 fix subnet test check by ignoring order
  api/v1beta1/azurecluster_validation_test.go
Labels: cncf-cla: yes, size/XS, kind/flake, release-note-none, approved, lgtm

#4531 only consider spec in existing when reconciling ASO tags
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
  azure/services/aso/interfaces.go
  azure/services/aso/mock_aso/aso_mock.go
  azure/services/aso/tags.go
  azure/services/aso/tags_test.go
  azure/services/groups/spec.go
  azure/services/managedclusters/spec.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#4533 Use main for cluster-api-azure-controller' tag
  config/capz/manager_image_patch.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4541 [release-1.13] only consider spec in existing when reconciling ASO tags
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
  azure/services/aso/interfaces.go
  azure/services/aso/mock_aso/aso_mock.go
  azure/services/aso/tags.go
  azure/services/aso/tags_test.go
  azure/services/groups/spec.go
  azure/services/managedclusters/spec.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#4544 cut v1.12.3
  CHANGELOG/v1.12.3.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4545 cut v1.13.1
  CHANGELOG/v1.13.1.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4546 Bump k8s release tool to include link fix
  Makefile
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4522 Add support for Azure CNI Powered by Cilium
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook_test.go
  api/v1beta1/types_class.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/managedcontrolplane.go
  azure/services/managedclusters/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#4543 partition aks e2e tests to parallelize
  test/e2e/azure_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4548 Bump cert-manager to v1.14.1
  Tiltfile
  hack/install-cert-manager.sh
Labels: kind/feature, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4503 make ServiceCIDR independent in ManagedPools
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#4539 Exercise spotVMOptions in E2E tests
  templates/test/ci/cluster-template-prow-spot.yaml
  templates/test/ci/prow-spot/kustomization.yaml
  templates/test/ci/prow-spot/patches/spot-vm-options.yaml
  test/e2e/azure_test.go
  test/e2e/config/azure-dev.yaml
Labels: kind/bug, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4551 enable ASO in creating configMap for OIDC Issuer URL
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  docs/book/src/topics/managedcluster.md
  templates/cluster-template-aks.yaml
  templates/flavors/aks/cluster-template.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, lgtm

#4554 Make PlatformFaultDomainCount & ZoneBalance configurable on AzureMachinePools
  azure/scope/machinepool.go
  azure/services/scalesets/scalesets_test.go
  azure/services/scalesets/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  exp/api/v1beta1/azuremachinepool_types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#4552 Bump cert-manager to v1.14.2
  Tiltfile
  hack/install-cert-manager.sh
Labels: kind/feature, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4565 update dependabot ignores
  .github/dependabot.yml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4555 Restore AMMP-converges-to-failed-ready test spec
  test/e2e/aks_public_ip_prefix.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4547 let ASO install CRDs
  config/aso/kustomization.yaml
  docs/book/src/topics/aso.md
  docs/book/src/topics/getting-started.md
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, lgtm

#4569 Set PlatformFaultDomainCount if VMSS flex is enabled
  azure/services/scalesets/spec.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#4573 fix broken link
  docs/book/src/developers/development.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#4304 add proposal for automating AKS features
  docs/proposals/20231122-automate-aks-features.md
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, kind/proposal

#4581 update Makefile with versions from gomod for kind and envsubst
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4572 allow adding pre-existing privateDNSZone to AKS clusters
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook.go
  api/v1beta1/types_class.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#4584 wait for cluster to be Ready before hitting API server
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4586 [release-1.12] Bump CAPI to v1.5.6
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4527 Add patches fields for AKS resources
  api/v1beta1/types_class.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/managedcontrolplane.go
  azure/scope/managedmachinepool.go
  azure/services/agentpools/spec.go
  azure/services/aso/aso.go
  azure/services/aso/aso_test.go
  azure/services/aso/interfaces.go
  azure/services/aso/mock_aso/aso_mock.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepooltemplates.yaml
  go.mod
  test/e2e/aks_patches.go
  test/e2e/azure_clusterproxy.go
  test/e2e/azure_test.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, lgtm

#4528 Include CAAPH in CAPI API version upgrade test
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4585 Bump CAPI to v1.6.2
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4590 [release-1.13] Bump CAPI to v1.6.2
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4591 Add changelog for CAPZ v1.12.4
  CHANGELOG/v1.12.4.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4592 Add changelog for CAPZ v1.13.2
  CHANGELOG/v1.13.2.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4589 Bump golangci-lint to 1.55.2
  .golangci.yml
  Makefile
  api/v1beta1/azurecluster_validation_test.go
  api/v1beta1/azuremachine_default_test.go
  api/v1beta1/azuremachine_validation_test.go
  api/v1beta1/azuremanagedcontrolplane_default_test.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  azure/converters/identity_test.go
  azure/converters/image_test.go
  azure/converters/spotinstances_test.go
  azure/scope/cluster_test.go
  azure/scope/machinepool_test.go
  azure/scope/machinepoolmachine_test.go
  azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy_test.go
  azure/services/agentpools/spec_test.go
  azure/services/aso/aso_test.go
  azure/services/groups/groups_test.go
  azure/services/inboundnatrules/inboundnatrules_test.go
  azure/services/managedclusters/spec_test.go
  azure/services/virtualmachines/spec_test.go
  azure/services/virtualmachines/virtualmachines.go
  azure/services/virtualmachines/virtualmachines_test.go
  controllers/azurecluster_controller.go
  controllers/azurecluster_controller_test.go
  controllers/azurejson_machinepool_controller_test.go
  controllers/azuremachine_controller.go
  controllers/azuremachine_controller_test.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedcontrolplane_controller_test.go
  controllers/azuremanagedmachinepool_controller.go
  exp/api/v1beta1/azuremachinepool_default_test.go
  exp/api/v1beta1/azuremachinepool_test.go
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/azuremachinepool_controller_test.go
  pkg/coalescing/reconciler.go
  test/e2e/aks.go
  test/e2e/aks_azure_cluster_autoscaler.go
  test/e2e/azure_csidriver.go
  test/e2e/azure_failuredomains.go
  test/e2e/azure_machinepools.go
  test/e2e/azure_privatecluster.go
  test/e2e/azure_securitygroups.go
  test/e2e/azure_test.go
  test/e2e/azure_vmextensions.go
  test/e2e/cni.go
  test/e2e/conformance_test.go
  test/e2e/daemonsets.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_suite_vars.go
  test/e2e/gpu_operator.go
  util/cache/ttllru/ttllru_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm
