Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2024-12, with the labels that each got.

#5311 Use feature flag to create internal LB
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/machine.go
  azure/scope/machine_test.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, lgtm

#5322 Bump CAPI Visualizer to v1.4.0
  hack/observability/cluster-api-visualizer/chart/Chart.yaml
  hack/observability/cluster-api-visualizer/chart/templates/service.yaml
  hack/observability/cluster-api-visualizer/chart/values.yaml
  hack/observability/cluster-api-visualizer/fetch-visualizer-resources.sh
Labels: kind/feature, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#5320 Improve pre-commit UX
  .pre-commit-config.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#5292 MachinePool always update vmssState
  azure/services/scalesets/scalesets.go
  azure/services/scalesets/scalesets_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#5319 docs: Getting Started first cluster focuses on AKS ASO
  docs/book/src/getting-started.md
Labels: cncf-cla: yes, size/M, release-note, approved, kind/documentation, lgtm

#5329 Improve pre-commit UX part 2
  .pre-commit-config.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5111 Set default values in API rather than in webhooks
  api/v1beta1/azuremachine_default.go
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/azuremachinetemplate_webhook.go
  api/v1beta1/azuremachinetemplate_webhook_test.go
  api/v1beta1/azuremanagedcontrolplane_default.go
  api/v1beta1/azuremanagedcontrolplane_default_test.go
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/azuremanagedcontrolplanetemplate_default.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook_test.go
  api/v1beta1/azuremanagedmachinepool_webhook_test.go
  api/v1beta1/types.go
  api/v1beta1/types_class.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepooltemplates.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, ok-to-test, lgtm

#5341 Add note for fleetsMember reference in ASOManagedCluster
  docs/book/src/managed/managedcluster.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#5330 [release-1.16] Bump CAPI to v1.7.9
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5351 Bump otel to v1.33.0/v0.55.0
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#5306 Update Tiltfile to use env variable to check aks cluster is being used
  Makefile
  Tiltfile
Labels: cncf-cla: yes, size/XS, release-note-none, approved, ok-to-test, lgtm
