Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2024-11, with the labels that each got.

#5200 Add the ability to auth via certs without storing them in etcd secret
  api/v1beta1/azureclusteridentity_types.go
  azure/scope/identity.go
  azure/scope/identity_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
  controllers/asosecret_controller.go
  controllers/asosecret_controller_test.go
  docs/book/src/topics/identities.md
  test/setup/certificate
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#5227 refactor can_reuse_artifacts for cloud-provider artifacts
  scripts/ci-build-azure-ccm.sh
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4575 Add Flatcar Container Linux sysext templates
  docs/book/src/self-managed/flatcar.md
  templates/addons/cluster-api-helm/cloud-provider-azure-flatcar-sysext.yaml
  templates/cluster-template-flatcar-sysext.yaml
  templates/flavors/flatcar-sysext/kustomization.yaml
  templates/flavors/flatcar-sysext/machine-deployment.yaml
  templates/flavors/flatcar-sysext/patches/kubeadm-controlplane.yaml
  templates/test/ci/cluster-template-prow-flatcar-sysext.yaml
  templates/test/ci/patches/cluster-label-cloud-provider-azure-flatcar-sysext.yaml
  templates/test/ci/prow-flatcar-sysext/kustomization.yaml
  test/e2e/azure_test.go
  test/e2e/config/azure-dev.yaml
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, ok-to-test, lgtm

#5231 Revert "simplify DRA config for containerd"
  templates/test/ci/cluster-template-prow-ci-version-dra.yaml
  templates/test/ci/patches/dra-kubeadmconfig.yaml
  templates/test/ci/patches/dra-kubeadmcontrolplane.yaml
  templates/test/dev/cluster-template-custom-builds-dra.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#5232 fix kustomize warnings for deprecated patchesStrategicMerge
  templates/flavors/flatcar-sysext/kustomization.yaml
  templates/test/ci/prow-flatcar-sysext/kustomization.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5224 add nawazkh to maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5230 [release-1.17] re-enable AKS BYO node test
  test/e2e/aks_byo_node.go
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#5225 translate machine-pool-ci-version KubeadmConfig merge patch to JSON patch
  templates/test/ci/prow-machine-pool-ci-version/kustomization.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/kubeadm-bootstrap-k8s-ci-binaries.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#5238 skip prealloc linter
  .golangci.yml
  azure/services/subnets/spec.go
  controllers/resource_reconciler.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#5210 Update self-managed templates to use internal LB for node-to-node communication
  templates/cluster-template-aad.yaml
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-ipv6.yaml
  templates/cluster-template-nvidia-gpu.yaml
  templates/flavors/aad/kustomization.yaml
  templates/flavors/azure-bastion/kustomization.yaml
  templates/flavors/azure-bastion/machine-deployment.yaml
  templates/flavors/azure-cni-v1/kustomization.yaml
  templates/flavors/azure-cni-v1/machine-deployment.yaml
  templates/flavors/default/kustomization.yaml
  templates/flavors/dual-stack/kustomization.yaml
  templates/flavors/edgezone/kustomization.yaml
  templates/flavors/edgezone/machine-deployment.yaml
  templates/flavors/ephemeral/kustomization.yaml
  templates/flavors/ephemeral/machine-deployment.yaml
  templates/flavors/flatcar/kustomization.yaml
  templates/flavors/ipv6/kustomization.yaml
  templates/flavors/nvidia-gpu/kustomization.yaml
  templates/internal-load-balancer/azure-cluster-frontend-ip.yaml
  templates/internal-load-balancer/kubeadm-config-template-worker-node.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, lgtm

#5242 Remove deprecated HPAContainerMetrics feature gate from templates
  templates/test/ci/cluster-template-prow-ci-version-dra.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/patches/controller-manager-featuregates.yaml
  templates/test/ci/patches/dra-kubeadmcontrolplane.yaml
  templates/test/ci/prow-ci-version/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds-dra.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/kustomization.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#5266 Default to Marketplace images for old Kubernetes versions
  azure/services/virtualmachineimages/images.go
  azure/services/virtualmachineimages/images_test.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm, kind/failing-test

#5244 [release-1.16] Remove deprecated HPAContainerMetrics feature gate from templates
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/patches/controller-manager-featuregates.yaml
  templates/test/ci/prow-ci-version/kustomization.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/kustomization.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#5270 chore: support registry overrides in makefile
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5255 Bump CAPI to v1.8.5
  .pre-commit-config.yaml
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5274 make Private IP of the internal LB of the API Server configurable
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azurecluster_default_test.go
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/azurecluster_validation_test.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#5276 [release-1.17] Bump CAPI to v1.8.5
  .pre-commit-config.yaml
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5277 fix ServicePrincipalCertificate not reading from Secret
  azure/scope/identity.go
  azure/scope/identity_test.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#5211 handle Entra auth for ASO API managed clusters
  azure/credential_cache.go
  azure/credential_cache_test.go
  azure/interfaces.go
  azure/mock_azure/azure_mock.go
  controllers/aso_credential_cache.go
  controllers/aso_credential_cache_test.go
  controllers/azureasomanagedcontrolplane_controller.go
  controllers/azureasomanagedcontrolplane_controller_test.go
  docs/book/src/managed/asomanagedcluster.md
  main.go
Labels: kind/bug, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#5284 fix ever-accumulating memory in logger
  util/tele/span_logger.go
  util/tele/span_logger_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#5256 [release-1.16] Bump CAPI to v1.7.8
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5263 template/flatcar-sysext: use marketplace images
  docs/book/src/self-managed/flatcar.md
  templates/cluster-template-flatcar-sysext.yaml
  templates/flavors/flatcar-sysext/machine-deployment.yaml
  templates/flavors/flatcar-sysext/patches/kubeadm-controlplane.yaml
  templates/test/ci/cluster-template-prow-flatcar-sysext.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5298 cut v1.17.2
  CHANGELOG/v1.17.2.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#5295 Revert "make Private IP of the internal LB of the API Server configurable"
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azurecluster_default_test.go
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/azurecluster_validation_test.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
Labels: cncf-cla: yes, size/L, do-not-merge/release-note-label-needed, lgtm

#5300 Revert "Update self-managed templates to use internal LB for node-to-node communication"
  templates/cluster-template-aad.yaml
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-ipv6.yaml
  templates/cluster-template-nvidia-gpu.yaml
  templates/flavors/aad/kustomization.yaml
  templates/flavors/azure-bastion/kustomization.yaml
  templates/flavors/azure-bastion/machine-deployment.yaml
  templates/flavors/azure-cni-v1/kustomization.yaml
  templates/flavors/azure-cni-v1/machine-deployment.yaml
  templates/flavors/default/kustomization.yaml
  templates/flavors/default/patches/control-plane.yaml
  templates/flavors/default/patches/kubeadm-config-template.yaml
  templates/flavors/dual-stack/kustomization.yaml
  templates/flavors/edgezone/kustomization.yaml
  templates/flavors/edgezone/machine-deployment.yaml
  templates/flavors/ephemeral/kustomization.yaml
  templates/flavors/ephemeral/machine-deployment.yaml
  templates/flavors/flatcar/kustomization.yaml
  templates/flavors/ipv6/kustomization.yaml
  templates/flavors/nvidia-gpu/kustomization.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
Labels: cncf-cla: yes, size/L, do-not-merge/release-note-label-needed, lgtm

#5305 add docs on migrating to new ASO API
  .markdownlinkcheck.json
  docs/book/src/managed/adopting-clusters.md
  docs/book/src/managed/asomanagedcluster.md
Labels: cncf-cla: yes, size/M, release-note, approved, kind/documentation, lgtm

#5312 rearrange cherry-pick candidate field
  .github/pull_request_template.md
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4611 enable the use of an external control plane
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azurecluster_default_test.go
  api/v1beta1/azurecluster_types.go
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/azurecluster_validation_test.go
  api/v1beta1/azureclustertemplate_validation.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/scope/machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  controllers/azurecluster_controller.go
  controllers/azurecluster_reconciler.go
  controllers/azuremachine_controller_test.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, ok-to-test, lgtm

#5304 Create and add InternalILB as a CAPZ feature flag
  Makefile
  config/manager/manager.yaml
  docs/book/src/developers/development.md
  feature/feature.go
  hack/observability/opentelemetry/controller-manager-patch.yaml
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, lgtm
