Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2024-07, with the labels that each got.

#4956 fix RBAC upgrade
  Makefile
  config/rbac/aggregation_role.yaml
  config/rbac/capz_manager_role_patch.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#4928 feat: support OSDisk.DiffDiskPlacement
  api/v1beta1/azuremachine_validation.go
  api/v1beta1/azuremachine_validation_test.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/converters/spotinstances_test.go
  azure/services/scalesets/spec.go
  azure/services/scalesets/spec_test.go
  azure/services/virtualmachines/spec.go
  azure/services/virtualmachines/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  exp/api/v1beta1/azuremachinepool_default.go
  exp/api/v1beta1/azuremachinepool_default_test.go
  exp/api/v1beta1/azuremachinepool_test.go
  exp/api/v1beta1/azuremachinepool_webhook.go
  exp/api/v1beta1/azuremachinepool_webhook_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#4962 Use Standard tier SKU for AKS e2e tests
  hack/util.sh
  templates/test/ci/cluster-template-prow-aks-aso.yaml
  templates/test/ci/cluster-template-prow-aks-clusterclass.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
  templates/test/ci/prow-aks-aso/kustomization.yaml
  templates/test/ci/prow-aks-clusterclass/kustomization.yaml
  templates/test/ci/prow-aks-clusterclass/patches/sku.yaml
  templates/test/ci/prow-aks/kustomization.yaml
  templates/test/ci/prow-aks/patches/sku.yaml
Labels: cncf-cla: yes, kind/flake, size/M, release-note-none, approved, lgtm

#4963 [release-1.15] Use Standard tier SKU for AKS e2e tests
  hack/util.sh
  templates/test/ci/cluster-template-prow-aks-aso.yaml
  templates/test/ci/cluster-template-prow-aks-clusterclass.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
  templates/test/ci/prow-aks-aso/kustomization.yaml
  templates/test/ci/prow-aks-clusterclass/kustomization.yaml
  templates/test/ci/prow-aks-clusterclass/patches/sku.yaml
  templates/test/ci/prow-aks/kustomization.yaml
  templates/test/ci/prow-aks/patches/sku.yaml
Labels: cncf-cla: yes, kind/flake, size/M, release-note-none, approved, lgtm

#4971 Don't reuse windows cnm image if it has os.version set
  scripts/ci-build-azure-ccm.sh
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#4972 bump AKS preview API version to 2023-11-02-preview
  azure/services/agentpools/agentpools_test.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/managedclusters/managedclusters_test.go
  azure/services/managedclusters/spec.go
  azure/services/managedclusters/spec_test.go
  controllers/azuremanagedmachinepool_reconciler.go
  exp/mutators/azureasomanagedcontrolplane_test.go
  test/e2e/aks_patches.go
  test/e2e/azure_clusterproxy.go
Labels: kind/feature, cncf-cla: yes, size/S, release-note, approved, lgtm

#4969 move ASOAPI out of experimental
  api/v1alpha1/azureasomanagedcluster_types.go
  api/v1alpha1/azureasomanagedcluster_webhook.go
  api/v1alpha1/azureasomanagedclustertemplate_types.go
  api/v1alpha1/azureasomanagedcontrolplane_types.go
  api/v1alpha1/azureasomanagedcontrolplane_webhook.go
  api/v1alpha1/azureasomanagedcontrolplanetemplate_types.go
  api/v1alpha1/azureasomanagedmachinepool_types.go
  api/v1alpha1/azureasomanagedmachinepool_webhook.go
  api/v1alpha1/azureasomanagedmachinepooltemplate_types.go
  api/v1alpha1/doc.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/webhook/manifests.yaml
  controllers/agentpooladopt_controller.go
  controllers/azureasomanagedcluster_controller.go
  controllers/azureasomanagedcluster_controller_test.go
  controllers/azureasomanagedcontrolplane_controller.go
  controllers/azureasomanagedcontrolplane_controller_test.go
  controllers/azureasomanagedmachinepool_controller.go
  controllers/azureasomanagedmachinepool_controller_test.go
  controllers/managedclusteradopt_controller.go
  controllers/resource_reconciler.go
  controllers/resource_reconciler_test.go
  docs/book/install-and-build.sh
  docs/book/src/SUMMARY.md
  docs/book/src/reference/v1alpha1-api.md
  docs/book/src/reference/v1alpha1-exp-api.md
  docs/book/src/topics/aso.md
  feature/feature.go
  main.go
  pkg/mutators/azureasomanagedcontrolplane.go
  pkg/mutators/azureasomanagedcontrolplane_test.go
  pkg/mutators/azureasomanagedmachinepool.go
  pkg/mutators/azureasomanagedmachinepool_test.go
  pkg/mutators/mutator.go
  pkg/mutators/mutator_test.go
  test/e2e/aks.go
  test/e2e/aks_machinepools.go
  test/e2e/azure_clusterproxy.go
  test/e2e/azure_logcollector.go
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, lgtm

#4939 Use workload identity for azure cli when Federated token file is present
  hack/ensure-acr-login.sh
  hack/ensure-azcli.sh
  scripts/ci-build-azure-ccm.sh
  scripts/ci-build-kubernetes.sh
  scripts/kind-with-registry.sh
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, lgtm

#4974 Bump CAPI to v1.7.4
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4980 Use the env AZURE_STORAGE_AUTH_MODE when using federated auth
  hack/ensure-azcli.sh
  scripts/ci-build-azure-ccm.sh
  scripts/ci-build-kubernetes.sh
  scripts/kind-with-registry.sh
Labels: kind/bug, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#4981 bump google.golang.org/grpc to v1.64.1
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#4979 [release-1.15] Bump CAPI to v1.7.4
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4975 [release-1.14] Bump CAPI to v1.6.7
  .github/workflows/cover.yaml
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4973 bump ASO to v2.8.0
  .github/workflows/cover.yaml
  .github/workflows/dependabot-code-gen.yml
  .github/workflows/scan.yml
  .golangci.yml
  Dockerfile
  Makefile
  Tiltfile
  config/aso/crds.yaml
  config/aso/kustomization.yaml
  config/aso/settings.yaml
  docs/book/src/developers/development.md
  go.mod
  go.sum
  hack/ensure-go.sh
  main.go
  netlify.toml
Labels: kind/feature, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#4978 remove service principal references from CI
  Makefile
  hack/create-custom-cloud-provider-config.sh
  hack/create-dev-cluster.sh
  hack/create-identity-secret.sh
  hack/ensure-azcli.sh
  hack/parse-prow-creds.sh
  scripts/ci-build-azure-ccm.sh
  scripts/ci-build-kubernetes.sh
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  scripts/ci-entrypoint.sh
  templates/azure-cluster-identity/azure-cluster-identity-sp.yaml
  templates/test/ci/patches/azureclusteridentity-azwi.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds/kustomization.yaml
  templates/test/dev/custom-builds/patches/azure-cluster-identity-user-assigned.yaml
  test/e2e/azure_selfhosted.go
  test/e2e/azure_test.go
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/conformance_test.go
  test/e2e/data/infrastructure-azure/v1.14.5/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.15.1/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template/kustomization.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, lgtm

#4983 use Watches from controller builder instead of Watch method
  controllers/asosecret_controller.go
  controllers/azurecluster_controller.go
  controllers/azurejson_machine_controller.go
  controllers/azurejson_machinepool_controller.go
  controllers/azuremachine_controller.go
  controllers/azuremanagedcluster_controller.go
  controllers/azuremanagedcontrolplane_controller.go
  controllers/azuremanagedmachinepool_controller.go
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/azuremachinepoolmachine_controller.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4986 Add release 1.16 to metadata.yaml
  metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4987 Add changelog for v1.14.7
  CHANGELOG/v1.14.7.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4988 Add changelog for v1.15.3
  CHANGELOG/v1.15.3.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4989 Add changelog for v1.16.0
  CHANGELOG/v1.16.0.md
Labels: cncf-cla: yes, size/L, release-note-none, approved, kind/documentation, lgtm

#4993 [release-1.15] add explicit namespace to ci-entrypoint flow
  Makefile
  hack/create-custom-cloud-provider-config.sh
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#4992 use managed identity for API version upgrade e2e tests
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/prow/kustomization.yaml
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.14.5/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.15.1/cluster-template-prow.yaml
Labels: cncf-cla: yes, release-note-none, approved, size/XXL, lgtm, kind/failing-test

#4999 [release-1.15] add namespace to identity secret kubectl commands
  hack/create-identity-secret.sh
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#4994 Update provider metadata and API upgrade test versions
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.15.3/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.16.0/cluster-template-prow.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5003 Update e2e test regions for community sub
  hack/util.sh
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#5000 use managed identity for CAPI self-hosted e2e test
  azure/scope/clients.go
  azure/scope/identity.go
  test/e2e/azure_selfhosted.go
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template/kustomization.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#4998 drop Local only env var
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note, approved, lgtm

#5011 ci-entrypoint: don't reset kind cluster before getting logs
  hack/create-dev-cluster.sh
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#5013 log transient AzureMachinePool errors at info level
  exp/controllers/azuremachinepool_controller.go
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5020 don't rollout VMSS model updates when tags change
  azure/const.go
  azure/defaults.go
  azure/scope/machinepool.go
  azure/types.go
  azure/types_test.go
  exp/controllers/azuremachinepool_reconciler.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#5016 Skip optional GPU-enabled test since sub has no quota
  test/e2e/azure_test.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#5023 update default custom cloud provider config for managed identity
  hack/create-custom-cloud-provider-config.sh
  templates/test/ci/default-custom-cloud-provider-config.json
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm

#5025 add timeout to infinite loop in ci-entrypoint.sh
  scripts/ci-entrypoint.sh
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4959 AzureMachinePoolMachine remove finalizer and avoid recreation if VMSS is deleting
  azure/scope/machinepool.go
  azure/scope/machinepool_test.go
  exp/controllers/azuremachinepoolmachine_controller.go
  exp/controllers/azuremachinepoolmachine_controller_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#5026 Update regions for new sub based on failures
  hack/util.sh
  templates/test/ci/cluster-template-prow-aks-clusterclass.yaml
  templates/test/ci/cluster-template-prow-aks.yaml
  templates/test/ci/prow-aks-clusterclass/patches/aks-clusterclass-pool0.yaml
  templates/test/ci/prow-aks/patches/aks-pool0.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, do-not-merge/hold, lgtm, kind/failing-test

#5042 increase linter timeout from 1m0s to 8m0s
  Makefile
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, kind/failing-test

#5040 Update kind-with-registry.sh
  scripts/kind-with-registry.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm
