Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2024-05, with the labels that each got.

#4793 ASOAPI: add resource mutator framework
  exp/controllers/azureasomanagedcluster_controller.go
  exp/controllers/azureasomanagedcontrolplane_controller.go
  exp/controllers/azureasomanagedmachinepool_controller.go
  exp/mutators/azureasomanagedcontrolplane.go
  exp/mutators/azureasomanagedcontrolplane_test.go
  exp/mutators/mutator.go
  exp/mutators/mutator_test.go
Labels: kind/bug, cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#4735 Don't include vnet name in template type
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/azuremanagedcontrolplanetemplate_default.go
  api/v1beta1/azuremanagedcontrolplanetemplate_default_test.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook.go
  api/v1beta1/azuremanagedcontrolplanetemplate_webhook_test.go
  api/v1beta1/types_class.go
  azure/scope/managedcontrolplane_test.go
  azure/scope/managedmachinepool_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
  controllers/azuremanagedcontrolplane_controller_test.go
  docs/book/src/topics/clusterclass.md
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#4794 ASOAPI: aggregate agentPoolProfiles for ManagedCluster create
  exp/controllers/azureasomanagedcontrolplane_controller.go
  exp/mutators/azureasomanagedcontrolplane.go
  exp/mutators/azureasomanagedcontrolplane_test.go
  main.go
  templates/cluster-template-aks-aso-clusterclass.yaml
  templates/cluster-template-aks-aso.yaml
  templates/flavors/aks-aso-clusterclass/clusterclass.yaml
  templates/flavors/aks-aso/cluster-template.yaml
  templates/test/ci/cluster-template-prow-aks-aso.yaml
Labels: kind/bug, cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#4798 ASOAPI: propagate machinepool values to ManagedClustersAgentPools
  exp/api/v1alpha1/azureasomanagedmachinepool_types.go
  exp/controllers/azureasomanagedmachinepool_controller.go
  exp/controllers/azureasomanagedmachinepool_controller_test.go
  exp/mutators/azureasomanagedcontrolplane.go
  exp/mutators/azureasomanagedcontrolplane_test.go
  exp/mutators/azureasomanagedmachinepool.go
  exp/mutators/azureasomanagedmachinepool_test.go
  templates/cluster-template-aks-aso.yaml
  templates/flavors/aks-aso/cluster-template.yaml
  templates/test/ci/cluster-template-prow-aks-aso.yaml
  templates/test/ci/prow-aks-aso/patches/aks-pool2.yaml
Labels: kind/bug, cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#4784 restore manager bootstrap creds for subscription ID
  config/capz/credentials.yaml
  config/capz/kustomization.yaml
  config/capz/manager_credentials_patch.yaml
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, lgtm

#4797 update go-apidiff
  Makefile
  scripts/ci-apidiff.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4795 remove unneeded code copied from CAPI
  go.mod
  main.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4803 ASOAPI: add pause handling
  exp/controllers/azureasomanagedcluster_controller.go
  exp/controllers/azureasomanagedcluster_controller_test.go
  exp/controllers/azureasomanagedcontrolplane_controller.go
  exp/controllers/azureasomanagedcontrolplane_controller_test.go
  exp/controllers/azureasomanagedmachinepool_controller.go
  exp/controllers/azureasomanagedmachinepool_controller_test.go
  exp/controllers/resource_reconciler.go
  exp/controllers/resource_reconciler_test.go
  exp/mutators/mutator.go
  exp/mutators/mutator_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4776 Clean up Azure AD Workload ID docs
  docs/book/src/topics/workload-identity.md
Labels: cncf-cla: yes, size/L, release-note-none, approved, kind/documentation, lgtm

#4812 Revert "use az to download storage blobs for custom builds"
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-kcp.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider-win.yaml
  templates/test/ci/prow-ci-version/patches/oot-credential-provider.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/kubeadm-bootstrap-windows-k8s-ci-binaries.yaml
  templates/test/ci/prow-machine-pool-ci-version/patches/machine-pool-ci-version.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/custom-builds.yaml
  templates/test/dev/custom-builds-machine-pool/patches/kubeadm-bootstrap-machine-pool-windows-k8s-pr-binaries.yaml
  templates/test/dev/patches/control-plane-custom-builds.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4799 ASOAPI: basic automated adoption
  config/rbac/role.yaml
  docs/book/src/topics/managedcluster.md
  exp/controllers/agentpooladopt_controller.go
  exp/controllers/managedclusteradopt_controller.go
  exp/mutators/azureasomanagedcontrolplane.go
  exp/mutators/azureasomanagedcontrolplane_test.go
  main.go
  templates/cluster-template-aks-aso-clusterclass.yaml
  templates/cluster-template-aks-aso.yaml
  templates/flavors/aks-aso-clusterclass/clusterclass.yaml
  templates/flavors/aks-aso/cluster-template.yaml
  templates/test/ci/cluster-template-prow-aks-aso.yaml
Labels: kind/feature, cncf-cla: yes, size/XL, release-note-none, approved, lgtm

#4810 ASOAPI: delete resources removed from spec
  exp/api/v1alpha1/azureasomanagedcluster_types.go
  exp/api/v1alpha1/azureasomanagedcontrolplane_types.go
  exp/api/v1alpha1/azureasomanagedmachinepool_types.go
  exp/controllers/resource_reconciler.go
  exp/controllers/resource_reconciler_test.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm

#4725 Allow upper-case resource names
  azure/services/agentpools/spec.go
  azure/services/aksextensions/spec.go
  azure/services/bastionhosts/spec.go
  azure/services/groups/groups.go
  azure/services/groups/spec.go
  azure/services/managedclusters/spec.go
  azure/services/natgateways/spec.go
  azure/services/privateendpoints/spec.go
  azure/services/privateendpoints/spec_test.go
  azure/services/subnets/spec.go
  azure/services/virtualnetworks/spec.go
  docs/book/src/topics/managedcluster.md
  test/e2e/aks_marketplace.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#4801 Use correct resource group for Bastion with custom vnet
  azure/scope/cluster.go
  azure/scope/cluster_test.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, lgtm

#4800 Don't allow fleetsMembers to have capital letters. Default spec.group.
  api/v1beta1/azuremanagedcontrolplane_default.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#4811 add e2e test for AzureASOManagedMachinePool scaling
  test/e2e/aks_machinepools.go
  test/e2e/azure_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4821 Add release v1.15 to metadata.yaml
  metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4820 [release-1.13] Don't allow fleetsMembers to have capital letters. Default spec.group.
  api/v1beta1/azuremanagedcontrolplane_default.go
  api/v1beta1/azuremanagedcontrolplane_webhook.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#4723 Allow setting ResourceGroupName in AzureManagedControlPlaneTemplate
  api/v1beta1/azuremanagedcontrolplane_types.go
  api/v1beta1/azuremanagedcontrolplane_webhook_test.go
  api/v1beta1/types_class.go
  azure/scope/managedcontrolplane_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
  controllers/azuremanagedcontrolplane_controller_test.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, lgtm

#4824 add release notes for CAPZ v1.13.6
  CHANGELOG/v1.13.6.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, do-not-merge/hold, lgtm

#4823 add release notes for CAPZ v1.15.0
  CHANGELOG/v1.15.0.md
Labels: cncf-cla: yes, size/L, release-note-none, approved, kind/documentation, lgtm

#4825 add release notes for CAPZ v1.14.4
  CHANGELOG/v1.14.4.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4827 fix authors for release notes for CAPZ v1.13.6
  CHANGELOG/v1.13.6.md
Labels: cncf-cla: yes, size/XS, release-note-none, approved, kind/documentation, lgtm

#4822 Enable E2E testing for v1.16 release cycle
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.14.4/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.15.0/cluster-template-prow.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#4826 Add willie-yao to project maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4819 Check UserManaged is not nil in azure/converters/diagnostics
  azure/converters/diagnostics.go
  azure/converters/diagnostics_test.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, ok-to-test, lgtm

#4605 Deploy CAAPH controller manager in Tilt
  Tiltfile
Labels: kind/feature, cncf-cla: yes, size/M, release-note-none, approved, lgtm

#4833 Set cluster name label for pre-existing kubeconfig
  controllers/azuremanagedcontrolplane_reconciler.go
Labels: kind/bug, cncf-cla: yes, size/S, release-note, approved, lgtm

#4830 Update godoc of CapacityReservationGroupID of AzureMachineSpec
  api/v1beta1/azuremachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, ok-to-test, lgtm

#4845 workaround ASO User-Agent not getting set
  config/aso/kustomization.yaml
Labels: kind/bug, cncf-cla: yes, size/S, release-note-none, approved, lgtm

#4843 Group dependabot updates together for GitHub actions
  .github/dependabot.yml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4855 Bump CAPI to v1.7.2
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4861 Make dependabot ignore major and minor Prometheus go mod bumps
  .github/dependabot.yml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4858 [release-1.15] Bump CAPI to v1.7.2
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4856 [release-1.14] Bump CAPI to v1.6.5
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#4831 deprecate AzureClusterIdentity spec.resourceID
  api/v1beta1/azureclusteridentity_types.go
  api/v1beta1/azureclusteridentity_validation.go
  api/v1beta1/azureclusteridentity_webhook_test.go
  azure/scope/identity_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
  docs/book/src/topics/identities.md
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/prow-private/patches/user-assigned.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note, approved, lgtm

#4792 Add DisableExtensionOperations field
  api/v1beta1/azuremachine_types.go
  api/v1beta1/azuremachine_validation.go
  api/v1beta1/azuremachine_webhook.go
  api/v1beta1/azuremachine_webhook_test.go
  api/v1beta1/azuremachinetemplate_webhook.go
  api/v1beta1/azuremachinetemplate_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/services/virtualmachines/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm

#4871 Add changelog for CAPZ v1.14.5
  CHANGELOG/v1.14.5.md
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, kind/documentation, lgtm

#4872 Add changelog for CAPZ v1.15.1
  CHANGELOG/v1.15.1.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#4873 Update clusterctl API upgrade test versions
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.14.5/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.15.1/cluster-template-prow.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#4875 ASOAPI: add CI tags to ManagedCluster resource
  templates/test/ci/cluster-template-prow-aks-aso.yaml
  templates/test/ci/prow-aks-aso/kustomization.yaml
Labels: cncf-cla: yes, size/S, kind/flake, release-note-none, approved, lgtm

#4874 rearrange parallelism in AKS machine pool e2e tests
  test/e2e/aks_machinepools.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#4865 Bump e2e test k8s versions
  docs/book/src/topics/windows.md
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/patches/apiserver.yaml
  templates/test/ci/prow-edgezone/kustomization.yaml
  templates/test/ci/prow-workload-identity/kustomization.yaml
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.14.5/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.15.1/cluster-template-prow.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4886 [release-1.15] Bump e2e test k8s versions
  docs/book/src/topics/windows.md
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/patches/apiserver.yaml
  templates/test/ci/prow-edgezone/kustomization.yaml
  templates/test/ci/prow-workload-identity/kustomization.yaml
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.13.4/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.14.2/cluster-template-prow.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4888 Use envtest binaries from controller-tools repo
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#4887 [release-1.14] Bump e2e test k8s versions
  docs/book/src/topics/windows.md
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-workload-identity.yaml
  templates/test/ci/patches/apiserver.yaml
  templates/test/ci/prow-edgezone/kustomization.yaml
  templates/test/ci/prow-workload-identity/kustomization.yaml
  test/e2e/capi_test.go
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.12.2/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.13.0/cluster-template-prow.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#4884 Create reconcile test for azuremanagedcluster_controller
  controllers/azuremanagedcluster_controller_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, ok-to-test, lgtm
