Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2025-08, with the labels that each got.

#5795 Add startupProbe to ASO
  config/aso/kustomization.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5796 Fix issue with MANAGER_IMAGE being overwritten in conformance tests
  conformance.mk
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#5798 Run verify-security weekly as a GitHub action
  .github/workflows/scan.yml
  .github/workflows/weekly-security-scan.yaml
  Makefile
  hack/ensure-trivy.sh
  hack/verify-container-images.sh
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#5806 [release-1.19] Run verify-security weekly as a GitHub action
  .github/workflows/scan.yml
  .github/workflows/weekly-security-scan.yaml
  Makefile
  hack/ensure-trivy.sh
  hack/verify-container-images.sh
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#5807 [release-1.20] Run verify-security weekly as a GitHub action
  .github/workflows/scan.yml
  .github/workflows/weekly-security-scan.yaml
  Makefile
  hack/ensure-trivy.sh
  hack/verify-container-images.sh
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#5816 Fix disabling NAT gateway creation for `cluster` role subnets
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azurecluster_default_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#5818 add release 1.21 to CAPZ metadata
  metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5817 chore: AzureCluster subnet default flow comments
  api/v1beta1/azurecluster_default.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5819 Add specific tolerations to calico-typha pods
  templates/addons/cluster-api-helm/calico-dual-stack.yaml
  templates/addons/cluster-api-helm/calico-ipv6.yaml
  templates/addons/cluster-api-helm/calico.yaml
  templates/test/ci/cluster-template-prow-apiserver-ilb-custom-images.yaml
  templates/test/ci/cluster-template-prow-apiserver-ilb.yaml
  templates/test/ci/cluster-template-prow-ci-version-dra.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version-md-and-mp.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-clusterclass-ci-rke2.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar-sysext.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-spot.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-dra.yaml
  templates/test/dev/cluster-template-custom-builds-load-dra.yaml
  templates/test/dev/cluster-template-custom-builds-load.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool-load-dra.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool-load.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-upgrades.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
Labels: cncf-cla: yes, size/XL, kind/flake, release-note-none, approved, lgtm

#5833 Drop error condition from AKS node public IP prefix e2e test
  test/e2e/aks_public_ip_prefix.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#5835 fix: add missing kind field to metadata.yaml
  metadata.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, ok-to-test, lgtm
