Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2025-07, with the labels that each got.

#5739 Update CAPI and CAPZ versions in e2e testing
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.19.5/cluster-template-aks.yaml
  test/e2e/data/infrastructure-azure/v1.19.5/cluster-template-prow-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1.19.5/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.20.1/cluster-template-aks.yaml
  test/e2e/data/infrastructure-azure/v1.20.1/cluster-template-prow-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1.20.1/cluster-template-prow.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#5740 Add dra-specific tag for monitoring
  templates/test/dev/cluster-template-custom-builds-load-dra.yaml
  templates/test/dev/custom-builds-load-dra/kustomization.yaml
  templates/test/dev/custom-builds-load-dra/patches/azuremachinetemplate-monitoring.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5749 Define AZURE_LOCATION_LOAD for load test regions
  hack/util.sh
  scripts/ci-conformance.sh
  scripts/ci-entrypoint.sh
  templates/test/dev/cluster-template-custom-builds-load-dra.yaml
  templates/test/dev/cluster-template-custom-builds-load.yaml
  templates/test/dev/custom-builds-load/kustomization.yaml
  templates/test/dev/custom-builds-load/patches/location.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5754 [release-1.20] Upgrade node delete timeout
  templates/test/ci/patches/kcp-node-deletion-timeout.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in/kustomization.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-upgrades.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-upgrades/kustomization.yaml
Labels: cncf-cla: yes, size/S, kind/flake, release-note-none, approved, lgtm

#5552 Add support to disable CAPZ components through a manager flag
  api/v1beta1/types.go
  docs/book/src/self-managed/externally-managed-azure-infrastructure.md
  main.go
  util/components/disabled_components.go
  util/components/disabled_components_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, lgtm

#5756 Fix DRA conformance config
  test/e2e/data/kubetest/conformance-dra-ginkgo-v2.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#5772 CI: Always use AZURE_LOCATION
  scripts/ci-conformance.sh
  scripts/ci-entrypoint.sh
  templates/test/dev/cluster-template-custom-builds-load-dra.yaml
  templates/test/dev/cluster-template-custom-builds-load.yaml
  templates/test/dev/custom-builds-load/kustomization.yaml
  templates/test/dev/custom-builds-load/patches/location.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/failing-test

#5774 Add release notes for CAPZ v1.19.6
  CHANGELOG/v1.19.6.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#5571 Acknowledge all ASO resource types before creating
  api/v1alpha1/azureasomanagedcluster_types.go
  api/v1alpha1/azureasomanagedcontrolplane_types.go
  api/v1alpha1/azureasomanagedmachinepool_types.go
  controllers/azureasomanagedcluster_controller.go
  controllers/azureasomanagedcontrolplane_controller.go
  controllers/azureasomanagedcontrolplane_controller_test.go
  controllers/azureasomanagedmachinepool_controller.go
  controllers/resource_reconciler.go
  controllers/resource_reconciler_test.go
Labels: kind/bug, cncf-cla: yes, size/XL, release-note, approved, lgtm

#5790 Bump CAAPH to v0.3.2
  Makefile
  Tiltfile
  docs/book/src/developers/getting-started-with-capi-operator.md
  test/e2e/config/azure-dev.yaml
  test/e2e/data/shared/v1beta1_addon_provider/metadata.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5793 fix(observability): configure ServiceMonitor for ASO secure metrics authentication
  hack/observability/prometheus/resources/prometheus.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#5792 Reduce qps/burst for kube-controller-manager in DRA load test templates
  templates/test/ci/patches/dra-kubeadmcontrolplane-load.yaml
  templates/test/dev/cluster-template-custom-builds-load-dra.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool-load-dra.yaml
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm
