Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2025-04, with the labels that each got.

#5489 Add documentation and scripts on running e2e test locally
  Makefile
  docs/book/src/developers/development.md
  docs/book/src/developers/tilt-with-aks-as-mgmt-ilb.md
  e2e.mk
  scripts/aks-as-mgmt.sh
  scripts/peer-vnets.sh
  test/e2e/config/azure-dev.yaml
Labels: kind/feature, cncf-cla: yes, size/XL, release-note, approved, lgtm

#5535 Add test coverage for agentpooladopt controller
  controllers/agentpooladopt_controller_test.go
  controllers/azurejson_machinepool_controller_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#5540 fix: reuse global TracerProvider to avoid memory leak
  azure/defaults.go
  azure/scope/identity.go
  controllers/aso_credential_cache.go
  pkg/ot/traces.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#5543 chore: remove revive lint ignore statements
  azure/services/availabilitysets/client.go
  azure/services/networkinterfaces/client.go
  azure/services/roleassignments/client.go
  test/e2e/cni.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5530 Bump CAPI to v1.9.6
  Makefile
  Tiltfile
  docs/book/src/getting-started.md
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5553 [release-1.18] Bump CAPI to v1.9.6
  Makefile
  Tiltfile
  docs/book/src/getting-started.md
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5554 [release-1.19] Bump CAPI to v1.9.6
  Makefile
  Tiltfile
  docs/book/src/getting-started.md
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/azure-dev.yaml
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5559 Add release notes for v1.18.3
  CHANGELOG/v1.18.3.md
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5560 Add release notes for v1.19.2
  CHANGELOG/v1.19.2.md
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5565 Use crddoc tool to generate CRD documentation
  docs/book/install-and-build.sh
Labels: cncf-cla: yes, size/S, release-note-none, approved, lgtm, kind/failing-test

#5561 Bump Go toolchain to v1.23.8
  Dockerfile
  Tiltfile
  go.mod
  hack/tools/go.mod
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5556 fix: support ClusterCacheTracker
  config/manager/manager.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, approved, ok-to-test, lgtm

#5525 ✨ Allow more permissive extensibility for securityRules and additional CP LoadBalancers
  api/v1beta1/types.go
  api/v1beta1/types_template.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/scope/cluster.go
  azure/scope/cluster_test.go
  azure/services/loadbalancers/loadbalancers_test.go
  azure/services/loadbalancers/spec.go
  azure/services/loadbalancers/spec_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclustertemplates.yaml
  docs/book/src/self-managed/custom-vnet.md
  templates/cluster-template-clusterclass-rke2.yaml
  templates/flavors/clusterclass-rke2/azure-cluster-template.yaml
  templates/flavors/clusterclass-rke2/azure-machine-template-controlplane.yaml
  templates/flavors/clusterclass-rke2/azure-machine-template-worker.yaml
  templates/flavors/clusterclass-rke2/clusterclass.yaml
  templates/flavors/clusterclass-rke2/kustomization.yaml
  templates/flavors/clusterclass-rke2/rke2-config-template.yaml
  templates/flavors/clusterclass-rke2/rke2-controlplane-template.yaml
  templates/test/ci/cluster-template-prow-clusterclass-ci-rke2.yaml
  templates/test/ci/cluster-template-prow-topology-rke2.yaml
  templates/test/ci/prow-clusterclass-ci-rke2/ccm-patch.yaml
  templates/test/ci/prow-clusterclass-ci-rke2/kustomization.yaml
  templates/test/ci/prow-clusterclass-ci-rke2/patches.yaml
  templates/test/ci/prow-clusterclass-ci-rke2/rke2-config-template.yaml
  templates/test/ci/prow-clusterclass-ci-rke2/variables.yaml
  test/e2e/azure_test.go
  test/e2e/common.go
  test/e2e/config/azure-dev.yaml
Labels: kind/feature, cncf-cla: yes, tide/merge-method-squash, release-note, approved, size/XXL, lgtm

#5569 NIC should be try to fix itself when it is in ProvisioningFailed State
  azure/services/async/async.go
  azure/services/networkinterfaces/spec.go
  azure/services/networkinterfaces/spec_test.go
Labels: kind/bug, cncf-cla: yes, tide/merge-method-squash, size/L, release-note, approved, lgtm

#5509 Add flag to disable bootstrap extension and improve error message
  api/v1beta1/azuremachine_types.go
  api/v1beta1/azuremachine_webhook.go
  api/v1beta1/zz_generated.deepcopy.go
  azure/defaults.go
  azure/scope/machine.go
  azure/scope/machine_test.go
  azure/services/virtualmachines/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#5538 Add test for managedclusteradopt controller
  controllers/managedclusteradopt_controller_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#5597 [release-1.18] Only update the subnet spec if status ASO CIDRs not empty
  azure/services/subnets/subnets.go
  azure/services/subnets/subnets_test.go
  azure/services/virtualnetworks/virtualnetworks.go
  azure/services/virtualnetworks/virtualnetworks_test.go
Labels: kind/bug, cncf-cla: yes, size/L, release-note, approved, ok-to-test, lgtm
