Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2025-05, with the labels that each got.

#5587 [Tilt] Drop SUBSCRIPTION_TYPE, do not peer vnets for all flavors and update vnet peering logic
  Tiltfile
  docs/book/src/developers/tilt-with-aks-as-mgmt-ilb.md
Labels: cncf-cla: yes, tide/merge-method-squash, kind/cleanup, size/M, release-note-none, approved, lgtm

#5562 Remove deprecated field NumberOfProbes
  azure/services/loadbalancers/spec.go
  azure/services/loadbalancers/spec_test.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note, approved, ok-to-test, lgtm

#5588 add make target to reuse existing AKS Cluster as mgmt cluster
  Makefile
  scripts/reuse-existing-aks-cluster.sh
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#5613 add v1.18.4 changelog
  CHANGELOG/v1.18.4.md
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note, approved, lgtm

#5614 add v1.19.3 changelog
  CHANGELOG/v1.19.3.md
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note, approved, lgtm

#5603 fix AzCluster_default and AzCluster_validation webhooks
  api/v1beta1/azurecluster_default.go
  api/v1beta1/azurecluster_validation.go
  api/v1beta1/azurecluster_validation_test.go
  api/v1beta1/azureclustertemplate_default_test.go
Labels: cncf-cla: yes, tide/merge-method-squash, kind/cleanup, size/L, release-note-none, approved, lgtm

#5619 Add explanatory comments
  scripts/aks-as-mgmt.sh
Labels: cncf-cla: yes, size/S, tide/merge-method-squash, kind/cleanup, release-note-none, approved, lgtm

#5576 Feature/add aks-delete make target
  Makefile
  scripts/aks-delete.sh
Labels: kind/feature, cncf-cla: yes, tide/merge-method-squash, size/L, release-note, approved, ok-to-test, lgtm

#5621 Bump cert-manager to v1.17.2
  Tiltfile
  hack/install-cert-manager.sh
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5622 Enable new AKS API version with ASO API
  docs/book/src/managed/asomanagedcluster.md
  docs/book/src/managed/managed.md
  main.go
  templates/cluster-template-aks-aso-clusterclass.yaml
  templates/cluster-template-aks-aso.yaml
  templates/flavors/aks-aso-clusterclass/clusterclass.yaml
  templates/flavors/aks-aso/cluster-template.yaml
  templates/test/ci/cluster-template-prow-aks-aso.yaml
  templates/test/ci/prow-aks-aso/patches/aks-pool2.yaml
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#5632 add v1.19.4 changelog
  CHANGELOG/v1.19.4.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#5633 add v1.18.5 changelog
  CHANGELOG/v1.18.5.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#5634 upgrade release-notes tool to version v0.18.0
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5639 Remove community AKS marketplace extension from e2e tests because no longer valid
  docs/book/src/managed/managedcluster.md
  test/e2e/aks_marketplace.go
Labels: cncf-cla: yes, size/S, release-note, approved, ok-to-test, lgtm, kind/failing-test

#5641 update the windows kubeproxy pod priority level
  templates/addons/windows/calico/kube-proxy-windows.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-load.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
Labels: kind/bug, cncf-cla: yes, size/S, do-not-merge/release-note-label-needed, approved, lgtm

#5628 feat: add additionalCapabilities spec to az MPs to support UltraSSDs
  azure/scope/machinepool.go
  azure/services/resourceskus/sku.go
  azure/services/scalesets/spec.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  exp/api/v1beta1/azuremachinepool_types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#5638 Fix GO-2025-3488 security vulnerability
  go.mod
  go.sum
Labels: kind/bug, cncf-cla: yes, size/XS, tide/merge-method-squash, release-note, approved, lgtm

#5625 Refactor docs so quick start instructions are for creating an AKS man…
  docs/book/src/SUMMARY.md
  docs/book/src/developers/getting-started-with-capi-operator.md
  docs/book/src/getting-started-with-aks.md
Labels: cncf-cla: yes, size/L, release-note-none, approved, kind/documentation, ok-to-test, lgtm
