Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2025-09, with the labels that each got.

#5859 Update active branches for security scanner
  .github/workflows/weekly-security-scan.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5867 Don't take windows capi image versions into consideration if no windows machines
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5879 [release-1.21] Get GO_VERSION from toolchain statment
  Makefile
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5888 [release-1.21] update azidentity to v1.12.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note, approved, lgtm
