Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2025-10, with the labels that each got.

#5890 [release-1.20] Define NoSchedule tolerations for tigera-operator
  templates/addons/calico-dual-stack/values.yaml
  templates/addons/calico-ipv6/values.yaml
  templates/addons/calico/values.yaml
  templates/addons/cluster-api-helm/calico-dual-stack.yaml
  templates/addons/cluster-api-helm/calico-ipv6.yaml
  templates/addons/cluster-api-helm/calico.yaml
  templates/test/ci/cluster-template-prow-apiserver-ilb.yaml
  templates/test/ci/cluster-template-prow-ci-version-dra.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version-md-and-mp.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-clusterclass-ci-rke2.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar-sysext.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-spot.yaml
  templates/test/ci/cluster-template-prow-topology.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-dra.yaml
  templates/test/dev/cluster-template-custom-builds-load-dra.yaml
  templates/test/dev/cluster-template-custom-builds-load.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
Labels: cncf-cla: yes, size/XL, kind/flake, release-note-none, approved, lgtm

#5891 Dalec E2E: Use revision numbers from environment variables
  templates/test/ci/cluster-template-prow-dalec-custom-builds.yaml
  templates/test/ci/prow-dalec-custom-builds/patches/azl3-machine-deployment.yaml
  templates/test/ci/prow-dalec-custom-builds/patches/control-plane-custom-builds.yaml
  templates/test/ci/prow-dalec-custom-builds/patches/kubeadm-bootstrap-custom-builds.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#5889 [release-1.20] update azidentity to v1.12.0
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5893 check the path before emitting containerd logs from windows node
  test/e2e/azure_logcollector.go
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm
