Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2025-02, with the labels that each got.

#5408 pin go toolchain to 1.22.11 and go directive to 1.22.7
  go.mod
Labels: kind/bug, cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#5413 Bump go to v1.22.12
  go.mod
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm, area/dependency

#5427 Update some gomod deps
  api/v1beta1/azurecluster_validation.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5409 Add monitoring tag to control plane templates
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/ci/patches/azuremachinetemplate-monitoring.yaml
  templates/test/dev/cluster-template-custom-builds-load.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  templates/test/dev/custom-builds-load/patches/azuremachinetemplate-monitoring.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#5422 Updated cert-manager install to match current documentation
  docs/book/src/getting-started.md
Labels: cncf-cla: yes, size/XS, release-note, approved, kind/documentation, ok-to-test, lgtm

#5428 Update ASO to v2.11.0
  azure/converters/managedagentpool.go
  azure/converters/managedagentpool_test.go
  azure/converters/subnets_test.go
  azure/services/agentpools/agentpools.go
  azure/services/agentpools/agentpools_test.go
  azure/services/agentpools/spec.go
  azure/services/agentpools/spec_test.go
  azure/services/bastionhosts/spec.go
  azure/services/bastionhosts/spec_test.go
  azure/services/fleetsmembers/spec_test.go
  azure/services/managedclusters/managedclusters.go
  azure/services/managedclusters/spec.go
  azure/services/natgateways/spec.go
  azure/services/natgateways/spec_test.go
  azure/services/subnets/spec.go
  azure/services/subnets/spec_test.go
  azure/services/subnets/subnets_test.go
  azure/services/virtualnetworks/virtualnetworks_test.go
  controllers/azureasomanagedmachinepool_controller_test.go
  go.mod
  go.sum
  pkg/mutators/azureasomanagedcontrolplane.go
  pkg/mutators/azureasomanagedcontrolplane_test.go
  pkg/mutators/azureasomanagedmachinepool_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note, approved, lgtm

#5437 [release-1.17] Bump CAPI to v1.8.10
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note, approved, lgtm

#5440 Update pre commit hooks to check spelling and lint-fix on pre commit
  .pre-commit-config.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5443 fix: remove deprecated kube-apiserver cloud-provider arg
  templates/cluster-template-aad.yaml
  templates/cluster-template-apiserver-ilb.yaml
  templates/cluster-template-azure-bastion.yaml
  templates/cluster-template-azure-cni-v1.yaml
  templates/cluster-template-clusterclass.yaml
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-edgezone.yaml
  templates/cluster-template-ephemeral.yaml
  templates/cluster-template-flatcar-sysext.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-ipv6.yaml
  templates/cluster-template-machinepool-windows.yaml
  templates/cluster-template-machinepool.yaml
  templates/cluster-template-nvidia-gpu.yaml
  templates/cluster-template-private.yaml
  templates/cluster-template-windows-apiserver-ilb.yaml
  templates/cluster-template-windows.yaml
  templates/cluster-template.yaml
  templates/flavors/base/cluster-template.yaml
  templates/flavors/clusterclass/kubeadm-controlplane-template.yaml
  templates/test/ci/cluster-template-prow-apiserver-ilb.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dra.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-clusterclass-ci-default.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar-sysext.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-spot.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-dra.yaml
  templates/test/dev/cluster-template-custom-builds-load.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/data/infrastructure-azure/v1.17.3/cluster-template-prow-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1.17.3/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.18.0/cluster-template-prow-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1.18.0/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1beta1/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-upgrades.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#5436 fix: Update DRA test api version to v1beta1
  templates/test/ci/cluster-template-prow-ci-version-dra.yaml
  templates/test/ci/patches/dra-kubeadmcontrolplane.yaml
  templates/test/dev/cluster-template-custom-builds-dra.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, approved, lgtm

#5453 bug: Fix APIServerLB nil pointer deref
  azure/scope/cluster.go
  azure/scope/cluster_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#5416 Support any bootstrap provider with MachinePools
  config/rbac/role.yaml
  exp/controllers/azuremachinepool_controller.go
  exp/controllers/azuremachinepool_controller_test.go
  exp/controllers/helpers.go
  exp/controllers/helpers_test.go
  exp/controllers/suite_test.go
  main.go
Labels: kind/bug, kind/feature, cncf-cla: yes, size/L, approved, release-note-action-required, ok-to-test, lgtm, kind/deprecation

#5458 [release-1.17] bug: Fix APIServerLB nil pointer deref
  azure/scope/cluster.go
  azure/scope/cluster_test.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#5438 Bump CAPI to v1.9.5
  Makefile
  Tiltfile
  docs/book/src/getting-started.md
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5455 [release-1.17] fix: remove deprecated kube-apiserver cloud-provider arg
  templates/cluster-template-aad.yaml
  templates/cluster-template-azure-bastion.yaml
  templates/cluster-template-azure-cni-v1.yaml
  templates/cluster-template-clusterclass.yaml
  templates/cluster-template-dual-stack.yaml
  templates/cluster-template-edgezone.yaml
  templates/cluster-template-ephemeral.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-ipv6.yaml
  templates/cluster-template-machinepool-windows.yaml
  templates/cluster-template-machinepool.yaml
  templates/cluster-template-nvidia-gpu.yaml
  templates/cluster-template-private.yaml
  templates/cluster-template-windows.yaml
  templates/cluster-template.yaml
  templates/flavors/base/cluster-template.yaml
  templates/flavors/clusterclass/kubeadm-controlplane-template.yaml
  templates/test/ci/cluster-template-prow-azure-cni-v1.yaml
  templates/test/ci/cluster-template-prow-ci-version-dra.yaml
  templates/test/ci/cluster-template-prow-ci-version-dual-stack.yaml
  templates/test/ci/cluster-template-prow-ci-version-ipv6.yaml
  templates/test/ci/cluster-template-prow-ci-version.yaml
  templates/test/ci/cluster-template-prow-clusterclass-ci-default.yaml
  templates/test/ci/cluster-template-prow-custom-vnet.yaml
  templates/test/ci/cluster-template-prow-dual-stack.yaml
  templates/test/ci/cluster-template-prow-edgezone.yaml
  templates/test/ci/cluster-template-prow-flatcar.yaml
  templates/test/ci/cluster-template-prow-ipv6.yaml
  templates/test/ci/cluster-template-prow-load.yaml
  templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
  templates/test/ci/cluster-template-prow-machine-pool-flex.yaml
  templates/test/ci/cluster-template-prow-machine-pool.yaml
  templates/test/ci/cluster-template-prow-nvidia-gpu.yaml
  templates/test/ci/cluster-template-prow-private.yaml
  templates/test/ci/cluster-template-prow-spot.yaml
  templates/test/ci/cluster-template-prow.yaml
  templates/test/dev/cluster-template-custom-builds-dra.yaml
  templates/test/dev/cluster-template-custom-builds-machine-pool.yaml
  templates/test/dev/cluster-template-custom-builds.yaml
  test/e2e/data/infrastructure-azure/v1.15.3/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.16.1/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1beta1/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template-upgrades.yaml
  test/e2e/data/infrastructure-azure/v1beta1/cluster-template.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, kind/failing-test

#5459 [release-1.18] Bump CAPI to v1.9.5
  Makefile
  Tiltfile
  docs/book/src/getting-started.md
  go.mod
  go.sum
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm
