Repository kubernetes-sigs/cluster-api-provider-azure, pull requests merged in 2025-03, with the labels that each got.

#5451 Tiltfile aks as mgmt improvements
  Makefile
  Tiltfile
  docs/book/src/developers/development.md
  docs/book/src/developers/tilt-with-aks-as-mgmt-ilb.md
  hack/verify-starlark.sh
  scripts/aks-as-mgmt.sh
  scripts/kind-with-registry.sh
Labels: cncf-cla: yes, size/XL, release-note, approved, lgtm

#5464 CAPZ v1.17.4
  CHANGELOG/v1.17.4.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, kind/documentation, lgtm

#5468 Update hrefs in the documentation
  docs/book/src/developers/development.md
  docs/book/src/developers/tilt-with-aks-as-mgmt-ilb.md
  templates/cluster-template-apiserver-ilb-README.md
  templates/cluster-template-windows-apiserver-ilb-README.md
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm

#5470 update hrefs in netlify document
  docs/book/src/SUMMARY.md
  docs/book/src/developers/development.md
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5421 Add new authentication type UserAssignedIdentityCredentials
  api/v1beta1/azureclusteridentity_types.go
  api/v1beta1/azureclusteridentity_validation.go
  api/v1beta1/types.go
  azure/credential_cache.go
  azure/interfaces.go
  azure/mock_azure/azure_mock.go
  azure/scope/identity.go
  azure/scope/identity_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
  docs/book/src/topics/identities.md
  go.mod
  go.sum
  test/setup/credentials.json
Labels: kind/feature, cncf-cla: yes, size/L, release-note, approved, lgtm

#5479 Bump Otel packages to v1.35.0 | Prometheus to v1.57.0
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note, approved, lgtm

#5483 add kind-create in the readme
  docs/book/src/developers/development.md
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5481 Update handling Capabilities that have a float value
  azure/services/resourceskus/sku.go
  azure/services/scalesets/scalesets_test.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, ok-to-test, lgtm

#5497 [release-1.17] Update handling Capabilities that have a float value
  azure/services/resourceskus/sku.go
  azure/services/scalesets/scalesets_test.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#5442 [release-1.17] Bump CAPI to v1.8.10 in dev and test code
  Makefile
  Tiltfile
  test/e2e/config/azure-dev.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5500 Add v1.17.5 changelog
  CHANGELOG/v1.17.5.md
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5501 Add v1.18.2 changelog
  CHANGELOG/v1.18.2.md
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5506 add release 1.19 to CAPZ metadata
  metadata.yaml
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5507 add sample PR on updating milestone on test-infra on CAPZ minor release
  docs/book/src/developers/releasing.md
Labels: cncf-cla: yes, size/XS, kind/cleanup, release-note-none, approved, lgtm

#5508 Add changelog v1.19.0
  CHANGELOG/v1.19.0.md
Labels: cncf-cla: yes, kind/cleanup, size/L, release-note-none, approved, lgtm

#5513 Update Roadmap
  docs/book/src/roadmap.md
Labels: cncf-cla: yes, size/S, release-note, approved, kind/documentation, ok-to-test, lgtm

#5512 Bump rest of ASO to v2.11.0
  Makefile
  config/aso/crds.yaml
  config/aso/kustomization.yaml
Labels: kind/bug, cncf-cla: yes, release-note, approved, size/XXL, lgtm

#5510 Update provider metadata and API upgrade test versions to CAPZ v1.19.0
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.18.2/cluster-template-prow-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1.18.2/cluster-template-prow.yaml
  test/e2e/data/infrastructure-azure/v1.19.0/cluster-template-prow-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1.19.0/cluster-template-prow.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5518 Add v1.19.1 changelog
  CHANGELOG/v1.19.1.md
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/documentation, lgtm

#5519 Update provider metadata and API upgrade test versions to v1.19.1
  test/e2e/config/azure-dev.yaml
  test/e2e/data/infrastructure-azure/v1.19.1/cluster-template-prow-machine-and-machine-pool.yaml
  test/e2e/data/infrastructure-azure/v1.19.1/cluster-template-prow.yaml
Labels: cncf-cla: yes, size/S, kind/cleanup, release-note-none, approved, lgtm

#5521 Ensure all agent pool parameters are preserved in managed cluster creates
  .golangci.yml
  azure/converters/managedagentpool.go
  pkg/mutators/azureasomanagedcontrolplane.go
Labels: kind/bug, cncf-cla: yes, size/M, release-note, approved, lgtm

#5527 add FAQ for apparent ASO API version mismatches
  docs/book/src/topics/FAQ.md
Labels: cncf-cla: yes, size/S, release-note, approved, kind/documentation, lgtm

#5522 Refactored Tilt with AKS docs
  docs/book/src/developers/tilt-with-aks-as-mgmt-ilb.md
Labels: cncf-cla: yes, size/L, release-note, approved, kind/documentation, ok-to-test, lgtm

#5531 Bump golangci-lint to v1.64.8
  .github/workflows/pr-golangci-lint.yaml
  .golangci.yml
  api/v1beta1/azurecluster_validation_test.go
  azure/scope/machinepool_test.go
  controllers/asosecret_controller_test.go
  controllers/helpers_test.go
  test/e2e/azure_privatecluster.go
  test/e2e/azure_selfhosted.go
  test/e2e/azure_test.go
  test/e2e/capi_test.go
  test/e2e/helpers.go
  util/system/namespace_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, release-note-none, approved, lgtm
